/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { PageableResultSignedProjectVo } from './PageableResultSignedProjectVo';
import {
    PageableResultSignedProjectVoFromJSON,
    PageableResultSignedProjectVoFromJSONTyped,
    PageableResultSignedProjectVoToJSON,
    PageableResultSignedProjectVoToJSONTyped,
} from './PageableResultSignedProjectVo';

/**
 * 
 * @export
 * @interface ApiResponsePageableResultSignedProjectVo
 */
export interface ApiResponsePageableResultSignedProjectVo {
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponsePageableResultSignedProjectVo
     */
    success: boolean;
    /**
     * 
     * @type {PageableResultSignedProjectVo}
     * @memberof ApiResponsePageableResultSignedProjectVo
     */
    data?: PageableResultSignedProjectVo;
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageableResultSignedProjectVo
     */
    errorCode?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageableResultSignedProjectVo
     */
    errorMessage?: string;
}


/**
 * Check if a given object implements the ApiResponsePageableResultSignedProjectVo interface.
 */
export function instanceOfApiResponsePageableResultSignedProjectVo(value: object): value is ApiResponsePageableResultSignedProjectVo {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function ApiResponsePageableResultSignedProjectVoFromJSON(json: any): ApiResponsePageableResultSignedProjectVo {
    return ApiResponsePageableResultSignedProjectVoFromJSONTyped(json, false);
}

export function ApiResponsePageableResultSignedProjectVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePageableResultSignedProjectVo {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : PageableResultSignedProjectVoFromJSON(json['data']),
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
    };
}

export function ApiResponsePageableResultSignedProjectVoToJSON(json: any): ApiResponsePageableResultSignedProjectVo {
    return ApiResponsePageableResultSignedProjectVoToJSONTyped(json, false);
}

export function ApiResponsePageableResultSignedProjectVoToJSONTyped(value?: ApiResponsePageableResultSignedProjectVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PageableResultSignedProjectVoToJSON(value['data']),
        'errorCode': value['errorCode'],
        'errorMessage': value['errorMessage'],
    };
}


