/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { PreEvaluationStatisticsResponseVo } from './PreEvaluationStatisticsResponseVo';
import {
    PreEvaluationStatisticsResponseVoFromJSON,
    PreEvaluationStatisticsResponseVoFromJSONTyped,
    PreEvaluationStatisticsResponseVoToJSON,
    PreEvaluationStatisticsResponseVoToJSONTyped,
} from './PreEvaluationStatisticsResponseVo';

/**
 * 
 * @export
 * @interface ApiResponsePreEvaluationStatisticsResponseVo
 */
export interface ApiResponsePreEvaluationStatisticsResponseVo {
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponsePreEvaluationStatisticsResponseVo
     */
    success: boolean;
    /**
     * 
     * @type {PreEvaluationStatisticsResponseVo}
     * @memberof ApiResponsePreEvaluationStatisticsResponseVo
     */
    data?: PreEvaluationStatisticsResponseVo;
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePreEvaluationStatisticsResponseVo
     */
    errorCode?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePreEvaluationStatisticsResponseVo
     */
    errorMessage?: string;
}


/**
 * Check if a given object implements the ApiResponsePreEvaluationStatisticsResponseVo interface.
 */
export function instanceOfApiResponsePreEvaluationStatisticsResponseVo(value: object): value is ApiResponsePreEvaluationStatisticsResponseVo {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function ApiResponsePreEvaluationStatisticsResponseVoFromJSON(json: any): ApiResponsePreEvaluationStatisticsResponseVo {
    return ApiResponsePreEvaluationStatisticsResponseVoFromJSONTyped(json, false);
}

export function ApiResponsePreEvaluationStatisticsResponseVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponsePreEvaluationStatisticsResponseVo {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : PreEvaluationStatisticsResponseVoFromJSON(json['data']),
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
    };
}

export function ApiResponsePreEvaluationStatisticsResponseVoToJSON(json: any): ApiResponsePreEvaluationStatisticsResponseVo {
    return ApiResponsePreEvaluationStatisticsResponseVoToJSONTyped(json, false);
}

export function ApiResponsePreEvaluationStatisticsResponseVoToJSONTyped(value?: ApiResponsePreEvaluationStatisticsResponseVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PreEvaluationStatisticsResponseVoToJSON(value['data']),
        'errorCode': value['errorCode'],
        'errorMessage': value['errorMessage'],
    };
}


