/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtZsProjProjectSignedDto1
 */
export interface ExtZsProjProjectSignedDto1 {
    /**
     * _id
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    id?: string;
    /**
     * 项目名称
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    name?: string;
    /**
     * 项目编号
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    code?: string;
    /**
     * 区县编码
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    districtCode?: string;
    /**
     * 区县
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    district?: string;
    /**
     * 园区code
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zoneCode?: string;
    /**
     * 园区名称
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zoneName?: string;
    /**
     * 街镇
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    townCode?: string;
    /**
     * 街镇名
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    townName?: string;
    /**
     * 项目类别, 1-内资,2-外资 默认1
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    pType?: number;
    /**
     * 总投资额,  内资时单位是亿元,外资时单位是万美元
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    investMoney?: number;
    /**
     * 协议利用外资(万美元)
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    foreignMoney?: number;
    /**
     * 项目类型, t_proj_type
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    projType?: string;
    /**
     * 产业大类(不要显示的) t_proj_industry_first
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    industryFirstCode?: string;
    /**
     * 产业大类名称t_proj_industry_first
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    industryFirstName?: string;
    /**
     * 行业编码(不要显示的)t_proj_industry
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    industryCode?: string;
    /**
     * 行业编码(显示的)t_proj_industry
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    industryName?: string;
    /**
     * 1-服务业 2-制造业
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    bIndustry?: number;
    /**
     * 投资方名称
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    investor?: string;
    /**
     * 10-央企,20-民营巨头 30-世界500强或跨国公司 40-其它
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    investorType?: number;
    /**
     * 90-香港 ,100-台湾,110-日本,&#13;&#10;120-韩国,130-美国,140-欧洲,&#13;&#10;150-新加坡,80-外资其他&#13;&#10;10 北京&#13;&#10;20 上海&#13;&#10;30 广州&#13;&#10;40 深圳&#13;&#10;50 苏州&#13;&#10;60 长三角其他城市&#13;&#10;70 内资其他&#13;&#10;
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    investorPlace?: string;
    /**
     * 签约日期
     * @type {Date}
     * @memberof ExtZsProjProjectSignedDto1
     */
    signedDate?: Date;
    /**
     * 签约信息统计日期
     * @type {Date}
     * @memberof ExtZsProjProjectSignedDto1
     */
    signedStatDate?: Date;
    /**
     * 项目简介, 大文本框
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    desc?: string;
    /**
     * 备案（核准）项目名称
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    checkName?: string;
    /**
     * 备案（核准）投资总额（亿元）
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    checkMoney?: number;
    /**
     * 备案（核准）日期
     * @type {Date}
     * @memberof ExtZsProjProjectSignedDto1
     */
    checkDate?: Date;
    /**
     * 备案（核准）统计日期
     * @type {Date}
     * @memberof ExtZsProjProjectSignedDto1
     */
    checkStatDate?: Date;
    /**
     * 统一社会信用代码证
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    uCode?: string;
    /**
     * 注册公司名称
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    companyName?: string;
    /**
     * 注册资金
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    regMoney?: number;
    /**
     * 注册日期
     * @type {Date}
     * @memberof ExtZsProjProjectSignedDto1
     */
    regDate?: Date;
    /**
     * reg_foreign_money
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    regForeignMoney?: number;
    /**
     * 注册信息统计日期：
     * @type {Date}
     * @memberof ExtZsProjProjectSignedDto1
     */
    regStatDate?: Date;
    /**
     * 是否涉及固定资产投资项目1-是,2-否
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isFixedAsset?: number;
    /**
     * 是否涉及建设用地
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isUseLand?: number;
    /**
     * 建设用地规划许可证编号
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    landLicence?: string;
    /**
     * 完成报批日期
     * @type {Date}
     * @memberof ExtZsProjProjectSignedDto1
     */
    finishCheckDate?: Date;
    /**
     * 取得许可证日期
     * @type {Date}
     * @memberof ExtZsProjProjectSignedDto1
     */
    licenceDate?: Date;
    /**
     * 到账金额
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    receivedMoney?: number;
    /**
     * 0已签约   1已注册   5已备案   4完成报批   2已开工   3已竣工  
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    progress?: number;
    /**
     * 0-待审核  1-市级审核通过 2-市区审核通过,3-审核不通过  4-保存未提交
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    checkStatus?: number;
    /**
     * 开工日期
     * @type {Date}
     * @memberof ExtZsProjProjectSignedDto1
     */
    startDateCommit?: Date;
    /**
     * 竣工日期
     * @type {Date}
     * @memberof ExtZsProjProjectSignedDto1
     */
    completeDate?: Date;
    /**
     * 投资方联系人
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    linker?: string;
    /**
     * 投资方联系电话
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    linkerTel?: string;
    /**
     * 招商人员
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    linkerTz?: string;
    /**
     * 招商人员电话
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    linkerTzTel?: string;
    /**
     * 创建人的id,前端界面不管理,插入时用登录人帐号赋值
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    creatorId?: number;
    /**
     * 创建人姓名
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    creatorName?: string;
    /**
     * 创建人的部门编码
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    creatorDept?: string;
    /**
     * 最后一次审核结果描述
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    lastCheckDesc?: string;
    /**
     * 实际投入资金规模（亿元）
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    actualInvest?: number;
    /**
     * 开工认定编码
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    startCode?: string;
    /**
     * 实际建成产能
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    actualOutput?: number;
    /**
     * 累计实际投入资金规模（亿元
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    sumActualInvest?: number;
    /**
     * 修改人
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    updateId?: string;
    /**
     * 老项目创建人id
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    oldCreateBy?: string;
    /**
     * 老项目修改人id&#13;&#10;
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    oldUpdateBy?: string;
    /**
     * 老项目的主键ID
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    oldId?: string;
    /**
     * 是否为六大产业项目
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isSixpro?: number;
    /**
     * 六大产业项目编码
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    sixproCode?: string;
    /**
     * 备注
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    remarks?: string;
    /**
     * 1-正常，2-删除
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    status?: number;
    /**
     * 排序
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    orderIdx?: number;
    /**
     * 签约金额（外资已根据汇率转换）
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    qyje?: number;
    /**
     * 开工确认 1：是 0：否
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    kgqr?: string;
    /**
     * 竣工确认 1：是 0：否
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    jgqr?: string;
    /**
     * 项目评级
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    projLevel?: string;
    /**
     * 是否为新引进企业
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isNew?: number;
    /**
     * 是否为世界500强或全球专业领域行业龙头企业
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isWorld?: number;
    /**
     * 是否为国内500强或国内行业排名前100企业
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isChina?: number;
    /**
     * 是否为上市公司或上市辅导期企业
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isListed?: number;
    /**
     * 是否为独角兽企业
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isUnicorn?: number;
    /**
     * 已投资项目对属地政府亩均税收（万元）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    mujunTax?: string;
    /**
     * 主要客户
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    mainCustomer?: string;
    /**
     * 计划总投资（万元）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    planTotal?: string;
    /**
     * 注册资本（万元）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zhuceMoney?: string;
    /**
     * 计划开工时间
     * @type {Date}
     * @memberof ExtZsProjProjectSignedDto1
     */
    planStartDate?: Date;
    /**
     * 计划竣工时间
     * @type {Date}
     * @memberof ExtZsProjProjectSignedDto1
     */
    planEndDate?: Date;
    /**
     * 项目使用主要原、辅材料
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    projectMaterial?: string;
    /**
     * 主要流程工艺
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    mainProcess?: string;
    /**
     * 是否为新供地项目
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isNewproject?: string;
    /**
     * 项目选址位置
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    projectAddress?: string;
    /**
     * 申请用地面积（亩）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    sqLandArea?: string;
    /**
     * 行业是否属于高新技术产业分类目录
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isGx?: string;
    /**
     * 是否为高技术项目
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isGjs?: string;
    /**
     * 是否为国家工业战略性新兴产业
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isGyzl?: string;
    /**
     * 容积率
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    far?: string;
    /**
     * 预期开票销售（万元）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqKpxs?: string;
    /**
     * 预期税收（万元）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqSs?: string;
    /**
     * 预期用工人数（人）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqWorker?: string;
    /**
     * 固定资产投资占比（%）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    fixedPercent?: string;
    /**
     * 投资强度（万元/千平方米）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    investLevel?: string;
    /**
     * 预期亩均税收（万元/千平方米）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqMjtax?: string;
    /**
     * 是否有产生废水和挥发性有机废水排放
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isWaterpf?: string;
    /**
     * 产生废水是否含氮、磷或使用高挥发性有机化合物含量涂料、油墨、胶粘剂
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isWuran?: string;
    /**
     * 总能耗
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    totalUse?: string;
    /**
     * 项目是否含有研发团队、产学研合作及研发机构建设内容
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isYanfa?: string;
    /**
     * 项目是否拥有相关有效发明专利
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isZhuanli?: string;
    /**
     * 是否拟列入重点活动签约项目库
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isImportant?: string;
    /**
     * 是否为招商会项目
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isZsh?: string;
    /**
     * 招商会名称
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zshName?: string;
    /**
     * 预计年销售（万元）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yjYear?: string;
    /**
     * 备注
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    remark?: string;
    /**
     * 是否为瞪羚企业
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isGazelle?: number;
    /**
     * 是否为专精特新企业
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isSpecialized?: number;
    /**
     * 设备投资（万元）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    deviceInvest?: string;
    /**
     * 固定资产投资（万元）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    fixedInvest?: string;
    /**
     * 1 自行接洽 2 市级机关推荐
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    bResource?: number;
    /**
     * 市集机关名称
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    sjjgName?: string;
    /**
     * 企业联系人
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    qyLinker?: string;
    /**
     * 联系电话
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    qyPhone?: string;
    /**
     * 申请用地年
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    sqLandYear?: string;
    /**
     * 预期产值
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqCz?: string;
    /**
     * 自评价等级 优良一般
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zpjLevel?: string;
    /**
     * 重点项目类型
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    importProjType?: string;
    /**
     * 计划总投资第一期
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    planTotal1?: string;
    /**
     * 计划总投资第二期
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    planTotal2?: string;
    /**
     * 是否重点项目
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isImportProj?: string;
    /**
     * 风险投资方名称
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    fxName?: string;
    /**
     * 预期开票销售（第一年）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqKpxs1?: string;
    /**
     * 预期开票销售（第二年）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqKpxs2?: string;
    /**
     * 预期开票销售（第三年）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqKpxs3?: string;
    /**
     * 预期税收（第一年）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqSs1?: string;
    /**
     * 预期税收（第二年）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqSs2?: string;
    /**
     * 预期税收（第三年）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqSs3?: string;
    /**
     * 预期亩均税收（第一年）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqMjtax1?: string;
    /**
     * 预期亩均税收（第二年）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqMjtax2?: string;
    /**
     * 预期亩均税收（第三年）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqMjtax3?: string;
    /**
     * 投资方实力评估
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    tzfLevel?: string;
    /**
     * 投资方风险评估
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    tzfFx?: string;
    /**
     * 产业关联度
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    cyGl?: string;
    /**
     * 产品市场和工艺水平
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    cpGy?: string;
    /**
     * 团队力量
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    team?: string;
    /**
     * 专利数
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zlNum?: string;
    /**
     * 参赛获奖情况
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    hjContent?: string;
    /**
     * 认定进度
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    rProgress?: string;
    /**
     * 是否风险投资
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isWarningInvest?: string;
    /**
     * 是否项目支持
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    ifSjProj?: string;
    /**
     * 预期产值（第一年）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqCz1?: string;
    /**
     * 预期产值（第二年）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqCz2?: string;
    /**
     * 预期产值（第三年）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    yqCz3?: string;
    /**
     * 产品市场前景
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    cpQj?: string;
    /**
     * 工艺水平（工作效率）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    gyXl?: string;
    /**
     * 工艺水平（良品率）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    gyLp?: string;
    /**
     * 工艺水平（整体评价）
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    gyPj?: string;
    /**
     * 资产负债表
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zcfz?: string;
    /**
     * 利润表
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    lirun?: string;
    /**
     * 现金流量表
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    xjll?: string;
    /**
     * 固定资产与流动资产占比
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zczb?: string;
    /**
     * 资金来源
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zjly?: string;
    /**
     * 金融机构信用评级
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    xypj?: string;
    /**
     * 行业协会评价
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    xhpj?: string;
    /**
     * 纳税合规性
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    hegui?: string;
    /**
     * 综合评估等级
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zhpg?: string;
    /**
     * 评估状态
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    pgStatus?: string;
    /**
     * 是否科创项目
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isKcProj?: string;
    /**
     * 科创项目认定条件
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    kcProjTj?: string;
    /**
     * QFLP外资项目
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isQflp?: string;
    /**
     * 成效情况说明
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    cgRemark?: string;
    /**
     * 是否特殊行业
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    tshy?: string;
    /**
     * 有无准入限制
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zrxz?: string;
    /**
     * 是否两高项目
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    lgxm?: string;
    /**
     * 有无重金属排放
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zjspf?: string;
    /**
     * 产品市场现状
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    cpscxz?: string;
    /**
     * 工艺水平
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    gysp?: string;
    /**
     * 生产效率
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    scxl?: string;
    /**
     * 良品率
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    lpl?: string;
    /**
     * 是否高新技术企业
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isGxjs?: string;
    /**
     * 是否建立企业研发中心
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    ifBuildYfzx?: string;
    /**
     * 企业研发中心
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    buildYfzx?: string;
    /**
     * 省级以上科技或人才等项目
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    sjProj?: string;
    /**
     * 厂房租赁面积(平方米)
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zlLandArea?: string;
    /**
     * 折算用地
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zlLandAreaZs?: string;
    /**
     * 质态评估评审结果
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    ztpgzzcl?: string;
    /**
     * 批准部门及文号
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    pzwh?: string;
    /**
     * 批准日期
     * @type {Date}
     * @memberof ExtZsProjProjectSignedDto1
     */
    pzrq?: Date;
    /**
     * 成效情况
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    cxqk?: string;
    /**
     * qr_key
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    qrKey?: string;
    /**
     * 招商方
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    zsf?: string;
    /**
     * 投资方
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    tzf?: string;
    /**
     * 投资地址
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    tzdz?: string;
    /**
     * 佐证材料
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    xyzzcl?: string;
    /**
     * 是否有融资需求
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    isRzxq?: string;
    /**
     * 融资金额
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    rzMoney?: string;
    /**
     * 科创项目分类
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    kcProjType?: string;
    /**
     * 科创佐证材料
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    kccl?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    desc?: string;
    /**
     * 
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    rprogress?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtZsProjProjectSignedDto1
     */
    ucode?: string;
    /**
     * 
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    ptype?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    bindustry?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtZsProjProjectSignedDto1
     */
    bresource?: number;
}


/**
 * Check if a given object implements the ExtZsProjProjectSignedDto1 interface.
 */
export function instanceOfExtZsProjProjectSignedDto1(value: object): value is ExtZsProjProjectSignedDto1 {
    return true;
}

export function ExtZsProjProjectSignedDto1FromJSON(json: any): ExtZsProjProjectSignedDto1 {
    return ExtZsProjProjectSignedDto1FromJSONTyped(json, false);
}

export function ExtZsProjProjectSignedDto1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtZsProjProjectSignedDto1 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'districtCode': json['districtCode'] == null ? undefined : json['districtCode'],
        'district': json['district'] == null ? undefined : json['district'],
        'zoneCode': json['zoneCode'] == null ? undefined : json['zoneCode'],
        'zoneName': json['zoneName'] == null ? undefined : json['zoneName'],
        'townCode': json['townCode'] == null ? undefined : json['townCode'],
        'townName': json['townName'] == null ? undefined : json['townName'],
        'pType': json['pType'] == null ? undefined : json['pType'],
        'investMoney': json['investMoney'] == null ? undefined : json['investMoney'],
        'foreignMoney': json['foreignMoney'] == null ? undefined : json['foreignMoney'],
        'projType': json['projType'] == null ? undefined : json['projType'],
        'industryFirstCode': json['industryFirstCode'] == null ? undefined : json['industryFirstCode'],
        'industryFirstName': json['industryFirstName'] == null ? undefined : json['industryFirstName'],
        'industryCode': json['industryCode'] == null ? undefined : json['industryCode'],
        'industryName': json['industryName'] == null ? undefined : json['industryName'],
        'bIndustry': json['bIndustry'] == null ? undefined : json['bIndustry'],
        'investor': json['investor'] == null ? undefined : json['investor'],
        'investorType': json['investorType'] == null ? undefined : json['investorType'],
        'investorPlace': json['investorPlace'] == null ? undefined : json['investorPlace'],
        'signedDate': json['signedDate'] == null ? undefined : (new Date(json['signedDate'])),
        'signedStatDate': json['signedStatDate'] == null ? undefined : (new Date(json['signedStatDate'])),
        'desc': json['Desc'] == null ? undefined : json['Desc'],
        'checkName': json['checkName'] == null ? undefined : json['checkName'],
        'checkMoney': json['checkMoney'] == null ? undefined : json['checkMoney'],
        'checkDate': json['checkDate'] == null ? undefined : (new Date(json['checkDate'])),
        'checkStatDate': json['checkStatDate'] == null ? undefined : (new Date(json['checkStatDate'])),
        'uCode': json['uCode'] == null ? undefined : json['uCode'],
        'companyName': json['companyName'] == null ? undefined : json['companyName'],
        'regMoney': json['regMoney'] == null ? undefined : json['regMoney'],
        'regDate': json['regDate'] == null ? undefined : (new Date(json['regDate'])),
        'regForeignMoney': json['regForeignMoney'] == null ? undefined : json['regForeignMoney'],
        'regStatDate': json['regStatDate'] == null ? undefined : (new Date(json['regStatDate'])),
        'isFixedAsset': json['isFixedAsset'] == null ? undefined : json['isFixedAsset'],
        'isUseLand': json['isUseLand'] == null ? undefined : json['isUseLand'],
        'landLicence': json['landLicence'] == null ? undefined : json['landLicence'],
        'finishCheckDate': json['finishCheckDate'] == null ? undefined : (new Date(json['finishCheckDate'])),
        'licenceDate': json['licenceDate'] == null ? undefined : (new Date(json['licenceDate'])),
        'receivedMoney': json['receivedMoney'] == null ? undefined : json['receivedMoney'],
        'progress': json['progress'] == null ? undefined : json['progress'],
        'checkStatus': json['checkStatus'] == null ? undefined : json['checkStatus'],
        'startDateCommit': json['startDateCommit'] == null ? undefined : (new Date(json['startDateCommit'])),
        'completeDate': json['completeDate'] == null ? undefined : (new Date(json['completeDate'])),
        'linker': json['linker'] == null ? undefined : json['linker'],
        'linkerTel': json['linkerTel'] == null ? undefined : json['linkerTel'],
        'linkerTz': json['linkerTz'] == null ? undefined : json['linkerTz'],
        'linkerTzTel': json['linkerTzTel'] == null ? undefined : json['linkerTzTel'],
        'creatorId': json['creatorId'] == null ? undefined : json['creatorId'],
        'creatorName': json['creatorName'] == null ? undefined : json['creatorName'],
        'creatorDept': json['creatorDept'] == null ? undefined : json['creatorDept'],
        'lastCheckDesc': json['lastCheckDesc'] == null ? undefined : json['lastCheckDesc'],
        'actualInvest': json['actualInvest'] == null ? undefined : json['actualInvest'],
        'startCode': json['startCode'] == null ? undefined : json['startCode'],
        'actualOutput': json['actualOutput'] == null ? undefined : json['actualOutput'],
        'sumActualInvest': json['sumActualInvest'] == null ? undefined : json['sumActualInvest'],
        'updateId': json['updateId'] == null ? undefined : json['updateId'],
        'oldCreateBy': json['oldCreateBy'] == null ? undefined : json['oldCreateBy'],
        'oldUpdateBy': json['oldUpdateBy'] == null ? undefined : json['oldUpdateBy'],
        'oldId': json['oldId'] == null ? undefined : json['oldId'],
        'isSixpro': json['isSixpro'] == null ? undefined : json['isSixpro'],
        'sixproCode': json['sixproCode'] == null ? undefined : json['sixproCode'],
        'remarks': json['remarks'] == null ? undefined : json['remarks'],
        'status': json['Status'] == null ? undefined : json['Status'],
        'orderIdx': json['orderIdx'] == null ? undefined : json['orderIdx'],
        'qyje': json['qyje'] == null ? undefined : json['qyje'],
        'kgqr': json['kgqr'] == null ? undefined : json['kgqr'],
        'jgqr': json['jgqr'] == null ? undefined : json['jgqr'],
        'projLevel': json['projLevel'] == null ? undefined : json['projLevel'],
        'isNew': json['isNew'] == null ? undefined : json['isNew'],
        'isWorld': json['isWorld'] == null ? undefined : json['isWorld'],
        'isChina': json['isChina'] == null ? undefined : json['isChina'],
        'isListed': json['isListed'] == null ? undefined : json['isListed'],
        'isUnicorn': json['isUnicorn'] == null ? undefined : json['isUnicorn'],
        'mujunTax': json['mujunTax'] == null ? undefined : json['mujunTax'],
        'mainCustomer': json['mainCustomer'] == null ? undefined : json['mainCustomer'],
        'planTotal': json['planTotal'] == null ? undefined : json['planTotal'],
        'zhuceMoney': json['zhuceMoney'] == null ? undefined : json['zhuceMoney'],
        'planStartDate': json['planStartDate'] == null ? undefined : (new Date(json['planStartDate'])),
        'planEndDate': json['planEndDate'] == null ? undefined : (new Date(json['planEndDate'])),
        'projectMaterial': json['projectMaterial'] == null ? undefined : json['projectMaterial'],
        'mainProcess': json['mainProcess'] == null ? undefined : json['mainProcess'],
        'isNewproject': json['isNewproject'] == null ? undefined : json['isNewproject'],
        'projectAddress': json['projectAddress'] == null ? undefined : json['projectAddress'],
        'sqLandArea': json['sqLandArea'] == null ? undefined : json['sqLandArea'],
        'isGx': json['isGx'] == null ? undefined : json['isGx'],
        'isGjs': json['isGjs'] == null ? undefined : json['isGjs'],
        'isGyzl': json['isGyzl'] == null ? undefined : json['isGyzl'],
        'far': json['far'] == null ? undefined : json['far'],
        'yqKpxs': json['yqKpxs'] == null ? undefined : json['yqKpxs'],
        'yqSs': json['yqSs'] == null ? undefined : json['yqSs'],
        'yqWorker': json['yqWorker'] == null ? undefined : json['yqWorker'],
        'fixedPercent': json['fixedPercent'] == null ? undefined : json['fixedPercent'],
        'investLevel': json['investLevel'] == null ? undefined : json['investLevel'],
        'yqMjtax': json['yqMjtax'] == null ? undefined : json['yqMjtax'],
        'isWaterpf': json['isWaterpf'] == null ? undefined : json['isWaterpf'],
        'isWuran': json['isWuran'] == null ? undefined : json['isWuran'],
        'totalUse': json['totalUse'] == null ? undefined : json['totalUse'],
        'isYanfa': json['isYanfa'] == null ? undefined : json['isYanfa'],
        'isZhuanli': json['isZhuanli'] == null ? undefined : json['isZhuanli'],
        'isImportant': json['isImportant'] == null ? undefined : json['isImportant'],
        'isZsh': json['isZsh'] == null ? undefined : json['isZsh'],
        'zshName': json['zshName'] == null ? undefined : json['zshName'],
        'yjYear': json['yjYear'] == null ? undefined : json['yjYear'],
        'remark': json['remark'] == null ? undefined : json['remark'],
        'isGazelle': json['isGazelle'] == null ? undefined : json['isGazelle'],
        'isSpecialized': json['isSpecialized'] == null ? undefined : json['isSpecialized'],
        'deviceInvest': json['deviceInvest'] == null ? undefined : json['deviceInvest'],
        'fixedInvest': json['fixedInvest'] == null ? undefined : json['fixedInvest'],
        'bResource': json['bResource'] == null ? undefined : json['bResource'],
        'sjjgName': json['sjjgName'] == null ? undefined : json['sjjgName'],
        'qyLinker': json['qyLinker'] == null ? undefined : json['qyLinker'],
        'qyPhone': json['qyPhone'] == null ? undefined : json['qyPhone'],
        'sqLandYear': json['sqLandYear'] == null ? undefined : json['sqLandYear'],
        'yqCz': json['yqCz'] == null ? undefined : json['yqCz'],
        'zpjLevel': json['zpjLevel'] == null ? undefined : json['zpjLevel'],
        'importProjType': json['importProjType'] == null ? undefined : json['importProjType'],
        'planTotal1': json['planTotal1'] == null ? undefined : json['planTotal1'],
        'planTotal2': json['planTotal2'] == null ? undefined : json['planTotal2'],
        'isImportProj': json['isImportProj'] == null ? undefined : json['isImportProj'],
        'fxName': json['fxName'] == null ? undefined : json['fxName'],
        'yqKpxs1': json['yqKpxs1'] == null ? undefined : json['yqKpxs1'],
        'yqKpxs2': json['yqKpxs2'] == null ? undefined : json['yqKpxs2'],
        'yqKpxs3': json['yqKpxs3'] == null ? undefined : json['yqKpxs3'],
        'yqSs1': json['yqSs1'] == null ? undefined : json['yqSs1'],
        'yqSs2': json['yqSs2'] == null ? undefined : json['yqSs2'],
        'yqSs3': json['yqSs3'] == null ? undefined : json['yqSs3'],
        'yqMjtax1': json['yqMjtax1'] == null ? undefined : json['yqMjtax1'],
        'yqMjtax2': json['yqMjtax2'] == null ? undefined : json['yqMjtax2'],
        'yqMjtax3': json['yqMjtax3'] == null ? undefined : json['yqMjtax3'],
        'tzfLevel': json['tzfLevel'] == null ? undefined : json['tzfLevel'],
        'tzfFx': json['tzfFx'] == null ? undefined : json['tzfFx'],
        'cyGl': json['cyGl'] == null ? undefined : json['cyGl'],
        'cpGy': json['cpGy'] == null ? undefined : json['cpGy'],
        'team': json['team'] == null ? undefined : json['team'],
        'zlNum': json['zlNum'] == null ? undefined : json['zlNum'],
        'hjContent': json['hjContent'] == null ? undefined : json['hjContent'],
        'rProgress': json['rProgress'] == null ? undefined : json['rProgress'],
        'isWarningInvest': json['isWarningInvest'] == null ? undefined : json['isWarningInvest'],
        'ifSjProj': json['ifSjProj'] == null ? undefined : json['ifSjProj'],
        'yqCz1': json['yqCz1'] == null ? undefined : json['yqCz1'],
        'yqCz2': json['yqCz2'] == null ? undefined : json['yqCz2'],
        'yqCz3': json['yqCz3'] == null ? undefined : json['yqCz3'],
        'cpQj': json['cpQj'] == null ? undefined : json['cpQj'],
        'gyXl': json['gyXl'] == null ? undefined : json['gyXl'],
        'gyLp': json['gyLp'] == null ? undefined : json['gyLp'],
        'gyPj': json['gyPj'] == null ? undefined : json['gyPj'],
        'zcfz': json['zcfz'] == null ? undefined : json['zcfz'],
        'lirun': json['lirun'] == null ? undefined : json['lirun'],
        'xjll': json['xjll'] == null ? undefined : json['xjll'],
        'zczb': json['zczb'] == null ? undefined : json['zczb'],
        'zjly': json['zjly'] == null ? undefined : json['zjly'],
        'xypj': json['xypj'] == null ? undefined : json['xypj'],
        'xhpj': json['xhpj'] == null ? undefined : json['xhpj'],
        'hegui': json['hegui'] == null ? undefined : json['hegui'],
        'zhpg': json['zhpg'] == null ? undefined : json['zhpg'],
        'pgStatus': json['pgStatus'] == null ? undefined : json['pgStatus'],
        'isKcProj': json['isKcProj'] == null ? undefined : json['isKcProj'],
        'kcProjTj': json['kcProjTj'] == null ? undefined : json['kcProjTj'],
        'isQflp': json['isQflp'] == null ? undefined : json['isQflp'],
        'cgRemark': json['cgRemark'] == null ? undefined : json['cgRemark'],
        'tshy': json['tshy'] == null ? undefined : json['tshy'],
        'zrxz': json['zrxz'] == null ? undefined : json['zrxz'],
        'lgxm': json['lgxm'] == null ? undefined : json['lgxm'],
        'zjspf': json['zjspf'] == null ? undefined : json['zjspf'],
        'cpscxz': json['cpscxz'] == null ? undefined : json['cpscxz'],
        'gysp': json['gysp'] == null ? undefined : json['gysp'],
        'scxl': json['scxl'] == null ? undefined : json['scxl'],
        'lpl': json['lpl'] == null ? undefined : json['lpl'],
        'isGxjs': json['isGxjs'] == null ? undefined : json['isGxjs'],
        'ifBuildYfzx': json['ifBuildYfzx'] == null ? undefined : json['ifBuildYfzx'],
        'buildYfzx': json['buildYfzx'] == null ? undefined : json['buildYfzx'],
        'sjProj': json['sjProj'] == null ? undefined : json['sjProj'],
        'zlLandArea': json['zlLandArea'] == null ? undefined : json['zlLandArea'],
        'zlLandAreaZs': json['zlLandAreaZs'] == null ? undefined : json['zlLandAreaZs'],
        'ztpgzzcl': json['ztpgzzcl'] == null ? undefined : json['ztpgzzcl'],
        'pzwh': json['pzwh'] == null ? undefined : json['pzwh'],
        'pzrq': json['pzrq'] == null ? undefined : (new Date(json['pzrq'])),
        'cxqk': json['cxqk'] == null ? undefined : json['cxqk'],
        'qrKey': json['qrKey'] == null ? undefined : json['qrKey'],
        'zsf': json['zsf'] == null ? undefined : json['zsf'],
        'tzf': json['tzf'] == null ? undefined : json['tzf'],
        'tzdz': json['tzdz'] == null ? undefined : json['tzdz'],
        'xyzzcl': json['xyzzcl'] == null ? undefined : json['xyzzcl'],
        'isRzxq': json['isRzxq'] == null ? undefined : json['isRzxq'],
        'rzMoney': json['rzMoney'] == null ? undefined : json['rzMoney'],
        'kcProjType': json['kcProjType'] == null ? undefined : json['kcProjType'],
        'kccl': json['kccl'] == null ? undefined : json['kccl'],
        'desc': json['desc'] == null ? undefined : json['desc'],
        'status': json['status'] == null ? undefined : json['status'],
        'rprogress': json['rprogress'] == null ? undefined : json['rprogress'],
        'ucode': json['ucode'] == null ? undefined : json['ucode'],
        'ptype': json['ptype'] == null ? undefined : json['ptype'],
        'bindustry': json['bindustry'] == null ? undefined : json['bindustry'],
        'bresource': json['bresource'] == null ? undefined : json['bresource'],
    };
}

export function ExtZsProjProjectSignedDto1ToJSON(json: any): ExtZsProjProjectSignedDto1 {
    return ExtZsProjProjectSignedDto1ToJSONTyped(json, false);
}

export function ExtZsProjProjectSignedDto1ToJSONTyped(value?: ExtZsProjProjectSignedDto1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'districtCode': value['districtCode'],
        'district': value['district'],
        'zoneCode': value['zoneCode'],
        'zoneName': value['zoneName'],
        'townCode': value['townCode'],
        'townName': value['townName'],
        'pType': value['pType'],
        'investMoney': value['investMoney'],
        'foreignMoney': value['foreignMoney'],
        'projType': value['projType'],
        'industryFirstCode': value['industryFirstCode'],
        'industryFirstName': value['industryFirstName'],
        'industryCode': value['industryCode'],
        'industryName': value['industryName'],
        'bIndustry': value['bIndustry'],
        'investor': value['investor'],
        'investorType': value['investorType'],
        'investorPlace': value['investorPlace'],
        'signedDate': value['signedDate'] == null ? undefined : ((value['signedDate']).toISOString().substring(0,10)),
        'signedStatDate': value['signedStatDate'] == null ? undefined : ((value['signedStatDate']).toISOString().substring(0,10)),
        'Desc': value['desc'],
        'checkName': value['checkName'],
        'checkMoney': value['checkMoney'],
        'checkDate': value['checkDate'] == null ? undefined : ((value['checkDate']).toISOString().substring(0,10)),
        'checkStatDate': value['checkStatDate'] == null ? undefined : ((value['checkStatDate']).toISOString().substring(0,10)),
        'uCode': value['uCode'],
        'companyName': value['companyName'],
        'regMoney': value['regMoney'],
        'regDate': value['regDate'] == null ? undefined : ((value['regDate']).toISOString().substring(0,10)),
        'regForeignMoney': value['regForeignMoney'],
        'regStatDate': value['regStatDate'] == null ? undefined : ((value['regStatDate']).toISOString().substring(0,10)),
        'isFixedAsset': value['isFixedAsset'],
        'isUseLand': value['isUseLand'],
        'landLicence': value['landLicence'],
        'finishCheckDate': value['finishCheckDate'] == null ? undefined : ((value['finishCheckDate']).toISOString().substring(0,10)),
        'licenceDate': value['licenceDate'] == null ? undefined : ((value['licenceDate']).toISOString().substring(0,10)),
        'receivedMoney': value['receivedMoney'],
        'progress': value['progress'],
        'checkStatus': value['checkStatus'],
        'startDateCommit': value['startDateCommit'] == null ? undefined : ((value['startDateCommit']).toISOString().substring(0,10)),
        'completeDate': value['completeDate'] == null ? undefined : ((value['completeDate']).toISOString().substring(0,10)),
        'linker': value['linker'],
        'linkerTel': value['linkerTel'],
        'linkerTz': value['linkerTz'],
        'linkerTzTel': value['linkerTzTel'],
        'creatorId': value['creatorId'],
        'creatorName': value['creatorName'],
        'creatorDept': value['creatorDept'],
        'lastCheckDesc': value['lastCheckDesc'],
        'actualInvest': value['actualInvest'],
        'startCode': value['startCode'],
        'actualOutput': value['actualOutput'],
        'sumActualInvest': value['sumActualInvest'],
        'updateId': value['updateId'],
        'oldCreateBy': value['oldCreateBy'],
        'oldUpdateBy': value['oldUpdateBy'],
        'oldId': value['oldId'],
        'isSixpro': value['isSixpro'],
        'sixproCode': value['sixproCode'],
        'remarks': value['remarks'],
        'Status': value['status'],
        'orderIdx': value['orderIdx'],
        'qyje': value['qyje'],
        'kgqr': value['kgqr'],
        'jgqr': value['jgqr'],
        'projLevel': value['projLevel'],
        'isNew': value['isNew'],
        'isWorld': value['isWorld'],
        'isChina': value['isChina'],
        'isListed': value['isListed'],
        'isUnicorn': value['isUnicorn'],
        'mujunTax': value['mujunTax'],
        'mainCustomer': value['mainCustomer'],
        'planTotal': value['planTotal'],
        'zhuceMoney': value['zhuceMoney'],
        'planStartDate': value['planStartDate'] == null ? undefined : ((value['planStartDate']).toISOString().substring(0,10)),
        'planEndDate': value['planEndDate'] == null ? undefined : ((value['planEndDate']).toISOString().substring(0,10)),
        'projectMaterial': value['projectMaterial'],
        'mainProcess': value['mainProcess'],
        'isNewproject': value['isNewproject'],
        'projectAddress': value['projectAddress'],
        'sqLandArea': value['sqLandArea'],
        'isGx': value['isGx'],
        'isGjs': value['isGjs'],
        'isGyzl': value['isGyzl'],
        'far': value['far'],
        'yqKpxs': value['yqKpxs'],
        'yqSs': value['yqSs'],
        'yqWorker': value['yqWorker'],
        'fixedPercent': value['fixedPercent'],
        'investLevel': value['investLevel'],
        'yqMjtax': value['yqMjtax'],
        'isWaterpf': value['isWaterpf'],
        'isWuran': value['isWuran'],
        'totalUse': value['totalUse'],
        'isYanfa': value['isYanfa'],
        'isZhuanli': value['isZhuanli'],
        'isImportant': value['isImportant'],
        'isZsh': value['isZsh'],
        'zshName': value['zshName'],
        'yjYear': value['yjYear'],
        'remark': value['remark'],
        'isGazelle': value['isGazelle'],
        'isSpecialized': value['isSpecialized'],
        'deviceInvest': value['deviceInvest'],
        'fixedInvest': value['fixedInvest'],
        'bResource': value['bResource'],
        'sjjgName': value['sjjgName'],
        'qyLinker': value['qyLinker'],
        'qyPhone': value['qyPhone'],
        'sqLandYear': value['sqLandYear'],
        'yqCz': value['yqCz'],
        'zpjLevel': value['zpjLevel'],
        'importProjType': value['importProjType'],
        'planTotal1': value['planTotal1'],
        'planTotal2': value['planTotal2'],
        'isImportProj': value['isImportProj'],
        'fxName': value['fxName'],
        'yqKpxs1': value['yqKpxs1'],
        'yqKpxs2': value['yqKpxs2'],
        'yqKpxs3': value['yqKpxs3'],
        'yqSs1': value['yqSs1'],
        'yqSs2': value['yqSs2'],
        'yqSs3': value['yqSs3'],
        'yqMjtax1': value['yqMjtax1'],
        'yqMjtax2': value['yqMjtax2'],
        'yqMjtax3': value['yqMjtax3'],
        'tzfLevel': value['tzfLevel'],
        'tzfFx': value['tzfFx'],
        'cyGl': value['cyGl'],
        'cpGy': value['cpGy'],
        'team': value['team'],
        'zlNum': value['zlNum'],
        'hjContent': value['hjContent'],
        'rProgress': value['rProgress'],
        'isWarningInvest': value['isWarningInvest'],
        'ifSjProj': value['ifSjProj'],
        'yqCz1': value['yqCz1'],
        'yqCz2': value['yqCz2'],
        'yqCz3': value['yqCz3'],
        'cpQj': value['cpQj'],
        'gyXl': value['gyXl'],
        'gyLp': value['gyLp'],
        'gyPj': value['gyPj'],
        'zcfz': value['zcfz'],
        'lirun': value['lirun'],
        'xjll': value['xjll'],
        'zczb': value['zczb'],
        'zjly': value['zjly'],
        'xypj': value['xypj'],
        'xhpj': value['xhpj'],
        'hegui': value['hegui'],
        'zhpg': value['zhpg'],
        'pgStatus': value['pgStatus'],
        'isKcProj': value['isKcProj'],
        'kcProjTj': value['kcProjTj'],
        'isQflp': value['isQflp'],
        'cgRemark': value['cgRemark'],
        'tshy': value['tshy'],
        'zrxz': value['zrxz'],
        'lgxm': value['lgxm'],
        'zjspf': value['zjspf'],
        'cpscxz': value['cpscxz'],
        'gysp': value['gysp'],
        'scxl': value['scxl'],
        'lpl': value['lpl'],
        'isGxjs': value['isGxjs'],
        'ifBuildYfzx': value['ifBuildYfzx'],
        'buildYfzx': value['buildYfzx'],
        'sjProj': value['sjProj'],
        'zlLandArea': value['zlLandArea'],
        'zlLandAreaZs': value['zlLandAreaZs'],
        'ztpgzzcl': value['ztpgzzcl'],
        'pzwh': value['pzwh'],
        'pzrq': value['pzrq'] == null ? undefined : ((value['pzrq']).toISOString().substring(0,10)),
        'cxqk': value['cxqk'],
        'qrKey': value['qrKey'],
        'zsf': value['zsf'],
        'tzf': value['tzf'],
        'tzdz': value['tzdz'],
        'xyzzcl': value['xyzzcl'],
        'isRzxq': value['isRzxq'],
        'rzMoney': value['rzMoney'],
        'kcProjType': value['kcProjType'],
        'kccl': value['kccl'],
        'desc': value['desc'],
        'status': value['status'],
        'rprogress': value['rprogress'],
        'ucode': value['ucode'],
        'ptype': value['ptype'],
        'bindustry': value['bindustry'],
        'bresource': value['bresource'],
    };
}


