/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { ProjectCountInfo } from './ProjectCountInfo';
import {
    ProjectCountInfoFromJSON,
    ProjectCountInfoFromJSONTyped,
    ProjectCountInfoToJSON,
    ProjectCountInfoToJSONTyped,
} from './ProjectCountInfo';

/**
 * 
 * @export
 * @interface FourAboveEnterprises
 */
export interface FourAboveEnterprises {
    /**
     * 
     * @type {ProjectCountInfo}
     * @memberof FourAboveEnterprises
     */
    total?: ProjectCountInfo;
    /**
     * 
     * @type {ProjectCountInfo}
     * @memberof FourAboveEnterprises
     */
    industry?: ProjectCountInfo;
    /**
     * 
     * @type {ProjectCountInfo}
     * @memberof FourAboveEnterprises
     */
    construction?: ProjectCountInfo;
    /**
     * 
     * @type {ProjectCountInfo}
     * @memberof FourAboveEnterprises
     */
    wholesaleRetail?: ProjectCountInfo;
    /**
     * 
     * @type {ProjectCountInfo}
     * @memberof FourAboveEnterprises
     */
    hospitality?: ProjectCountInfo;
    /**
     * 
     * @type {ProjectCountInfo}
     * @memberof FourAboveEnterprises
     */
    realEstate?: ProjectCountInfo;
    /**
     * 
     * @type {ProjectCountInfo}
     * @memberof FourAboveEnterprises
     */
    service?: ProjectCountInfo;
}


/**
 * Check if a given object implements the FourAboveEnterprises interface.
 */
export function instanceOfFourAboveEnterprises(value: object): value is FourAboveEnterprises {
    return true;
}

export function FourAboveEnterprisesFromJSON(json: any): FourAboveEnterprises {
    return FourAboveEnterprisesFromJSONTyped(json, false);
}

export function FourAboveEnterprisesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FourAboveEnterprises {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : ProjectCountInfoFromJSON(json['total']),
        'industry': json['industry'] == null ? undefined : ProjectCountInfoFromJSON(json['industry']),
        'construction': json['construction'] == null ? undefined : ProjectCountInfoFromJSON(json['construction']),
        'wholesaleRetail': json['wholesaleRetail'] == null ? undefined : ProjectCountInfoFromJSON(json['wholesaleRetail']),
        'hospitality': json['hospitality'] == null ? undefined : ProjectCountInfoFromJSON(json['hospitality']),
        'realEstate': json['realEstate'] == null ? undefined : ProjectCountInfoFromJSON(json['realEstate']),
        'service': json['service'] == null ? undefined : ProjectCountInfoFromJSON(json['service']),
    };
}

export function FourAboveEnterprisesToJSON(json: any): FourAboveEnterprises {
    return FourAboveEnterprisesToJSONTyped(json, false);
}

export function FourAboveEnterprisesToJSONTyped(value?: FourAboveEnterprises | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': ProjectCountInfoToJSON(value['total']),
        'industry': ProjectCountInfoToJSON(value['industry']),
        'construction': ProjectCountInfoToJSON(value['construction']),
        'wholesaleRetail': ProjectCountInfoToJSON(value['wholesaleRetail']),
        'hospitality': ProjectCountInfoToJSON(value['hospitality']),
        'realEstate': ProjectCountInfoToJSON(value['realEstate']),
        'service': ProjectCountInfoToJSON(value['service']),
    };
}


