/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndustrialChainDistributionTreeVo
 */
export interface IndustrialChainDistributionTreeVo {
    /**
     * 创新集群
     * @type {string}
     * @memberof IndustrialChainDistributionTreeVo
     */
    innovativeCluster: string;
    /**
     * 产业链
     * @type {string}
     * @memberof IndustrialChainDistributionTreeVo
     */
    industrialChain: string;
    /**
     * 项目数量
     * @type {number}
     * @memberof IndustrialChainDistributionTreeVo
     */
    projectCount: number;
    /**
     * 投资额
     * @type {number}
     * @memberof IndustrialChainDistributionTreeVo
     */
    investmentAmount: number;
    /**
     * children
     * @type {Array<IndustrialChainDistributionTreeVo>}
     * @memberof IndustrialChainDistributionTreeVo
     */
    children: Array<IndustrialChainDistributionTreeVo>;
    /**
     * 创新集群
     * @type {string}
     * @memberof IndustrialChainDistributionTreeVo
     */
    innovativeClusterLabel: string;
    /**
     * 产业链
     * @type {string}
     * @memberof IndustrialChainDistributionTreeVo
     */
    industrialChainLabel: string;
    /**
     * 项目比重(%)
     * @type {number}
     * @memberof IndustrialChainDistributionTreeVo
     */
    projectProportion?: number;
    /**
     * 投资比重(%)
     * @type {number}
     * @memberof IndustrialChainDistributionTreeVo
     */
    investmentProportion?: number;
}


/**
 * Check if a given object implements the IndustrialChainDistributionTreeVo interface.
 */
export function instanceOfIndustrialChainDistributionTreeVo(value: object): value is IndustrialChainDistributionTreeVo {
    if (!('innovativeCluster' in value) || value['innovativeCluster'] === undefined) return false;
    if (!('industrialChain' in value) || value['industrialChain'] === undefined) return false;
    if (!('projectCount' in value) || value['projectCount'] === undefined) return false;
    if (!('investmentAmount' in value) || value['investmentAmount'] === undefined) return false;
    if (!('children' in value) || value['children'] === undefined) return false;
    if (!('innovativeClusterLabel' in value) || value['innovativeClusterLabel'] === undefined) return false;
    if (!('industrialChainLabel' in value) || value['industrialChainLabel'] === undefined) return false;
    return true;
}

export function IndustrialChainDistributionTreeVoFromJSON(json: any): IndustrialChainDistributionTreeVo {
    return IndustrialChainDistributionTreeVoFromJSONTyped(json, false);
}

export function IndustrialChainDistributionTreeVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndustrialChainDistributionTreeVo {
    if (json == null) {
        return json;
    }
    return {
        
        'innovativeCluster': json['innovativeCluster'],
        'industrialChain': json['industrialChain'],
        'projectCount': json['projectCount'],
        'investmentAmount': json['investmentAmount'],
        'children': ((json['children'] as Array<any>).map(IndustrialChainDistributionTreeVoFromJSON)),
        'innovativeClusterLabel': json['innovativeClusterLabel'],
        'industrialChainLabel': json['industrialChainLabel'],
        'projectProportion': json['projectProportion'] == null ? undefined : json['projectProportion'],
        'investmentProportion': json['investmentProportion'] == null ? undefined : json['investmentProportion'],
    };
}

export function IndustrialChainDistributionTreeVoToJSON(json: any): IndustrialChainDistributionTreeVo {
    return IndustrialChainDistributionTreeVoToJSONTyped(json, false);
}

export function IndustrialChainDistributionTreeVoToJSONTyped(value?: IndustrialChainDistributionTreeVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'innovativeCluster': value['innovativeCluster'],
        'industrialChain': value['industrialChain'],
        'projectCount': value['projectCount'],
        'investmentAmount': value['investmentAmount'],
        'children': ((value['children'] as Array<any>).map(IndustrialChainDistributionTreeVoToJSON)),
        'innovativeClusterLabel': value['innovativeClusterLabel'],
        'industrialChainLabel': value['industrialChainLabel'],
        'projectProportion': value['projectProportion'],
        'investmentProportion': value['investmentProportion'],
    };
}


