/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MyOrganizationVo
 */
export interface MyOrganizationVo {
    /**
     * 部门ID
     * @type {string}
     * @memberof MyOrganizationVo
     */
    id: string;
    /**
     * 部门名称
     * @type {string}
     * @memberof MyOrganizationVo
     */
    name: string;
    /**
     * 委办局ID
     * @type {string}
     * @memberof MyOrganizationVo
     */
    cobId: string;
    /**
     * 委办局名称
     * @type {string}
     * @memberof MyOrganizationVo
     */
    cobName?: string;
}


/**
 * Check if a given object implements the MyOrganizationVo interface.
 */
export function instanceOfMyOrganizationVo(value: object): value is MyOrganizationVo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('cobId' in value) || value['cobId'] === undefined) return false;
    return true;
}

export function MyOrganizationVoFromJSON(json: any): MyOrganizationVo {
    return MyOrganizationVoFromJSONTyped(json, false);
}

export function MyOrganizationVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyOrganizationVo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'cobId': json['cobId'],
        'cobName': json['cobName'] == null ? undefined : json['cobName'],
    };
}

export function MyOrganizationVoToJSON(json: any): MyOrganizationVo {
    return MyOrganizationVoToJSONTyped(json, false);
}

export function MyOrganizationVoToJSONTyped(value?: MyOrganizationVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'cobId': value['cobId'],
        'cobName': value['cobName'],
    };
}


