/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OnePlusFourClassify
 */
export interface OnePlusFourClassify {
    /**
     * 
     * @type {string}
     * @memberof OnePlusFourClassify
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof OnePlusFourClassify
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof OnePlusFourClassify
     */
    t1?: number;
    /**
     * 
     * @type {string}
     * @memberof OnePlusFourClassify
     */
    t2?: string;
    /**
     * 
     * @type {number}
     * @memberof OnePlusFourClassify
     */
    tze?: number;
}


/**
 * Check if a given object implements the OnePlusFourClassify interface.
 */
export function instanceOfOnePlusFourClassify(value: object): value is OnePlusFourClassify {
    return true;
}

export function OnePlusFourClassifyFromJSON(json: any): OnePlusFourClassify {
    return OnePlusFourClassifyFromJSONTyped(json, false);
}

export function OnePlusFourClassifyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnePlusFourClassify {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
        't1': json['t1'] == null ? undefined : json['t1'],
        't2': json['t2'] == null ? undefined : json['t2'],
        'tze': json['tze'] == null ? undefined : json['tze'],
    };
}

export function OnePlusFourClassifyToJSON(json: any): OnePlusFourClassify {
    return OnePlusFourClassifyToJSONTyped(json, false);
}

export function OnePlusFourClassifyToJSONTyped(value?: OnePlusFourClassify | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        't1': value['t1'],
        't2': value['t2'],
        'tze': value['tze'],
    };
}


