/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { ProjectScoreVo } from './ProjectScoreVo';
import {
    ProjectScoreVoFromJSON,
    ProjectScoreVoFromJSONTyped,
    ProjectScoreVoToJSON,
    ProjectScoreVoToJSONTyped,
} from './ProjectScoreVo';

/**
 * 
 * @export
 * @interface PageableResultProjectScoreVo
 */
export interface PageableResultProjectScoreVo {
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectScoreVo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectScoreVo
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectScoreVo
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectScoreVo
     */
    total: number;
    /**
     * 
     * @type {Array<ProjectScoreVo>}
     * @memberof PageableResultProjectScoreVo
     */
    records: Array<ProjectScoreVo>;
}


/**
 * Check if a given object implements the PageableResultProjectScoreVo interface.
 */
export function instanceOfPageableResultProjectScoreVo(value: object): value is PageableResultProjectScoreVo {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultProjectScoreVoFromJSON(json: any): PageableResultProjectScoreVo {
    return PageableResultProjectScoreVoFromJSONTyped(json, false);
}

export function PageableResultProjectScoreVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultProjectScoreVo {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(ProjectScoreVoFromJSON)),
    };
}

export function PageableResultProjectScoreVoToJSON(json: any): PageableResultProjectScoreVo {
    return PageableResultProjectScoreVoToJSONTyped(json, false);
}

export function PageableResultProjectScoreVoToJSONTyped(value?: PageableResultProjectScoreVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(ProjectScoreVoToJSON)),
    };
}


