/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { ProjectKeyProjectReviewVo } from './ProjectKeyProjectReviewVo';
import {
    ProjectKeyProjectReviewVoFromJSON,
    ProjectKeyProjectReviewVoFromJSONTyped,
    ProjectKeyProjectReviewVoToJSON,
    ProjectKeyProjectReviewVoToJSONTyped,
} from './ProjectKeyProjectReviewVo';

/**
 * 
 * @export
 * @interface PageableResultProjectKeyProjectReviewVo
 */
export interface PageableResultProjectKeyProjectReviewVo {
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectKeyProjectReviewVo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectKeyProjectReviewVo
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectKeyProjectReviewVo
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectKeyProjectReviewVo
     */
    total: number;
    /**
     * 
     * @type {Array<ProjectKeyProjectReviewVo>}
     * @memberof PageableResultProjectKeyProjectReviewVo
     */
    records: Array<ProjectKeyProjectReviewVo>;
}


/**
 * Check if a given object implements the PageableResultProjectKeyProjectReviewVo interface.
 */
export function instanceOfPageableResultProjectKeyProjectReviewVo(value: object): value is PageableResultProjectKeyProjectReviewVo {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultProjectKeyProjectReviewVoFromJSON(json: any): PageableResultProjectKeyProjectReviewVo {
    return PageableResultProjectKeyProjectReviewVoFromJSONTyped(json, false);
}

export function PageableResultProjectKeyProjectReviewVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultProjectKeyProjectReviewVo {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(ProjectKeyProjectReviewVoFromJSON)),
    };
}

export function PageableResultProjectKeyProjectReviewVoToJSON(json: any): PageableResultProjectKeyProjectReviewVo {
    return PageableResultProjectKeyProjectReviewVoToJSONTyped(json, false);
}

export function PageableResultProjectKeyProjectReviewVoToJSONTyped(value?: PageableResultProjectKeyProjectReviewVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(ProjectKeyProjectReviewVoToJSON)),
    };
}


