/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { ProjectVo } from './ProjectVo';
import {
    ProjectVoFromJSON,
    ProjectVoFromJSONTyped,
    ProjectVoToJSON,
    ProjectVoToJSONTyped,
} from './ProjectVo';

/**
 * 
 * @export
 * @interface PageableResultProjectVo
 */
export interface PageableResultProjectVo {
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectVo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectVo
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectVo
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectVo
     */
    total: number;
    /**
     * 
     * @type {Array<ProjectVo>}
     * @memberof PageableResultProjectVo
     */
    records: Array<ProjectVo>;
}


/**
 * Check if a given object implements the PageableResultProjectVo interface.
 */
export function instanceOfPageableResultProjectVo(value: object): value is PageableResultProjectVo {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultProjectVoFromJSON(json: any): PageableResultProjectVo {
    return PageableResultProjectVoFromJSONTyped(json, false);
}

export function PageableResultProjectVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultProjectVo {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(ProjectVoFromJSON)),
    };
}

export function PageableResultProjectVoToJSON(json: any): PageableResultProjectVo {
    return PageableResultProjectVoToJSONTyped(json, false);
}

export function PageableResultProjectVoToJSONTyped(value?: PageableResultProjectVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(ProjectVoToJSON)),
    };
}


