/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { TProjProjectSigned } from './TProjProjectSigned';
import {
    TProjProjectSignedFromJSON,
    TProjProjectSignedFromJSONTyped,
    TProjProjectSignedToJSON,
    TProjProjectSignedToJSONTyped,
} from './TProjProjectSigned';

/**
 * 
 * @export
 * @interface PageableResultTProjProjectSigned
 */
export interface PageableResultTProjProjectSigned {
    /**
     * 
     * @type {number}
     * @memberof PageableResultTProjProjectSigned
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTProjProjectSigned
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTProjProjectSigned
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTProjProjectSigned
     */
    total: number;
    /**
     * 
     * @type {Array<TProjProjectSigned>}
     * @memberof PageableResultTProjProjectSigned
     */
    records: Array<TProjProjectSigned>;
}


/**
 * Check if a given object implements the PageableResultTProjProjectSigned interface.
 */
export function instanceOfPageableResultTProjProjectSigned(value: object): value is PageableResultTProjProjectSigned {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultTProjProjectSignedFromJSON(json: any): PageableResultTProjProjectSigned {
    return PageableResultTProjProjectSignedFromJSONTyped(json, false);
}

export function PageableResultTProjProjectSignedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultTProjProjectSigned {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(TProjProjectSignedFromJSON)),
    };
}

export function PageableResultTProjProjectSignedToJSON(json: any): PageableResultTProjProjectSigned {
    return PageableResultTProjProjectSignedToJSONTyped(json, false);
}

export function PageableResultTProjProjectSignedToJSONTyped(value?: PageableResultTProjProjectSigned | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(TProjProjectSignedToJSON)),
    };
}


