/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { ProjectOnlineApprovalVo1 } from './ProjectOnlineApprovalVo1';
import {
    ProjectOnlineApprovalVo1FromJSON,
    ProjectOnlineApprovalVo1FromJSONTyped,
    ProjectOnlineApprovalVo1ToJSON,
    ProjectOnlineApprovalVo1ToJSONTyped,
} from './ProjectOnlineApprovalVo1';

/**
 * 
 * @export
 * @interface PageableResultProjectOnlineApprovalVo1
 */
export interface PageableResultProjectOnlineApprovalVo1 {
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectOnlineApprovalVo1
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectOnlineApprovalVo1
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectOnlineApprovalVo1
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectOnlineApprovalVo1
     */
    total: number;
    /**
     * 
     * @type {Array<ProjectOnlineApprovalVo1>}
     * @memberof PageableResultProjectOnlineApprovalVo1
     */
    records: Array<ProjectOnlineApprovalVo1>;
}


/**
 * Check if a given object implements the PageableResultProjectOnlineApprovalVo1 interface.
 */
export function instanceOfPageableResultProjectOnlineApprovalVo1(value: object): value is PageableResultProjectOnlineApprovalVo1 {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultProjectOnlineApprovalVo1FromJSON(json: any): PageableResultProjectOnlineApprovalVo1 {
    return PageableResultProjectOnlineApprovalVo1FromJSONTyped(json, false);
}

export function PageableResultProjectOnlineApprovalVo1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultProjectOnlineApprovalVo1 {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(ProjectOnlineApprovalVo1FromJSON)),
    };
}

export function PageableResultProjectOnlineApprovalVo1ToJSON(json: any): PageableResultProjectOnlineApprovalVo1 {
    return PageableResultProjectOnlineApprovalVo1ToJSONTyped(json, false);
}

export function PageableResultProjectOnlineApprovalVo1ToJSONTyped(value?: PageableResultProjectOnlineApprovalVo1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(ProjectOnlineApprovalVo1ToJSON)),
    };
}


