/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { LhbMajorProjectStatusVo } from './LhbMajorProjectStatusVo';
import {
    LhbMajorProjectStatusVoFromJSON,
    LhbMajorProjectStatusVoFromJSONTyped,
    LhbMajorProjectStatusVoToJSON,
    LhbMajorProjectStatusVoToJSONTyped,
} from './LhbMajorProjectStatusVo';

/**
 * 
 * @export
 * @interface PageableResultLhbMajorProjectStatusVo
 */
export interface PageableResultLhbMajorProjectStatusVo {
    /**
     * 
     * @type {number}
     * @memberof PageableResultLhbMajorProjectStatusVo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultLhbMajorProjectStatusVo
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultLhbMajorProjectStatusVo
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultLhbMajorProjectStatusVo
     */
    total: number;
    /**
     * 
     * @type {Array<LhbMajorProjectStatusVo>}
     * @memberof PageableResultLhbMajorProjectStatusVo
     */
    records: Array<LhbMajorProjectStatusVo>;
}


/**
 * Check if a given object implements the PageableResultLhbMajorProjectStatusVo interface.
 */
export function instanceOfPageableResultLhbMajorProjectStatusVo(value: object): value is PageableResultLhbMajorProjectStatusVo {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultLhbMajorProjectStatusVoFromJSON(json: any): PageableResultLhbMajorProjectStatusVo {
    return PageableResultLhbMajorProjectStatusVoFromJSONTyped(json, false);
}

export function PageableResultLhbMajorProjectStatusVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultLhbMajorProjectStatusVo {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(LhbMajorProjectStatusVoFromJSON)),
    };
}

export function PageableResultLhbMajorProjectStatusVoToJSON(json: any): PageableResultLhbMajorProjectStatusVo {
    return PageableResultLhbMajorProjectStatusVoToJSONTyped(json, false);
}

export function PageableResultLhbMajorProjectStatusVoToJSONTyped(value?: PageableResultLhbMajorProjectStatusVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(LhbMajorProjectStatusVoToJSON)),
    };
}


