/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { ProjectDigitalServiceVo } from './ProjectDigitalServiceVo';
import {
    ProjectDigitalServiceVoFromJSON,
    ProjectDigitalServiceVoFromJSONTyped,
    ProjectDigitalServiceVoToJSON,
    ProjectDigitalServiceVoToJSONTyped,
} from './ProjectDigitalServiceVo';

/**
 * 
 * @export
 * @interface PageableResultProjectDigitalServiceVo
 */
export interface PageableResultProjectDigitalServiceVo {
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectDigitalServiceVo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectDigitalServiceVo
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectDigitalServiceVo
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectDigitalServiceVo
     */
    total: number;
    /**
     * 
     * @type {Array<ProjectDigitalServiceVo>}
     * @memberof PageableResultProjectDigitalServiceVo
     */
    records: Array<ProjectDigitalServiceVo>;
}


/**
 * Check if a given object implements the PageableResultProjectDigitalServiceVo interface.
 */
export function instanceOfPageableResultProjectDigitalServiceVo(value: object): value is PageableResultProjectDigitalServiceVo {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultProjectDigitalServiceVoFromJSON(json: any): PageableResultProjectDigitalServiceVo {
    return PageableResultProjectDigitalServiceVoFromJSONTyped(json, false);
}

export function PageableResultProjectDigitalServiceVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultProjectDigitalServiceVo {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(ProjectDigitalServiceVoFromJSON)),
    };
}

export function PageableResultProjectDigitalServiceVoToJSON(json: any): PageableResultProjectDigitalServiceVo {
    return PageableResultProjectDigitalServiceVoToJSONTyped(json, false);
}

export function PageableResultProjectDigitalServiceVoToJSONTyped(value?: PageableResultProjectDigitalServiceVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(ProjectDigitalServiceVoToJSON)),
    };
}


