/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { TBizZone } from './TBizZone';
import {
    TBizZoneFromJSON,
    TBizZoneFromJSONTyped,
    TBizZoneToJSON,
    TBizZoneToJSONTyped,
} from './TBizZone';

/**
 * 
 * @export
 * @interface PageableResultTBizZone
 */
export interface PageableResultTBizZone {
    /**
     * 
     * @type {number}
     * @memberof PageableResultTBizZone
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTBizZone
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTBizZone
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTBizZone
     */
    total: number;
    /**
     * 
     * @type {Array<TBizZone>}
     * @memberof PageableResultTBizZone
     */
    records: Array<TBizZone>;
}


/**
 * Check if a given object implements the PageableResultTBizZone interface.
 */
export function instanceOfPageableResultTBizZone(value: object): value is PageableResultTBizZone {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultTBizZoneFromJSON(json: any): PageableResultTBizZone {
    return PageableResultTBizZoneFromJSONTyped(json, false);
}

export function PageableResultTBizZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultTBizZone {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(TBizZoneFromJSON)),
    };
}

export function PageableResultTBizZoneToJSON(json: any): PageableResultTBizZone {
    return PageableResultTBizZoneToJSONTyped(json, false);
}

export function PageableResultTBizZoneToJSONTyped(value?: PageableResultTBizZone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(TBizZoneToJSON)),
    };
}


