/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { ProjectFagaiKeyProjectsStatsVo } from './ProjectFagaiKeyProjectsStatsVo';
import {
    ProjectFagaiKeyProjectsStatsVoFromJSON,
    ProjectFagaiKeyProjectsStatsVoFromJSONTyped,
    ProjectFagaiKeyProjectsStatsVoToJSON,
    ProjectFagaiKeyProjectsStatsVoToJSONTyped,
} from './ProjectFagaiKeyProjectsStatsVo';

/**
 * 
 * @export
 * @interface PageableResultProjectFagaiKeyProjectsStatsVo
 */
export interface PageableResultProjectFagaiKeyProjectsStatsVo {
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectFagaiKeyProjectsStatsVo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectFagaiKeyProjectsStatsVo
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectFagaiKeyProjectsStatsVo
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectFagaiKeyProjectsStatsVo
     */
    total: number;
    /**
     * 
     * @type {Array<ProjectFagaiKeyProjectsStatsVo>}
     * @memberof PageableResultProjectFagaiKeyProjectsStatsVo
     */
    records: Array<ProjectFagaiKeyProjectsStatsVo>;
}


/**
 * Check if a given object implements the PageableResultProjectFagaiKeyProjectsStatsVo interface.
 */
export function instanceOfPageableResultProjectFagaiKeyProjectsStatsVo(value: object): value is PageableResultProjectFagaiKeyProjectsStatsVo {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultProjectFagaiKeyProjectsStatsVoFromJSON(json: any): PageableResultProjectFagaiKeyProjectsStatsVo {
    return PageableResultProjectFagaiKeyProjectsStatsVoFromJSONTyped(json, false);
}

export function PageableResultProjectFagaiKeyProjectsStatsVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultProjectFagaiKeyProjectsStatsVo {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(ProjectFagaiKeyProjectsStatsVoFromJSON)),
    };
}

export function PageableResultProjectFagaiKeyProjectsStatsVoToJSON(json: any): PageableResultProjectFagaiKeyProjectsStatsVo {
    return PageableResultProjectFagaiKeyProjectsStatsVoToJSONTyped(json, false);
}

export function PageableResultProjectFagaiKeyProjectsStatsVoToJSONTyped(value?: PageableResultProjectFagaiKeyProjectsStatsVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(ProjectFagaiKeyProjectsStatsVoToJSON)),
    };
}


