/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { TProjCheckLog } from './TProjCheckLog';
import {
    TProjCheckLogFromJSON,
    TProjCheckLogFromJSONTyped,
    TProjCheckLogToJSON,
    TProjCheckLogToJSONTyped,
} from './TProjCheckLog';

/**
 * 
 * @export
 * @interface PageableResultTProjCheckLog
 */
export interface PageableResultTProjCheckLog {
    /**
     * 
     * @type {number}
     * @memberof PageableResultTProjCheckLog
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTProjCheckLog
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTProjCheckLog
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTProjCheckLog
     */
    total: number;
    /**
     * 
     * @type {Array<TProjCheckLog>}
     * @memberof PageableResultTProjCheckLog
     */
    records: Array<TProjCheckLog>;
}


/**
 * Check if a given object implements the PageableResultTProjCheckLog interface.
 */
export function instanceOfPageableResultTProjCheckLog(value: object): value is PageableResultTProjCheckLog {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultTProjCheckLogFromJSON(json: any): PageableResultTProjCheckLog {
    return PageableResultTProjCheckLogFromJSONTyped(json, false);
}

export function PageableResultTProjCheckLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultTProjCheckLog {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(TProjCheckLogFromJSON)),
    };
}

export function PageableResultTProjCheckLogToJSON(json: any): PageableResultTProjCheckLog {
    return PageableResultTProjCheckLogToJSONTyped(json, false);
}

export function PageableResultTProjCheckLogToJSONTyped(value?: PageableResultTProjCheckLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(TProjCheckLogToJSON)),
    };
}


