/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectInfoFgVo
 */
export interface ProjectInfoFgVo {
    /**
     * 主键
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    id?: string;
    /**
     * 发改项目名称
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    fgProjectName?: string;
    /**
     * 全生命项目名称
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    fullLifecycleProjectName?: string;
    /**
     * 项目来源
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    projectSource?: string;
    /**
     * 项目代码
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    projectCode?: string;
    /**
     * 备案证项目代码
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    filingProjectCode?: string;
    /**
     * 申请备案时间
     * @type {Date}
     * @memberof ProjectInfoFgVo
     */
    filingApplicationTime?: Date;
    /**
     * 建设规模
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    constructionScale?: string;
    /**
     * 建设起止年限
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    constructionStartEndYears?: string;
    /**
     * 计划总投资(含单位)
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    plannedTotalInvestment?: string;
    /**
     * 计划总投资(数值)
     * @type {number}
     * @memberof ProjectInfoFgVo
     */
    plannedTotalInvestmentValue?: number;
    /**
     * 从开工到2025年底预计完成投资
     * @type {number}
     * @memberof ProjectInfoFgVo
     */
    expectedCompletedInvestmentTo2025?: number;
    /**
     * 2026年计划投资(含单位)
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    plannedInvestment2026?: string;
    /**
     * 2026年计划投资(数值)
     * @type {number}
     * @memberof ProjectInfoFgVo
     */
    plannedInvestment2026Value?: number;
    /**
     * 截至2025年底建设进度或前期工作进展情况
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    progressToEnd2025?: string;
    /**
     * 2026年建设进度
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    constructionProgress2026?: string;
    /**
     * 是否新开工
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    isNewStart?: string;
    /**
     * (预计)开工时间
     * @type {Date}
     * @memberof ProjectInfoFgVo
     */
    expectedStartTime?: Date;
    /**
     * (预计)首次达产时间
     * @type {Date}
     * @memberof ProjectInfoFgVo
     */
    expectedFirstProductionTime?: Date;
    /**
     * 投资主体名称
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    investmentEntityName?: string;
    /**
     * 服务推进责任单位
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    responsibleUnit?: string;
    /**
     * 项目所在园区、乡镇/街道
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    projectLocation?: string;
    /**
     * 投资性质
     * @type {string}
     * @memberof ProjectInfoFgVo
     */
    investmentNature?: string;
}


/**
 * Check if a given object implements the ProjectInfoFgVo interface.
 */
export function instanceOfProjectInfoFgVo(value: object): value is ProjectInfoFgVo {
    return true;
}

export function ProjectInfoFgVoFromJSON(json: any): ProjectInfoFgVo {
    return ProjectInfoFgVoFromJSONTyped(json, false);
}

export function ProjectInfoFgVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectInfoFgVo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fgProjectName': json['fgProjectName'] == null ? undefined : json['fgProjectName'],
        'fullLifecycleProjectName': json['fullLifecycleProjectName'] == null ? undefined : json['fullLifecycleProjectName'],
        'projectSource': json['projectSource'] == null ? undefined : json['projectSource'],
        'projectCode': json['projectCode'] == null ? undefined : json['projectCode'],
        'filingProjectCode': json['filingProjectCode'] == null ? undefined : json['filingProjectCode'],
        'filingApplicationTime': json['filingApplicationTime'] == null ? undefined : (new Date(json['filingApplicationTime'])),
        'constructionScale': json['constructionScale'] == null ? undefined : json['constructionScale'],
        'constructionStartEndYears': json['constructionStartEndYears'] == null ? undefined : json['constructionStartEndYears'],
        'plannedTotalInvestment': json['plannedTotalInvestment'] == null ? undefined : json['plannedTotalInvestment'],
        'plannedTotalInvestmentValue': json['plannedTotalInvestmentValue'] == null ? undefined : json['plannedTotalInvestmentValue'],
        'expectedCompletedInvestmentTo2025': json['expectedCompletedInvestmentTo2025'] == null ? undefined : json['expectedCompletedInvestmentTo2025'],
        'plannedInvestment2026': json['plannedInvestment2026'] == null ? undefined : json['plannedInvestment2026'],
        'plannedInvestment2026Value': json['plannedInvestment2026Value'] == null ? undefined : json['plannedInvestment2026Value'],
        'progressToEnd2025': json['progressToEnd2025'] == null ? undefined : json['progressToEnd2025'],
        'constructionProgress2026': json['constructionProgress2026'] == null ? undefined : json['constructionProgress2026'],
        'isNewStart': json['isNewStart'] == null ? undefined : json['isNewStart'],
        'expectedStartTime': json['expectedStartTime'] == null ? undefined : (new Date(json['expectedStartTime'])),
        'expectedFirstProductionTime': json['expectedFirstProductionTime'] == null ? undefined : (new Date(json['expectedFirstProductionTime'])),
        'investmentEntityName': json['investmentEntityName'] == null ? undefined : json['investmentEntityName'],
        'responsibleUnit': json['responsibleUnit'] == null ? undefined : json['responsibleUnit'],
        'projectLocation': json['projectLocation'] == null ? undefined : json['projectLocation'],
        'investmentNature': json['investmentNature'] == null ? undefined : json['investmentNature'],
    };
}

export function ProjectInfoFgVoToJSON(json: any): ProjectInfoFgVo {
    return ProjectInfoFgVoToJSONTyped(json, false);
}

export function ProjectInfoFgVoToJSONTyped(value?: ProjectInfoFgVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fgProjectName': value['fgProjectName'],
        'fullLifecycleProjectName': value['fullLifecycleProjectName'],
        'projectSource': value['projectSource'],
        'projectCode': value['projectCode'],
        'filingProjectCode': value['filingProjectCode'],
        'filingApplicationTime': value['filingApplicationTime'] == null ? undefined : ((value['filingApplicationTime']).toISOString().substring(0,10)),
        'constructionScale': value['constructionScale'],
        'constructionStartEndYears': value['constructionStartEndYears'],
        'plannedTotalInvestment': value['plannedTotalInvestment'],
        'plannedTotalInvestmentValue': value['plannedTotalInvestmentValue'],
        'expectedCompletedInvestmentTo2025': value['expectedCompletedInvestmentTo2025'],
        'plannedInvestment2026': value['plannedInvestment2026'],
        'plannedInvestment2026Value': value['plannedInvestment2026Value'],
        'progressToEnd2025': value['progressToEnd2025'],
        'constructionProgress2026': value['constructionProgress2026'],
        'isNewStart': value['isNewStart'],
        'expectedStartTime': value['expectedStartTime'] == null ? undefined : ((value['expectedStartTime']).toISOString().substring(0,10)),
        'expectedFirstProductionTime': value['expectedFirstProductionTime'] == null ? undefined : ((value['expectedFirstProductionTime']).toISOString().substring(0,10)),
        'investmentEntityName': value['investmentEntityName'],
        'responsibleUnit': value['responsibleUnit'],
        'projectLocation': value['projectLocation'],
        'investmentNature': value['investmentNature'],
    };
}


