/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectOnlineApprovalInfoVo
 */
export interface ProjectOnlineApprovalInfoVo {
    /**
     * 主键
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoVo
     */
    id?: string;
    /**
     * 在线审批ID
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoVo
     */
    onlineApprovalId?: string;
    /**
     * 行ID
     * @type {number}
     * @memberof ProjectOnlineApprovalInfoVo
     */
    rowId?: number;
    /**
     * 实施主体
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoVo
     */
    implementingSubject?: string;
    /**
     * 承办部门
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoVo
     */
    undertakingDepartment?: string;
    /**
     * 部门区划
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoVo
     */
    administrativeDivision?: string;
    /**
     * 审批事项
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoVo
     */
    approvalItem?: string;
    /**
     * 办理状态及时间
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoVo
     */
    approvalStatus?: string;
}


/**
 * Check if a given object implements the ProjectOnlineApprovalInfoVo interface.
 */
export function instanceOfProjectOnlineApprovalInfoVo(value: object): value is ProjectOnlineApprovalInfoVo {
    return true;
}

export function ProjectOnlineApprovalInfoVoFromJSON(json: any): ProjectOnlineApprovalInfoVo {
    return ProjectOnlineApprovalInfoVoFromJSONTyped(json, false);
}

export function ProjectOnlineApprovalInfoVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectOnlineApprovalInfoVo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'onlineApprovalId': json['onlineApprovalId'] == null ? undefined : json['onlineApprovalId'],
        'rowId': json['rowId'] == null ? undefined : json['rowId'],
        'implementingSubject': json['implementingSubject'] == null ? undefined : json['implementingSubject'],
        'undertakingDepartment': json['undertakingDepartment'] == null ? undefined : json['undertakingDepartment'],
        'administrativeDivision': json['administrativeDivision'] == null ? undefined : json['administrativeDivision'],
        'approvalItem': json['approvalItem'] == null ? undefined : json['approvalItem'],
        'approvalStatus': json['approvalStatus'] == null ? undefined : json['approvalStatus'],
    };
}

export function ProjectOnlineApprovalInfoVoToJSON(json: any): ProjectOnlineApprovalInfoVo {
    return ProjectOnlineApprovalInfoVoToJSONTyped(json, false);
}

export function ProjectOnlineApprovalInfoVoToJSONTyped(value?: ProjectOnlineApprovalInfoVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'onlineApprovalId': value['onlineApprovalId'],
        'rowId': value['rowId'],
        'implementingSubject': value['implementingSubject'],
        'undertakingDepartment': value['undertakingDepartment'],
        'administrativeDivision': value['administrativeDivision'],
        'approvalItem': value['approvalItem'],
        'approvalStatus': value['approvalStatus'],
    };
}


