/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectImportantProvinceInfoVo
 */
export interface ProjectImportantProvinceInfoVo {
    /**
     * 主键
     * @type {string}
     * @memberof ProjectImportantProvinceInfoVo
     */
    id?: string;
    /**
     * 年份
     * @type {number}
     * @memberof ProjectImportantProvinceInfoVo
     */
    year?: number;
    /**
     * 级别（如：省、市）
     * @type {string}
     * @memberof ProjectImportantProvinceInfoVo
     */
    level?: string;
    /**
     * 企业名称
     * @type {string}
     * @memberof ProjectImportantProvinceInfoVo
     */
    companyName?: string;
    /**
     * 项目名称
     * @type {string}
     * @memberof ProjectImportantProvinceInfoVo
     */
    projectName?: string;
    /**
     * 项目建设内容和规模
     * @type {string}
     * @memberof ProjectImportantProvinceInfoVo
     */
    constructionContentAndScale?: string;
    /**
     * 所属板块
     * @type {string}
     * @memberof ProjectImportantProvinceInfoVo
     */
    sector?: string;
    /**
     * 项目融资需求（万元）
     * @type {number}
     * @memberof ProjectImportantProvinceInfoVo
     */
    financingDemand?: number;
    /**
     * 到202X-1年底累计完成投资（万元）
     * @type {number}
     * @memberof ProjectImportantProvinceInfoVo
     */
    cumulativeInvestmentToPrevYear?: number;
    /**
     * 202X年计划投资（万元）
     * @type {number}
     * @memberof ProjectImportantProvinceInfoVo
     */
    plannedInvestmentCurrentYear?: number;
    /**
     * 预计新增经济效益-销售（万元）
     * @type {number}
     * @memberof ProjectImportantProvinceInfoVo
     */
    expectedSales?: number;
    /**
     * 预计新增经济效益-利润（万元）
     * @type {number}
     * @memberof ProjectImportantProvinceInfoVo
     */
    expectedProfit?: number;
    /**
     * 预计新增经济效益-税金（万元）
     * @type {number}
     * @memberof ProjectImportantProvinceInfoVo
     */
    expectedTax?: number;
    /**
     * 项目起止年月（起），示例：2022年1月
     * @type {Date}
     * @memberof ProjectImportantProvinceInfoVo
     */
    startDate?: Date;
    /**
     * 项目起止年月（止），示例：2024年12月
     * @type {Date}
     * @memberof ProjectImportantProvinceInfoVo
     */
    endDate?: Date;
    /**
     * 项目所属园区
     * @type {string}
     * @memberof ProjectImportantProvinceInfoVo
     */
    park?: string;
    /**
     * 项目阶段（如：续建结转下年）
     * @type {string}
     * @memberof ProjectImportantProvinceInfoVo
     */
    projectStage?: string;
    /**
     * 当年完成投资（万元）
     * @type {number}
     * @memberof ProjectImportantProvinceInfoVo
     */
    investmentCompletedCurrentYear?: number;
    /**
     * 项目形象进度
     * @type {string}
     * @memberof ProjectImportantProvinceInfoVo
     */
    projectProgress?: string;
    /**
     * 行业分类
     * @type {string}
     * @memberof ProjectImportantProvinceInfoVo
     */
    industryClassification?: string;
}


/**
 * Check if a given object implements the ProjectImportantProvinceInfoVo interface.
 */
export function instanceOfProjectImportantProvinceInfoVo(value: object): value is ProjectImportantProvinceInfoVo {
    return true;
}

export function ProjectImportantProvinceInfoVoFromJSON(json: any): ProjectImportantProvinceInfoVo {
    return ProjectImportantProvinceInfoVoFromJSONTyped(json, false);
}

export function ProjectImportantProvinceInfoVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectImportantProvinceInfoVo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'year': json['year'] == null ? undefined : json['year'],
        'level': json['level'] == null ? undefined : json['level'],
        'companyName': json['companyName'] == null ? undefined : json['companyName'],
        'projectName': json['projectName'] == null ? undefined : json['projectName'],
        'constructionContentAndScale': json['constructionContentAndScale'] == null ? undefined : json['constructionContentAndScale'],
        'sector': json['sector'] == null ? undefined : json['sector'],
        'financingDemand': json['financingDemand'] == null ? undefined : json['financingDemand'],
        'cumulativeInvestmentToPrevYear': json['cumulativeInvestmentToPrevYear'] == null ? undefined : json['cumulativeInvestmentToPrevYear'],
        'plannedInvestmentCurrentYear': json['plannedInvestmentCurrentYear'] == null ? undefined : json['plannedInvestmentCurrentYear'],
        'expectedSales': json['expectedSales'] == null ? undefined : json['expectedSales'],
        'expectedProfit': json['expectedProfit'] == null ? undefined : json['expectedProfit'],
        'expectedTax': json['expectedTax'] == null ? undefined : json['expectedTax'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'park': json['park'] == null ? undefined : json['park'],
        'projectStage': json['projectStage'] == null ? undefined : json['projectStage'],
        'investmentCompletedCurrentYear': json['investmentCompletedCurrentYear'] == null ? undefined : json['investmentCompletedCurrentYear'],
        'projectProgress': json['projectProgress'] == null ? undefined : json['projectProgress'],
        'industryClassification': json['industryClassification'] == null ? undefined : json['industryClassification'],
    };
}

export function ProjectImportantProvinceInfoVoToJSON(json: any): ProjectImportantProvinceInfoVo {
    return ProjectImportantProvinceInfoVoToJSONTyped(json, false);
}

export function ProjectImportantProvinceInfoVoToJSONTyped(value?: ProjectImportantProvinceInfoVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'year': value['year'],
        'level': value['level'],
        'companyName': value['companyName'],
        'projectName': value['projectName'],
        'constructionContentAndScale': value['constructionContentAndScale'],
        'sector': value['sector'],
        'financingDemand': value['financingDemand'],
        'cumulativeInvestmentToPrevYear': value['cumulativeInvestmentToPrevYear'],
        'plannedInvestmentCurrentYear': value['plannedInvestmentCurrentYear'],
        'expectedSales': value['expectedSales'],
        'expectedProfit': value['expectedProfit'],
        'expectedTax': value['expectedTax'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString().substring(0,10)),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString().substring(0,10)),
        'park': value['park'],
        'projectStage': value['projectStage'],
        'investmentCompletedCurrentYear': value['investmentCompletedCurrentYear'],
        'projectProgress': value['projectProgress'],
        'industryClassification': value['industryClassification'],
    };
}


