/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 项目预评估列表VO
 * @export
 * @interface ProjectPreEvaluationVo
 */
export interface ProjectPreEvaluationVo {
    /**
     * 项目ID
     * @type {string}
     * @memberof ProjectPreEvaluationVo
     */
    id?: string;
    /**
     * 项目名称
     * @type {string}
     * @memberof ProjectPreEvaluationVo
     */
    projectName?: string;
    /**
     * 所属板块（园区名称）
     * @type {string}
     * @memberof ProjectPreEvaluationVo
     */
    parkName?: string;
    /**
     * 国民经济分类
     * @type {string}
     * @memberof ProjectPreEvaluationVo
     */
    industryClassification?: string;
    /**
     * 投资方
     * @type {string}
     * @memberof ProjectPreEvaluationVo
     */
    investor?: string;
    /**
     * 投资总额（亿元）
     * @type {number}
     * @memberof ProjectPreEvaluationVo
     */
    totalInvestmentCny?: number;
    /**
     * 园区ID
     * @type {string}
     * @memberof ProjectPreEvaluationVo
     */
    park?: string;
    /**
     * 评估状态：未完成/已完成
     * @type {string}
     * @memberof ProjectPreEvaluationVo
     */
    evaluationStatus?: string;
    /**
     * 年度（查询条件）
     * @type {number}
     * @memberof ProjectPreEvaluationVo
     */
    year?: number;
    /**
     * 产业类型（查询条件）
     * @type {string}
     * @memberof ProjectPreEvaluationVo
     */
    projectType?: string;
    /**
     * 部门名称（查询条件）
     * @type {string}
     * @memberof ProjectPreEvaluationVo
     */
    deptName?: string;
}


/**
 * Check if a given object implements the ProjectPreEvaluationVo interface.
 */
export function instanceOfProjectPreEvaluationVo(value: object): value is ProjectPreEvaluationVo {
    return true;
}

export function ProjectPreEvaluationVoFromJSON(json: any): ProjectPreEvaluationVo {
    return ProjectPreEvaluationVoFromJSONTyped(json, false);
}

export function ProjectPreEvaluationVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectPreEvaluationVo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'projectName': json['projectName'] == null ? undefined : json['projectName'],
        'parkName': json['parkName'] == null ? undefined : json['parkName'],
        'industryClassification': json['industryClassification'] == null ? undefined : json['industryClassification'],
        'investor': json['investor'] == null ? undefined : json['investor'],
        'totalInvestmentCny': json['totalInvestmentCny'] == null ? undefined : json['totalInvestmentCny'],
        'park': json['park'] == null ? undefined : json['park'],
        'evaluationStatus': json['evaluationStatus'] == null ? undefined : json['evaluationStatus'],
        'year': json['year'] == null ? undefined : json['year'],
        'projectType': json['projectType'] == null ? undefined : json['projectType'],
        'deptName': json['deptName'] == null ? undefined : json['deptName'],
    };
}

export function ProjectPreEvaluationVoToJSON(json: any): ProjectPreEvaluationVo {
    return ProjectPreEvaluationVoToJSONTyped(json, false);
}

export function ProjectPreEvaluationVoToJSONTyped(value?: ProjectPreEvaluationVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'projectName': value['projectName'],
        'parkName': value['parkName'],
        'industryClassification': value['industryClassification'],
        'investor': value['investor'],
        'totalInvestmentCny': value['totalInvestmentCny'],
        'park': value['park'],
        'evaluationStatus': value['evaluationStatus'],
        'year': value['year'],
        'projectType': value['projectType'],
        'deptName': value['deptName'],
    };
}


