/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 签约项目统计信息
 * @export
 * @interface SignedProjectInfoVo
 */
export interface SignedProjectInfoVo {
    /**
     * 区域名称
     * @type {string}
     * @memberof SignedProjectInfoVo
     */
    district?: string;
    /**
     * 区域编码
     * @type {string}
     * @memberof SignedProjectInfoVo
     */
    districtCode?: string;
    /**
     * 项目总数
     * @type {number}
     * @memberof SignedProjectInfoVo
     */
    projNums?: number;
    /**
     * 项目同比
     * @type {string}
     * @memberof SignedProjectInfoVo
     */
    projTb?: string;
    /**
     * 总投资（亿元）
     * @type {number}
     * @memberof SignedProjectInfoVo
     */
    ztz?: number;
    /**
     * 总投资同比
     * @type {string}
     * @memberof SignedProjectInfoVo
     */
    ztzTb?: string;
    /**
     * 内资项目数
     * @type {number}
     * @memberof SignedProjectInfoVo
     */
    nzProjNum?: number;
    /**
     * 内资投资金额
     * @type {number}
     * @memberof SignedProjectInfoVo
     */
    nzTz?: number;
    /**
     * 外资项目数量
     * @type {number}
     * @memberof SignedProjectInfoVo
     */
    wzProjNum?: number;
    /**
     * 外资投资金额
     * @type {number}
     * @memberof SignedProjectInfoVo
     */
    wzTz?: number;
    /**
     * 去年项目数量
     * @type {number}
     * @memberof SignedProjectInfoVo
     */
    lastYearProjNums?: number;
    /**
     * 去年总投资
     * @type {number}
     * @memberof SignedProjectInfoVo
     */
    lastZtz?: number;
    /**
     * 签约日期
     * @type {string}
     * @memberof SignedProjectInfoVo
     */
    signedDate?: string;
    /**
     * 六大产业编码
     * @type {number}
     * @memberof SignedProjectInfoVo
     */
    sixproCode?: number;
    /**
     * 项目类型
     * @type {string}
     * @memberof SignedProjectInfoVo
     */
    projType?: string;
    /**
     * 项目名称
     * @type {string}
     * @memberof SignedProjectInfoVo
     */
    projName?: string;
    /**
     * 年度目标任务数
     * @type {number}
     * @memberof SignedProjectInfoVo
     */
    ndmbrws?: number;
    /**
     * 年度完成数
     * @type {number}
     * @memberof SignedProjectInfoVo
     */
    ndwcs?: number;
    /**
     * 年度目标任务完成率
     * @type {string}
     * @memberof SignedProjectInfoVo
     */
    ndmbwcl?: string;
}


/**
 * Check if a given object implements the SignedProjectInfoVo interface.
 */
export function instanceOfSignedProjectInfoVo(value: object): value is SignedProjectInfoVo {
    return true;
}

export function SignedProjectInfoVoFromJSON(json: any): SignedProjectInfoVo {
    return SignedProjectInfoVoFromJSONTyped(json, false);
}

export function SignedProjectInfoVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignedProjectInfoVo {
    if (json == null) {
        return json;
    }
    return {
        
        'district': json['district'] == null ? undefined : json['district'],
        'districtCode': json['districtCode'] == null ? undefined : json['districtCode'],
        'projNums': json['projNums'] == null ? undefined : json['projNums'],
        'projTb': json['projTb'] == null ? undefined : json['projTb'],
        'ztz': json['ztz'] == null ? undefined : json['ztz'],
        'ztzTb': json['ztzTb'] == null ? undefined : json['ztzTb'],
        'nzProjNum': json['nzProjNum'] == null ? undefined : json['nzProjNum'],
        'nzTz': json['nzTz'] == null ? undefined : json['nzTz'],
        'wzProjNum': json['wzProjNum'] == null ? undefined : json['wzProjNum'],
        'wzTz': json['wzTz'] == null ? undefined : json['wzTz'],
        'lastYearProjNums': json['lastYearProjNums'] == null ? undefined : json['lastYearProjNums'],
        'lastZtz': json['lastZtz'] == null ? undefined : json['lastZtz'],
        'signedDate': json['signedDate'] == null ? undefined : json['signedDate'],
        'sixproCode': json['sixproCode'] == null ? undefined : json['sixproCode'],
        'projType': json['projType'] == null ? undefined : json['projType'],
        'projName': json['projName'] == null ? undefined : json['projName'],
        'ndmbrws': json['ndmbrws'] == null ? undefined : json['ndmbrws'],
        'ndwcs': json['ndwcs'] == null ? undefined : json['ndwcs'],
        'ndmbwcl': json['ndmbwcl'] == null ? undefined : json['ndmbwcl'],
    };
}

export function SignedProjectInfoVoToJSON(json: any): SignedProjectInfoVo {
    return SignedProjectInfoVoToJSONTyped(json, false);
}

export function SignedProjectInfoVoToJSONTyped(value?: SignedProjectInfoVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'district': value['district'],
        'districtCode': value['districtCode'],
        'projNums': value['projNums'],
        'projTb': value['projTb'],
        'ztz': value['ztz'],
        'ztzTb': value['ztzTb'],
        'nzProjNum': value['nzProjNum'],
        'nzTz': value['nzTz'],
        'wzProjNum': value['wzProjNum'],
        'wzTz': value['wzTz'],
        'lastYearProjNums': value['lastYearProjNums'],
        'lastZtz': value['lastZtz'],
        'signedDate': value['signedDate'],
        'sixproCode': value['sixproCode'],
        'projType': value['projType'],
        'projName': value['projName'],
        'ndmbrws': value['ndmbrws'],
        'ndwcs': value['ndwcs'],
        'ndmbwcl': value['ndmbwcl'],
    };
}


