/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartProjectVo
 */
export interface StartProjectVo {
    /**
     * 项目ID
     * @type {string}
     * @memberof StartProjectVo
     */
    id?: string;
    /**
     * 项目名称
     * @type {string}
     * @memberof StartProjectVo
     */
    projectName?: string;
    /**
     * 所属板块（园区名称）
     * @type {string}
     * @memberof StartProjectVo
     */
    zoneName?: string;
    /**
     * 国民经济分类
     * @type {string}
     * @memberof StartProjectVo
     */
    industryClassification?: string;
    /**
     * 投资方
     * @type {string}
     * @memberof StartProjectVo
     */
    investor?: string;
    /**
     * 投资总额（亿元）
     * @type {number}
     * @memberof StartProjectVo
     */
    investmentAmount?: number;
    /**
     * 开工日期
     * @type {string}
     * @memberof StartProjectVo
     */
    startDate?: string;
    /**
     * 审核状态：0-无审核，1-部门审核中，2-部门审核通过，3-部门审核退回，4-专班审核中，5-专班审核通过，6-专班审核退回，7-审核不通过，8-通过不计分
     * @type {number}
     * @memberof StartProjectVo
     */
    auditStatus?: number;
    /**
     * 审核状态名称
     * @type {string}
     * @memberof StartProjectVo
     */
    auditStatusName?: string;
}


/**
 * Check if a given object implements the StartProjectVo interface.
 */
export function instanceOfStartProjectVo(value: object): value is StartProjectVo {
    return true;
}

export function StartProjectVoFromJSON(json: any): StartProjectVo {
    return StartProjectVoFromJSONTyped(json, false);
}

export function StartProjectVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartProjectVo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'projectName': json['projectName'] == null ? undefined : json['projectName'],
        'zoneName': json['zoneName'] == null ? undefined : json['zoneName'],
        'industryClassification': json['industryClassification'] == null ? undefined : json['industryClassification'],
        'investor': json['investor'] == null ? undefined : json['investor'],
        'investmentAmount': json['investmentAmount'] == null ? undefined : json['investmentAmount'],
        'startDate': json['startDate'] == null ? undefined : json['startDate'],
        'auditStatus': json['auditStatus'] == null ? undefined : json['auditStatus'],
        'auditStatusName': json['auditStatusName'] == null ? undefined : json['auditStatusName'],
    };
}

export function StartProjectVoToJSON(json: any): StartProjectVo {
    return StartProjectVoToJSONTyped(json, false);
}

export function StartProjectVoToJSONTyped(value?: StartProjectVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'projectName': value['projectName'],
        'zoneName': value['zoneName'],
        'industryClassification': value['industryClassification'],
        'investor': value['investor'],
        'investmentAmount': value['investmentAmount'],
        'startDate': value['startDate'],
        'auditStatus': value['auditStatus'],
        'auditStatusName': value['auditStatusName'],
    };
}


