/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemWorkflowDto
 */
export interface SystemWorkflowDto {
    /**
     * 工作流代码
     * @type {string}
     * @memberof SystemWorkflowDto
     */
    code?: string;
    /**
     * 工作流名称
     * @type {string}
     * @memberof SystemWorkflowDto
     */
    name?: string;
}


/**
 * Check if a given object implements the SystemWorkflowDto interface.
 */
export function instanceOfSystemWorkflowDto(value: object): value is SystemWorkflowDto {
    return true;
}

export function SystemWorkflowDtoFromJSON(json: any): SystemWorkflowDto {
    return SystemWorkflowDtoFromJSONTyped(json, false);
}

export function SystemWorkflowDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemWorkflowDto {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function SystemWorkflowDtoToJSON(json: any): SystemWorkflowDto {
    return SystemWorkflowDtoToJSONTyped(json, false);
}

export function SystemWorkflowDtoToJSONTyped(value?: SystemWorkflowDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
    };
}


