/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TProjPgyj
 */
export interface TProjPgyj {
    /**
     * 
     * @type {string}
     * @memberof TProjPgyj
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TProjPgyj
     */
    deleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TProjPgyj
     */
    createTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TProjPgyj
     */
    updateTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof TProjPgyj
     */
    signedId?: string;
    /**
     * 
     * @type {string}
     * @memberof TProjPgyj
     */
    pgbm?: string;
    /**
     * 
     * @type {string}
     * @memberof TProjPgyj
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TProjPgyj
     */
    pgyj?: string;
    /**
     * 
     * @type {string}
     * @memberof TProjPgyj
     */
    status?: string;
}


/**
 * Check if a given object implements the TProjPgyj interface.
 */
export function instanceOfTProjPgyj(value: object): value is TProjPgyj {
    return true;
}

export function TProjPgyjFromJSON(json: any): TProjPgyj {
    return TProjPgyjFromJSONTyped(json, false);
}

export function TProjPgyjFromJSONTyped(json: any, ignoreDiscriminator: boolean): TProjPgyj {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'createTime': json['createTime'] == null ? undefined : (new Date(json['createTime'])),
        'updateTime': json['updateTime'] == null ? undefined : (new Date(json['updateTime'])),
        'signedId': json['signedId'] == null ? undefined : json['signedId'],
        'pgbm': json['pgbm'] == null ? undefined : json['pgbm'],
        'name': json['name'] == null ? undefined : json['name'],
        'pgyj': json['pgyj'] == null ? undefined : json['pgyj'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TProjPgyjToJSON(json: any): TProjPgyj {
    return TProjPgyjToJSONTyped(json, false);
}

export function TProjPgyjToJSONTyped(value?: TProjPgyj | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'deleted': value['deleted'],
        'createTime': value['createTime'] == null ? undefined : ((value['createTime']).toISOString()),
        'updateTime': value['updateTime'] == null ? undefined : ((value['updateTime']).toISOString()),
        'signedId': value['signedId'],
        'pgbm': value['pgbm'],
        'name': value['name'],
        'pgyj': value['pgyj'],
        'status': value['status'],
    };
}


