/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnderConstruction
 */
export interface UnderConstruction {
    /**
     * 本月新增
     * @type {number}
     * @memberof UnderConstruction
     */
    monthIncreasement: number;
    /**
     * 当年累计新增
     * @type {number}
     * @memberof UnderConstruction
     */
    yearIncreasement: number;
    /**
     * 计划总投资
     * @type {number}
     * @memberof UnderConstruction
     */
    plannedTotalInvestment: number;
}


/**
 * Check if a given object implements the UnderConstruction interface.
 */
export function instanceOfUnderConstruction(value: object): value is UnderConstruction {
    if (!('monthIncreasement' in value) || value['monthIncreasement'] === undefined) return false;
    if (!('yearIncreasement' in value) || value['yearIncreasement'] === undefined) return false;
    if (!('plannedTotalInvestment' in value) || value['plannedTotalInvestment'] === undefined) return false;
    return true;
}

export function UnderConstructionFromJSON(json: any): UnderConstruction {
    return UnderConstructionFromJSONTyped(json, false);
}

export function UnderConstructionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnderConstruction {
    if (json == null) {
        return json;
    }
    return {
        
        'monthIncreasement': json['monthIncreasement'],
        'yearIncreasement': json['yearIncreasement'],
        'plannedTotalInvestment': json['plannedTotalInvestment'],
    };
}

export function UnderConstructionToJSON(json: any): UnderConstruction {
    return UnderConstructionToJSONTyped(json, false);
}

export function UnderConstructionToJSONTyped(value?: UnderConstruction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'monthIncreasement': value['monthIncreasement'],
        'yearIncreasement': value['yearIncreasement'],
        'plannedTotalInvestment': value['plannedTotalInvestment'],
    };
}


