/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Userinfo200Response
 */
export interface Userinfo200Response {
    /**
     * Client端的AppKey
     * @type {string}
     * @memberof Userinfo200Response
     */
    clientId: string;
    /**
     * Token格式，固定为bearer
     * @type {string}
     * @memberof Userinfo200Response
     */
    tokenType: string;
    /**
     * 访问令牌
     * @type {string}
     * @memberof Userinfo200Response
     */
    accessToken: string;
    /**
     * 刷新令牌
     * @type {string}
     * @memberof Userinfo200Response
     */
    refreshToken: string;
    /**
     * 访问令牌有效期（秒）
     * @type {number}
     * @memberof Userinfo200Response
     */
    expiresIn: number;
    /**
     * 刷新令牌有效期（秒）
     * @type {number}
     * @memberof Userinfo200Response
     */
    refreshExpiresIn: number;
    /**
     * 授权范围
     * @type {string}
     * @memberof Userinfo200Response
     */
    scope: string;
}


/**
 * Check if a given object implements the Userinfo200Response interface.
 */
export function instanceOfUserinfo200Response(value: object): value is Userinfo200Response {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    if (!('refreshExpiresIn' in value) || value['refreshExpiresIn'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function Userinfo200ResponseFromJSON(json: any): Userinfo200Response {
    return Userinfo200ResponseFromJSONTyped(json, false);
}

export function Userinfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Userinfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'tokenType': json['token_type'],
        'accessToken': json['access_token'],
        'refreshToken': json['refresh_token'],
        'expiresIn': json['expires_in'],
        'refreshExpiresIn': json['refresh_expires_in'],
        'scope': json['scope'],
    };
}

export function Userinfo200ResponseToJSON(json: any): Userinfo200Response {
    return Userinfo200ResponseToJSONTyped(json, false);
}

export function Userinfo200ResponseToJSONTyped(value?: Userinfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'token_type': value['tokenType'],
        'access_token': value['accessToken'],
        'refresh_token': value['refreshToken'],
        'expires_in': value['expiresIn'],
        'refresh_expires_in': value['refreshExpiresIn'],
        'scope': value['scope'],
    };
}


