/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileDownloadVo1
 */
export interface FileDownloadVo1 {
    /**
     * 
     * @type {string}
     * @memberof FileDownloadVo1
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FileDownloadVo1
     */
    path: string;
}


/**
 * Check if a given object implements the FileDownloadVo1 interface.
 */
export function instanceOfFileDownloadVo1(value: object): value is FileDownloadVo1 {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function FileDownloadVo1FromJSON(json: any): FileDownloadVo1 {
    return FileDownloadVo1FromJSONTyped(json, false);
}

export function FileDownloadVo1FromJSONTyped(json: any, ignoreDiscriminator: boolean): FileDownloadVo1 {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'path': json['path'],
    };
}

export function FileDownloadVo1ToJSON(json: any): FileDownloadVo1 {
    return FileDownloadVo1ToJSONTyped(json, false);
}

export function FileDownloadVo1ToJSONTyped(value?: FileDownloadVo1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'path': value['path'],
    };
}


