/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { ExtZsProjProjectSignedVo } from './ExtZsProjProjectSignedVo';
import {
    ExtZsProjProjectSignedVoFromJSON,
    ExtZsProjProjectSignedVoFromJSONTyped,
    ExtZsProjProjectSignedVoToJSON,
    ExtZsProjProjectSignedVoToJSONTyped,
} from './ExtZsProjProjectSignedVo';

/**
 * 
 * @export
 * @interface PageableResultExtZsProjProjectSignedVo
 */
export interface PageableResultExtZsProjProjectSignedVo {
    /**
     * 
     * @type {number}
     * @memberof PageableResultExtZsProjProjectSignedVo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultExtZsProjProjectSignedVo
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultExtZsProjProjectSignedVo
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultExtZsProjProjectSignedVo
     */
    total: number;
    /**
     * 
     * @type {Array<ExtZsProjProjectSignedVo>}
     * @memberof PageableResultExtZsProjProjectSignedVo
     */
    records: Array<ExtZsProjProjectSignedVo>;
}


/**
 * Check if a given object implements the PageableResultExtZsProjProjectSignedVo interface.
 */
export function instanceOfPageableResultExtZsProjProjectSignedVo(value: object): value is PageableResultExtZsProjProjectSignedVo {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultExtZsProjProjectSignedVoFromJSON(json: any): PageableResultExtZsProjProjectSignedVo {
    return PageableResultExtZsProjProjectSignedVoFromJSONTyped(json, false);
}

export function PageableResultExtZsProjProjectSignedVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultExtZsProjProjectSignedVo {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(ExtZsProjProjectSignedVoFromJSON)),
    };
}

export function PageableResultExtZsProjProjectSignedVoToJSON(json: any): PageableResultExtZsProjProjectSignedVo {
    return PageableResultExtZsProjProjectSignedVoToJSONTyped(json, false);
}

export function PageableResultExtZsProjProjectSignedVoToJSONTyped(value?: PageableResultExtZsProjProjectSignedVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(ExtZsProjProjectSignedVoToJSON)),
    };
}


