/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { IndustryChainVo } from './IndustryChainVo';
import {
    IndustryChainVoFromJSON,
    IndustryChainVoFromJSONTyped,
    IndustryChainVoToJSON,
    IndustryChainVoToJSONTyped,
} from './IndustryChainVo';

/**
 * 
 * @export
 * @interface PageableResultIndustryChainVo
 */
export interface PageableResultIndustryChainVo {
    /**
     * 
     * @type {number}
     * @memberof PageableResultIndustryChainVo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultIndustryChainVo
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultIndustryChainVo
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultIndustryChainVo
     */
    total: number;
    /**
     * 
     * @type {Array<IndustryChainVo>}
     * @memberof PageableResultIndustryChainVo
     */
    records: Array<IndustryChainVo>;
}


/**
 * Check if a given object implements the PageableResultIndustryChainVo interface.
 */
export function instanceOfPageableResultIndustryChainVo(value: object): value is PageableResultIndustryChainVo {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultIndustryChainVoFromJSON(json: any): PageableResultIndustryChainVo {
    return PageableResultIndustryChainVoFromJSONTyped(json, false);
}

export function PageableResultIndustryChainVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultIndustryChainVo {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(IndustryChainVoFromJSON)),
    };
}

export function PageableResultIndustryChainVoToJSON(json: any): PageableResultIndustryChainVo {
    return PageableResultIndustryChainVoToJSONTyped(json, false);
}

export function PageableResultIndustryChainVoToJSONTyped(value?: PageableResultIndustryChainVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(IndustryChainVoToJSON)),
    };
}


