/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectDigitalInvestmentAttractingVo
 */
export interface ProjectDigitalInvestmentAttractingVo {
    /**
     * 主键
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    id?: string;
    /**
     * 项目编号
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectCode?: string;
    /**
     * 项目名称
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectName?: string;
    /**
     * 所属区县
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    district?: string;
    /**
     * 所属区县
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    districtName?: string;
    /**
     * 所属园区
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    park?: string;
    /**
     * 所属园区
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    parkName?: string;
    /**
     * 国民经济分类
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    nationalEconomicClassification?: string;
    /**
     * 统一社会信用代码
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    uscc?: string;
    /**
     * 企业名称
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    companyName?: string;
    /**
     * 企业注册资金
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    companyRegistrationFunds?: number;
    /**
     * 企业注册日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    companyRegistrationDate?: Date;
    /**
     * 项目类别
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectCategory?: string;
    /**
     * 项目属性
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectAttribute?: string;
    /**
     * 项目内容
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectContent?: string;
    /**
     * 投资标识
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investmentFlag?: string;
    /**
     * 国别/地区
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    countryRegion?: string;
    /**
     * 具体国别/地区
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    specificCountryRegion?: string;
    /**
     * 投资方
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investor?: string;
    /**
     * 投资金额（亿美元/亿元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investmentAmount?: number;
    /**
     * 注册资本（亿美元/亿元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    registeredCapital?: number;
    /**
     * 洽谈进度
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    negotiationProgress?: string;
    /**
     * 国民经济行业分类
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    industryClassification?: string;
    /**
     * 当前项目进度
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    currentProjectProgress?: string;
    /**
     * 入库时间
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    entryTime?: Date;
    /**
     * 注册信息统计日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    registrationInfoStatisticsDate?: Date;
    /**
     * 佐证资料（营业执照）
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    certificateDataBusinessLicense?: string;
    /**
     * 备案（核准）项目名称
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    filingApprovalProjectName?: string;
    /**
     * 备案（核准）投资总额（亿元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    filingApprovalInvestmentTotal?: number;
    /**
     * 备案（核准）日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    filingApprovalDate?: Date;
    /**
     * 备案信息统计日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    filingInfoStatisticsDate?: Date;
    /**
     * 佐证资料（项目备案（核准）文件）
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    certificateDataProjectFilingApprovalFile?: string;
    /**
     * 是否涉及固定资产投资项目
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isFixedAssetInvestment?: boolean;
    /**
     * 是否涉及建设用地
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isConstructionLand?: boolean;
    /**
     * 建设用地规划许可证编号
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    constructionLandPlanningPermitNumber?: string;
    /**
     * 取得许可证日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    permitObtainDate?: Date;
    /**
     * 完成报批统计日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    completionReportStatisticsDate?: Date;
    /**
     * 佐证资料
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    certificateData?: string;
    /**
     * 开工确认日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    startConfirmDate?: Date;
    /**
     * 竣工确认日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    endConfirmDate?: Date;
    /**
     * 是否为新引进企业
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isNewIntroducedEnterprise?: boolean;
    /**
     * 项目评级（内资、外资；金额分级）
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectRating?: string;
    /**
     * 主要投资方名称
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    mainInvestorName?: string;
    /**
     * 计划总投资（亿元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plannedTotalInvestment?: number;
    /**
     * 项目选址位置
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectLocation?: string;
    /**
     * 是否为招商会项目
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isRecruitmentFairProject?: boolean;
    /**
     * 招商会名称
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    recruitmentFairName?: string;
    /**
     * 签约时间
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    signingTime?: Date;
    /**
     * 签约合同
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    signingContract?: string;
    /**
     * 项目总投资额（亿美元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    totalInvestmentUsd?: number;
    /**
     * 项目总投资额（亿元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    totalInvestmentCny?: number;
    /**
     * 项目来源
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectSource?: string;
    /**
     * 厂房类型
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    factoryType?: string;
    /**
     * 拟用地面积（平方米）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plannedLandArea?: number;
    /**
     * 拟租厂房面积（平方米）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plannedRentalFactoryArea?: number;
    /**
     * 拟购厂房面积（平方米）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plannedPurchaseFactoryArea?: number;
    /**
     * 预计年销量（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedAnnualSales?: number;
    /**
     * 预计年销售（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedAnnualSalesAmount?: number;
    /**
     * 预计年税收（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedAnnualTax?: number;
    /**
     * 项目类型
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectType?: string;
    /**
     * 产业大类名称
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    industryMajorClassName?: string;
    /**
     * 所属行业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    belongingIndustry?: string;
    /**
     * 投资方性质
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investorNature?: string;
    /**
     * 项目简介
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectProfile?: string;
    /**
     * 是否为世界500强或全球专业领域行业龙头企业
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isWorldTop500OrLeadingGlobalCompany?: boolean;
    /**
     * 是否为国内500强或国内行业排名前100企业
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isDomesticTop500OrTop100Company?: boolean;
    /**
     * 是否为上市公司或上市辅导期企业
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isPubliclyTradedOrPreIPOCompany?: boolean;
    /**
     * 是否为瞪羚、专精特新、独角兽企业
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isUnicornStartup?: boolean;
    /**
     * 已投资项目对属地政府亩均税收（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    averageTaxPerMuOfExistingInvestment?: number;
    /**
     * 主要客户
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    majorCustomers?: string;
    /**
     * 固定资产投资（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    fixedAssetInvestment?: number;
    /**
     * 设备投资（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    equipmentInvestment?: number;
    /**
     * 计划开工时间
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plannedStartTime?: Date;
    /**
     * 计划竣工时间
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plannedEndTime?: Date;
    /**
     * 项目使用主要原、辅材料
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    mainRawMaterialsUsed?: string;
    /**
     * 主要流程工艺
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    mainProcessTechnology?: string;
    /**
     * 是否为新供地项目
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isNewSupplyLandProject?: boolean;
    /**
     * 申请用地面积（亩）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    appliedLandArea?: number;
    /**
     * 行业是否属于高新技术产业分类目录
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isHighTechIndustry?: boolean;
    /**
     * 是否为高技术项目
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isHighTechProject?: boolean;
    /**
     * 是否为国家工业战略性新兴产业
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isNationalStrategicEmergingIndustry?: boolean;
    /**
     * 容积率（%）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plotRatioPercent?: number;
    /**
     * 预期开票销售（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedInvoiceSales?: number;
    /**
     * 预期税收（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedTax?: number;
    /**
     * 预期用工人数（人）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedEmployeeCount?: number;
    /**
     * 固定资产投资占比（%）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    fixedAssetInvestmentPercentage?: number;
    /**
     * 投资强度（万元/千平方米）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investmentIntensity?: number;
    /**
     * 预期亩均税收（万元/千平方米）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedAverageTax?: number;
    /**
     * 是否有产生废水和挥发性有机废水排放
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    wastewaterBy1?: boolean;
    /**
     * 产生废水是否含氮、磷或使用高挥发性有机化合物含量涂料、油墨、胶粘剂
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    wastewaterBy2?: boolean;
    /**
     * 总能耗
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    totalEnergyConsumption?: number;
    /**
     * 项目是否含有研发团队、产学研合作及研发机构建设内容
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    hasRndTeamAndCooperation?: boolean;
    /**
     * 项目是否拥有相关有效发明专利
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    hasValidPatents?: boolean;
    /**
     * 是否拟列入重点活动签约项目库
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isListedAsKeyActivitySigningProject?: boolean;
    /**
     * 备注
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    remarks?: string;
    /**
     * 协议利用外资（万美元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    agreementForeignDirectInvestment?: number;
    /**
     * 招商项目ID
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investOnlineId?: number;
    /**
     * 在线审批ID
     * @type {Array<string>}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    onlineApprovalIds?: Array<string>;
    /**
     * 工改ID
     * @type {Array<string>}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    constructionApprovalIds?: Array<string>;
    /**
     * 是否质态评估市级机关预警
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isQualityEvaluation?: boolean;
    /**
     * 是否项目审核
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isProjectReview?: boolean;
    /**
     * 质态评估是否完成
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isQualityEvaluationComplete?: boolean;
    /**
     * 项目审核是否完成
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isProjectReviewComplete?: boolean;
    /**
     * 是否项目竣工审批
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isProjectCompletionApproval?: boolean;
    /**
     * 是否项目开工审批
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isProjectStartApproval?: boolean;
    /**
     * 审核状态
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    auditStatus?: string;
    /**
     * 亮灯
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    light?: string;
    /**
     * 投资标识
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investmentFlagLabel?: string;
    /**
     * 当前项目进度
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    currentProjectProgressLabel?: string;
    /**
     * 是否涉及固定资产投资项目
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isFixedAssetInvestmentLabel?: string;
    /**
     * 是否涉及建设用地
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isConstructionLandLabel?: string;
    /**
     * 是否为新引进企业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isNewIntroducedEnterpriseLabel?: string;
    /**
     * 是否为招商会项目
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isRecruitmentFairProjectLabel?: string;
    /**
     * 是否为世界500强或全球专业领域行业龙头企业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isWorldTop500OrLeadingGlobalCompanyLabel?: string;
    /**
     * 是否为国内500强或国内行业排名前100企业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isDomesticTop500OrTop100CompanyLabel?: string;
    /**
     * 是否为上市公司或上市辅导期企业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isPubliclyTradedOrPreIPOCompanyLabel?: string;
    /**
     * 是否为瞪羚、专精特新、独角兽企业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isUnicornStartupLabel?: string;
    /**
     * 行业是否属于高新技术产业分类目录
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isHighTechIndustryLabel?: string;
    /**
     * 是否为高技术项目
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isHighTechProjectLabel?: string;
    /**
     * 是否为国家工业战略性新兴产业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isNationalStrategicEmergingIndustryLabel?: string;
    /**
     * 是否有产生废水和挥发性有机废水排放
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    wastewaterBy1Label?: string;
    /**
     * 产生废水是否含氮、磷或使用高挥发性有机化合物含量涂料、油墨、胶粘剂
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    wastewaterBy2Label?: string;
    /**
     * 项目是否含有研发团队、产学研合作及研发机构建设内容
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    hasRndTeamAndCooperationLabel?: string;
    /**
     * 项目是否拥有相关有效发明专利
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    hasValidPatentsLabel?: string;
    /**
     * 是否拟列入重点活动签约项目库
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isListedAsKeyActivitySigningProjectLabel?: string;
    /**
     * 是否质态评估市级机关预警
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isQualityEvaluationLabel?: string;
    /**
     * 是否项目审核
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isProjectReviewLabel?: string;
}


/**
 * Check if a given object implements the ProjectDigitalInvestmentAttractingVo interface.
 */
export function instanceOfProjectDigitalInvestmentAttractingVo(value: object): value is ProjectDigitalInvestmentAttractingVo {
    return true;
}

export function ProjectDigitalInvestmentAttractingVoFromJSON(json: any): ProjectDigitalInvestmentAttractingVo {
    return ProjectDigitalInvestmentAttractingVoFromJSONTyped(json, false);
}

export function ProjectDigitalInvestmentAttractingVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDigitalInvestmentAttractingVo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'projectCode': json['projectCode'] == null ? undefined : json['projectCode'],
        'projectName': json['projectName'] == null ? undefined : json['projectName'],
        'district': json['district'] == null ? undefined : json['district'],
        'districtName': json['districtName'] == null ? undefined : json['districtName'],
        'park': json['park'] == null ? undefined : json['park'],
        'parkName': json['parkName'] == null ? undefined : json['parkName'],
        'nationalEconomicClassification': json['nationalEconomicClassification'] == null ? undefined : json['nationalEconomicClassification'],
        'uscc': json['uscc'] == null ? undefined : json['uscc'],
        'companyName': json['companyName'] == null ? undefined : json['companyName'],
        'companyRegistrationFunds': json['companyRegistrationFunds'] == null ? undefined : json['companyRegistrationFunds'],
        'companyRegistrationDate': json['companyRegistrationDate'] == null ? undefined : (new Date(json['companyRegistrationDate'])),
        'projectCategory': json['projectCategory'] == null ? undefined : json['projectCategory'],
        'projectAttribute': json['projectAttribute'] == null ? undefined : json['projectAttribute'],
        'projectContent': json['projectContent'] == null ? undefined : json['projectContent'],
        'investmentFlag': json['investmentFlag'] == null ? undefined : json['investmentFlag'],
        'countryRegion': json['countryRegion'] == null ? undefined : json['countryRegion'],
        'specificCountryRegion': json['specificCountryRegion'] == null ? undefined : json['specificCountryRegion'],
        'investor': json['investor'] == null ? undefined : json['investor'],
        'investmentAmount': json['investmentAmount'] == null ? undefined : json['investmentAmount'],
        'registeredCapital': json['registeredCapital'] == null ? undefined : json['registeredCapital'],
        'negotiationProgress': json['negotiationProgress'] == null ? undefined : json['negotiationProgress'],
        'industryClassification': json['industryClassification'] == null ? undefined : json['industryClassification'],
        'currentProjectProgress': json['currentProjectProgress'] == null ? undefined : json['currentProjectProgress'],
        'entryTime': json['entryTime'] == null ? undefined : (new Date(json['entryTime'])),
        'registrationInfoStatisticsDate': json['registrationInfoStatisticsDate'] == null ? undefined : (new Date(json['registrationInfoStatisticsDate'])),
        'certificateDataBusinessLicense': json['certificateDataBusinessLicense'] == null ? undefined : json['certificateDataBusinessLicense'],
        'filingApprovalProjectName': json['filingApprovalProjectName'] == null ? undefined : json['filingApprovalProjectName'],
        'filingApprovalInvestmentTotal': json['filingApprovalInvestmentTotal'] == null ? undefined : json['filingApprovalInvestmentTotal'],
        'filingApprovalDate': json['filingApprovalDate'] == null ? undefined : (new Date(json['filingApprovalDate'])),
        'filingInfoStatisticsDate': json['filingInfoStatisticsDate'] == null ? undefined : (new Date(json['filingInfoStatisticsDate'])),
        'certificateDataProjectFilingApprovalFile': json['certificateDataProjectFilingApprovalFile'] == null ? undefined : json['certificateDataProjectFilingApprovalFile'],
        'isFixedAssetInvestment': json['isFixedAssetInvestment'] == null ? undefined : json['isFixedAssetInvestment'],
        'isConstructionLand': json['isConstructionLand'] == null ? undefined : json['isConstructionLand'],
        'constructionLandPlanningPermitNumber': json['constructionLandPlanningPermitNumber'] == null ? undefined : json['constructionLandPlanningPermitNumber'],
        'permitObtainDate': json['permitObtainDate'] == null ? undefined : (new Date(json['permitObtainDate'])),
        'completionReportStatisticsDate': json['completionReportStatisticsDate'] == null ? undefined : (new Date(json['completionReportStatisticsDate'])),
        'certificateData': json['certificateData'] == null ? undefined : json['certificateData'],
        'startConfirmDate': json['startConfirmDate'] == null ? undefined : (new Date(json['startConfirmDate'])),
        'endConfirmDate': json['endConfirmDate'] == null ? undefined : (new Date(json['endConfirmDate'])),
        'isNewIntroducedEnterprise': json['isNewIntroducedEnterprise'] == null ? undefined : json['isNewIntroducedEnterprise'],
        'projectRating': json['projectRating'] == null ? undefined : json['projectRating'],
        'mainInvestorName': json['mainInvestorName'] == null ? undefined : json['mainInvestorName'],
        'plannedTotalInvestment': json['plannedTotalInvestment'] == null ? undefined : json['plannedTotalInvestment'],
        'projectLocation': json['projectLocation'] == null ? undefined : json['projectLocation'],
        'isRecruitmentFairProject': json['isRecruitmentFairProject'] == null ? undefined : json['isRecruitmentFairProject'],
        'recruitmentFairName': json['recruitmentFairName'] == null ? undefined : json['recruitmentFairName'],
        'signingTime': json['signingTime'] == null ? undefined : (new Date(json['signingTime'])),
        'signingContract': json['signingContract'] == null ? undefined : json['signingContract'],
        'totalInvestmentUsd': json['totalInvestmentUsd'] == null ? undefined : json['totalInvestmentUsd'],
        'totalInvestmentCny': json['totalInvestmentCny'] == null ? undefined : json['totalInvestmentCny'],
        'projectSource': json['projectSource'] == null ? undefined : json['projectSource'],
        'factoryType': json['factoryType'] == null ? undefined : json['factoryType'],
        'plannedLandArea': json['plannedLandArea'] == null ? undefined : json['plannedLandArea'],
        'plannedRentalFactoryArea': json['plannedRentalFactoryArea'] == null ? undefined : json['plannedRentalFactoryArea'],
        'plannedPurchaseFactoryArea': json['plannedPurchaseFactoryArea'] == null ? undefined : json['plannedPurchaseFactoryArea'],
        'expectedAnnualSales': json['expectedAnnualSales'] == null ? undefined : json['expectedAnnualSales'],
        'expectedAnnualSalesAmount': json['expectedAnnualSalesAmount'] == null ? undefined : json['expectedAnnualSalesAmount'],
        'expectedAnnualTax': json['expectedAnnualTax'] == null ? undefined : json['expectedAnnualTax'],
        'projectType': json['projectType'] == null ? undefined : json['projectType'],
        'industryMajorClassName': json['industryMajorClassName'] == null ? undefined : json['industryMajorClassName'],
        'belongingIndustry': json['belongingIndustry'] == null ? undefined : json['belongingIndustry'],
        'investorNature': json['investorNature'] == null ? undefined : json['investorNature'],
        'projectProfile': json['projectProfile'] == null ? undefined : json['projectProfile'],
        'isWorldTop500OrLeadingGlobalCompany': json['isWorldTop500OrLeadingGlobalCompany'] == null ? undefined : json['isWorldTop500OrLeadingGlobalCompany'],
        'isDomesticTop500OrTop100Company': json['isDomesticTop500OrTop100Company'] == null ? undefined : json['isDomesticTop500OrTop100Company'],
        'isPubliclyTradedOrPreIPOCompany': json['isPubliclyTradedOrPreIPOCompany'] == null ? undefined : json['isPubliclyTradedOrPreIPOCompany'],
        'isUnicornStartup': json['isUnicornStartup'] == null ? undefined : json['isUnicornStartup'],
        'averageTaxPerMuOfExistingInvestment': json['averageTaxPerMuOfExistingInvestment'] == null ? undefined : json['averageTaxPerMuOfExistingInvestment'],
        'majorCustomers': json['majorCustomers'] == null ? undefined : json['majorCustomers'],
        'fixedAssetInvestment': json['fixedAssetInvestment'] == null ? undefined : json['fixedAssetInvestment'],
        'equipmentInvestment': json['equipmentInvestment'] == null ? undefined : json['equipmentInvestment'],
        'plannedStartTime': json['plannedStartTime'] == null ? undefined : (new Date(json['plannedStartTime'])),
        'plannedEndTime': json['plannedEndTime'] == null ? undefined : (new Date(json['plannedEndTime'])),
        'mainRawMaterialsUsed': json['mainRawMaterialsUsed'] == null ? undefined : json['mainRawMaterialsUsed'],
        'mainProcessTechnology': json['mainProcessTechnology'] == null ? undefined : json['mainProcessTechnology'],
        'isNewSupplyLandProject': json['isNewSupplyLandProject'] == null ? undefined : json['isNewSupplyLandProject'],
        'appliedLandArea': json['appliedLandArea'] == null ? undefined : json['appliedLandArea'],
        'isHighTechIndustry': json['isHighTechIndustry'] == null ? undefined : json['isHighTechIndustry'],
        'isHighTechProject': json['isHighTechProject'] == null ? undefined : json['isHighTechProject'],
        'isNationalStrategicEmergingIndustry': json['isNationalStrategicEmergingIndustry'] == null ? undefined : json['isNationalStrategicEmergingIndustry'],
        'plotRatioPercent': json['plotRatioPercent'] == null ? undefined : json['plotRatioPercent'],
        'expectedInvoiceSales': json['expectedInvoiceSales'] == null ? undefined : json['expectedInvoiceSales'],
        'expectedTax': json['expectedTax'] == null ? undefined : json['expectedTax'],
        'expectedEmployeeCount': json['expectedEmployeeCount'] == null ? undefined : json['expectedEmployeeCount'],
        'fixedAssetInvestmentPercentage': json['fixedAssetInvestmentPercentage'] == null ? undefined : json['fixedAssetInvestmentPercentage'],
        'investmentIntensity': json['investmentIntensity'] == null ? undefined : json['investmentIntensity'],
        'expectedAverageTax': json['expectedAverageTax'] == null ? undefined : json['expectedAverageTax'],
        'wastewaterBy1': json['wastewaterBy1'] == null ? undefined : json['wastewaterBy1'],
        'wastewaterBy2': json['wastewaterBy2'] == null ? undefined : json['wastewaterBy2'],
        'totalEnergyConsumption': json['totalEnergyConsumption'] == null ? undefined : json['totalEnergyConsumption'],
        'hasRndTeamAndCooperation': json['hasRndTeamAndCooperation'] == null ? undefined : json['hasRndTeamAndCooperation'],
        'hasValidPatents': json['hasValidPatents'] == null ? undefined : json['hasValidPatents'],
        'isListedAsKeyActivitySigningProject': json['isListedAsKeyActivitySigningProject'] == null ? undefined : json['isListedAsKeyActivitySigningProject'],
        'remarks': json['remarks'] == null ? undefined : json['remarks'],
        'agreementForeignDirectInvestment': json['agreementForeignDirectInvestment'] == null ? undefined : json['agreementForeignDirectInvestment'],
        'investOnlineId': json['investOnlineId'] == null ? undefined : json['investOnlineId'],
        'onlineApprovalIds': json['onlineApprovalIds'] == null ? undefined : json['onlineApprovalIds'],
        'constructionApprovalIds': json['constructionApprovalIds'] == null ? undefined : json['constructionApprovalIds'],
        'isQualityEvaluation': json['isQualityEvaluation'] == null ? undefined : json['isQualityEvaluation'],
        'isProjectReview': json['isProjectReview'] == null ? undefined : json['isProjectReview'],
        'isQualityEvaluationComplete': json['isQualityEvaluationComplete'] == null ? undefined : json['isQualityEvaluationComplete'],
        'isProjectReviewComplete': json['isProjectReviewComplete'] == null ? undefined : json['isProjectReviewComplete'],
        'isProjectCompletionApproval': json['isProjectCompletionApproval'] == null ? undefined : json['isProjectCompletionApproval'],
        'isProjectStartApproval': json['isProjectStartApproval'] == null ? undefined : json['isProjectStartApproval'],
        'auditStatus': json['auditStatus'] == null ? undefined : json['auditStatus'],
        'light': json['light'] == null ? undefined : json['light'],
        'investmentFlagLabel': json['investmentFlagLabel'] == null ? undefined : json['investmentFlagLabel'],
        'currentProjectProgressLabel': json['currentProjectProgressLabel'] == null ? undefined : json['currentProjectProgressLabel'],
        'isFixedAssetInvestmentLabel': json['isFixedAssetInvestmentLabel'] == null ? undefined : json['isFixedAssetInvestmentLabel'],
        'isConstructionLandLabel': json['isConstructionLandLabel'] == null ? undefined : json['isConstructionLandLabel'],
        'isNewIntroducedEnterpriseLabel': json['isNewIntroducedEnterpriseLabel'] == null ? undefined : json['isNewIntroducedEnterpriseLabel'],
        'isRecruitmentFairProjectLabel': json['isRecruitmentFairProjectLabel'] == null ? undefined : json['isRecruitmentFairProjectLabel'],
        'isWorldTop500OrLeadingGlobalCompanyLabel': json['isWorldTop500OrLeadingGlobalCompanyLabel'] == null ? undefined : json['isWorldTop500OrLeadingGlobalCompanyLabel'],
        'isDomesticTop500OrTop100CompanyLabel': json['isDomesticTop500OrTop100CompanyLabel'] == null ? undefined : json['isDomesticTop500OrTop100CompanyLabel'],
        'isPubliclyTradedOrPreIPOCompanyLabel': json['isPubliclyTradedOrPreIPOCompanyLabel'] == null ? undefined : json['isPubliclyTradedOrPreIPOCompanyLabel'],
        'isUnicornStartupLabel': json['isUnicornStartupLabel'] == null ? undefined : json['isUnicornStartupLabel'],
        'isHighTechIndustryLabel': json['isHighTechIndustryLabel'] == null ? undefined : json['isHighTechIndustryLabel'],
        'isHighTechProjectLabel': json['isHighTechProjectLabel'] == null ? undefined : json['isHighTechProjectLabel'],
        'isNationalStrategicEmergingIndustryLabel': json['isNationalStrategicEmergingIndustryLabel'] == null ? undefined : json['isNationalStrategicEmergingIndustryLabel'],
        'wastewaterBy1Label': json['wastewaterBy1Label'] == null ? undefined : json['wastewaterBy1Label'],
        'wastewaterBy2Label': json['wastewaterBy2Label'] == null ? undefined : json['wastewaterBy2Label'],
        'hasRndTeamAndCooperationLabel': json['hasRndTeamAndCooperationLabel'] == null ? undefined : json['hasRndTeamAndCooperationLabel'],
        'hasValidPatentsLabel': json['hasValidPatentsLabel'] == null ? undefined : json['hasValidPatentsLabel'],
        'isListedAsKeyActivitySigningProjectLabel': json['isListedAsKeyActivitySigningProjectLabel'] == null ? undefined : json['isListedAsKeyActivitySigningProjectLabel'],
        'isQualityEvaluationLabel': json['isQualityEvaluationLabel'] == null ? undefined : json['isQualityEvaluationLabel'],
        'isProjectReviewLabel': json['isProjectReviewLabel'] == null ? undefined : json['isProjectReviewLabel'],
    };
}

export function ProjectDigitalInvestmentAttractingVoToJSON(json: any): ProjectDigitalInvestmentAttractingVo {
    return ProjectDigitalInvestmentAttractingVoToJSONTyped(json, false);
}

export function ProjectDigitalInvestmentAttractingVoToJSONTyped(value?: ProjectDigitalInvestmentAttractingVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'projectCode': value['projectCode'],
        'projectName': value['projectName'],
        'district': value['district'],
        'districtName': value['districtName'],
        'park': value['park'],
        'parkName': value['parkName'],
        'nationalEconomicClassification': value['nationalEconomicClassification'],
        'uscc': value['uscc'],
        'companyName': value['companyName'],
        'companyRegistrationFunds': value['companyRegistrationFunds'],
        'companyRegistrationDate': value['companyRegistrationDate'] == null ? undefined : ((value['companyRegistrationDate']).toISOString().substring(0,10)),
        'projectCategory': value['projectCategory'],
        'projectAttribute': value['projectAttribute'],
        'projectContent': value['projectContent'],
        'investmentFlag': value['investmentFlag'],
        'countryRegion': value['countryRegion'],
        'specificCountryRegion': value['specificCountryRegion'],
        'investor': value['investor'],
        'investmentAmount': value['investmentAmount'],
        'registeredCapital': value['registeredCapital'],
        'negotiationProgress': value['negotiationProgress'],
        'industryClassification': value['industryClassification'],
        'currentProjectProgress': value['currentProjectProgress'],
        'entryTime': value['entryTime'] == null ? undefined : ((value['entryTime']).toISOString()),
        'registrationInfoStatisticsDate': value['registrationInfoStatisticsDate'] == null ? undefined : ((value['registrationInfoStatisticsDate']).toISOString().substring(0,10)),
        'certificateDataBusinessLicense': value['certificateDataBusinessLicense'],
        'filingApprovalProjectName': value['filingApprovalProjectName'],
        'filingApprovalInvestmentTotal': value['filingApprovalInvestmentTotal'],
        'filingApprovalDate': value['filingApprovalDate'] == null ? undefined : ((value['filingApprovalDate']).toISOString().substring(0,10)),
        'filingInfoStatisticsDate': value['filingInfoStatisticsDate'] == null ? undefined : ((value['filingInfoStatisticsDate']).toISOString().substring(0,10)),
        'certificateDataProjectFilingApprovalFile': value['certificateDataProjectFilingApprovalFile'],
        'isFixedAssetInvestment': value['isFixedAssetInvestment'],
        'isConstructionLand': value['isConstructionLand'],
        'constructionLandPlanningPermitNumber': value['constructionLandPlanningPermitNumber'],
        'permitObtainDate': value['permitObtainDate'] == null ? undefined : ((value['permitObtainDate']).toISOString().substring(0,10)),
        'completionReportStatisticsDate': value['completionReportStatisticsDate'] == null ? undefined : ((value['completionReportStatisticsDate']).toISOString().substring(0,10)),
        'certificateData': value['certificateData'],
        'startConfirmDate': value['startConfirmDate'] == null ? undefined : ((value['startConfirmDate']).toISOString().substring(0,10)),
        'endConfirmDate': value['endConfirmDate'] == null ? undefined : ((value['endConfirmDate']).toISOString().substring(0,10)),
        'isNewIntroducedEnterprise': value['isNewIntroducedEnterprise'],
        'projectRating': value['projectRating'],
        'mainInvestorName': value['mainInvestorName'],
        'plannedTotalInvestment': value['plannedTotalInvestment'],
        'projectLocation': value['projectLocation'],
        'isRecruitmentFairProject': value['isRecruitmentFairProject'],
        'recruitmentFairName': value['recruitmentFairName'],
        'signingTime': value['signingTime'] == null ? undefined : ((value['signingTime']).toISOString().substring(0,10)),
        'signingContract': value['signingContract'],
        'totalInvestmentUsd': value['totalInvestmentUsd'],
        'totalInvestmentCny': value['totalInvestmentCny'],
        'projectSource': value['projectSource'],
        'factoryType': value['factoryType'],
        'plannedLandArea': value['plannedLandArea'],
        'plannedRentalFactoryArea': value['plannedRentalFactoryArea'],
        'plannedPurchaseFactoryArea': value['plannedPurchaseFactoryArea'],
        'expectedAnnualSales': value['expectedAnnualSales'],
        'expectedAnnualSalesAmount': value['expectedAnnualSalesAmount'],
        'expectedAnnualTax': value['expectedAnnualTax'],
        'projectType': value['projectType'],
        'industryMajorClassName': value['industryMajorClassName'],
        'belongingIndustry': value['belongingIndustry'],
        'investorNature': value['investorNature'],
        'projectProfile': value['projectProfile'],
        'isWorldTop500OrLeadingGlobalCompany': value['isWorldTop500OrLeadingGlobalCompany'],
        'isDomesticTop500OrTop100Company': value['isDomesticTop500OrTop100Company'],
        'isPubliclyTradedOrPreIPOCompany': value['isPubliclyTradedOrPreIPOCompany'],
        'isUnicornStartup': value['isUnicornStartup'],
        'averageTaxPerMuOfExistingInvestment': value['averageTaxPerMuOfExistingInvestment'],
        'majorCustomers': value['majorCustomers'],
        'fixedAssetInvestment': value['fixedAssetInvestment'],
        'equipmentInvestment': value['equipmentInvestment'],
        'plannedStartTime': value['plannedStartTime'] == null ? undefined : ((value['plannedStartTime']).toISOString().substring(0,10)),
        'plannedEndTime': value['plannedEndTime'] == null ? undefined : ((value['plannedEndTime']).toISOString().substring(0,10)),
        'mainRawMaterialsUsed': value['mainRawMaterialsUsed'],
        'mainProcessTechnology': value['mainProcessTechnology'],
        'isNewSupplyLandProject': value['isNewSupplyLandProject'],
        'appliedLandArea': value['appliedLandArea'],
        'isHighTechIndustry': value['isHighTechIndustry'],
        'isHighTechProject': value['isHighTechProject'],
        'isNationalStrategicEmergingIndustry': value['isNationalStrategicEmergingIndustry'],
        'plotRatioPercent': value['plotRatioPercent'],
        'expectedInvoiceSales': value['expectedInvoiceSales'],
        'expectedTax': value['expectedTax'],
        'expectedEmployeeCount': value['expectedEmployeeCount'],
        'fixedAssetInvestmentPercentage': value['fixedAssetInvestmentPercentage'],
        'investmentIntensity': value['investmentIntensity'],
        'expectedAverageTax': value['expectedAverageTax'],
        'wastewaterBy1': value['wastewaterBy1'],
        'wastewaterBy2': value['wastewaterBy2'],
        'totalEnergyConsumption': value['totalEnergyConsumption'],
        'hasRndTeamAndCooperation': value['hasRndTeamAndCooperation'],
        'hasValidPatents': value['hasValidPatents'],
        'isListedAsKeyActivitySigningProject': value['isListedAsKeyActivitySigningProject'],
        'remarks': value['remarks'],
        'agreementForeignDirectInvestment': value['agreementForeignDirectInvestment'],
        'investOnlineId': value['investOnlineId'],
        'onlineApprovalIds': value['onlineApprovalIds'],
        'constructionApprovalIds': value['constructionApprovalIds'],
        'isQualityEvaluation': value['isQualityEvaluation'],
        'isProjectReview': value['isProjectReview'],
        'isQualityEvaluationComplete': value['isQualityEvaluationComplete'],
        'isProjectReviewComplete': value['isProjectReviewComplete'],
        'isProjectCompletionApproval': value['isProjectCompletionApproval'],
        'isProjectStartApproval': value['isProjectStartApproval'],
        'auditStatus': value['auditStatus'],
        'light': value['light'],
        'investmentFlagLabel': value['investmentFlagLabel'],
        'currentProjectProgressLabel': value['currentProjectProgressLabel'],
        'isFixedAssetInvestmentLabel': value['isFixedAssetInvestmentLabel'],
        'isConstructionLandLabel': value['isConstructionLandLabel'],
        'isNewIntroducedEnterpriseLabel': value['isNewIntroducedEnterpriseLabel'],
        'isRecruitmentFairProjectLabel': value['isRecruitmentFairProjectLabel'],
        'isWorldTop500OrLeadingGlobalCompanyLabel': value['isWorldTop500OrLeadingGlobalCompanyLabel'],
        'isDomesticTop500OrTop100CompanyLabel': value['isDomesticTop500OrTop100CompanyLabel'],
        'isPubliclyTradedOrPreIPOCompanyLabel': value['isPubliclyTradedOrPreIPOCompanyLabel'],
        'isUnicornStartupLabel': value['isUnicornStartupLabel'],
        'isHighTechIndustryLabel': value['isHighTechIndustryLabel'],
        'isHighTechProjectLabel': value['isHighTechProjectLabel'],
        'isNationalStrategicEmergingIndustryLabel': value['isNationalStrategicEmergingIndustryLabel'],
        'wastewaterBy1Label': value['wastewaterBy1Label'],
        'wastewaterBy2Label': value['wastewaterBy2Label'],
        'hasRndTeamAndCooperationLabel': value['hasRndTeamAndCooperationLabel'],
        'hasValidPatentsLabel': value['hasValidPatentsLabel'],
        'isListedAsKeyActivitySigningProjectLabel': value['isListedAsKeyActivitySigningProjectLabel'],
        'isQualityEvaluationLabel': value['isQualityEvaluationLabel'],
        'isProjectReviewLabel': value['isProjectReviewLabel'],
    };
}


