/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDataGrantsDto
 */
export interface UserDataGrantsDto {
    /**
     * 用户ID
     * @type {Array<string>}
     * @memberof UserDataGrantsDto
     */
    useridList: Array<string>;
    /**
     * 区域ID
     * @type {Array<string>}
     * @memberof UserDataGrantsDto
     */
    areaIdList: Array<string>;
}

export function UserDataGrantsDtoFromJSON(json: any): UserDataGrantsDto {
    return UserDataGrantsDtoFromJSONTyped(json, false);
}

export function UserDataGrantsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDataGrantsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'useridList': json['useridList'],
        'areaIdList': json['areaIdList'],
    };
}

export function UserDataGrantsDtoToJSON(value?: UserDataGrantsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'useridList': value.useridList,
        'areaIdList': value.areaIdList,
    };
}


