server:
  prefer-ip-prefix: '127.0.0.'
  pc-host: http://localhost:8000
  h5-host: http://localhost:5173

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: test
  data:
    redis:
      host: localhost
      password: enterprise-lifecycle
      database: 1

springdoc:
  api-docs:
    enabled: true

mybatis-flex:
  datasource:
    gong-gai:
      url: jdbc:mysql://localhost:3306/gonggai
      username: enterprise_lifecycle
      password: enterprise_lifecycle
      #read-only: true
    invest-online:
      url: jdbc:mysql://localhost:3306/invest_online
      username: enterprise_lifecycle
      password: enterprise_lifecycle
      # url: jdbc:mysql://localhost:3306/invest_online
      # username: zs_test
      # password: Dj3wGnmur5SV
      read-only: true

s3:
  provider: obs
  endpoint: http://localhost:9000
  bucket: qyqsmzq
  access-key: 'WEROGAUDXFYPQDCKLG8I'
  secret-key: 'mBoSSdid8hRsL3iOlfPwK8gV5zRmRR0vAKIEEKCP'
