import DictManage from '@/pages/DictManage';
import HomePage from '@/pages/HomePage';
import menu from '@/locales/bn-BD/menu';

export default [
  { name: '登录', path: '/login', component: './User/Login', layout: false },
  { name: 'sso', path: '/tztLogin', component: './TztRedirect', layout: false },
  { name: '企业全生命周期管理系统', path: '/tutorial', component: './TutorialPage', layout: false },
  { name: '项目管理', path: '/tutorial/project-manage', component: './TutorialPage/ProjectManage', layout: false },
  { name: '项目进度', path: '/tutorial/project-advance', component: './TutorialPage/ProjectManage/ProjectAdvance', layout: false },

  { name: '工改管理', path: '/tutorial/projectGG-manage', component: './TutorialPage/ProjectManageGG', layout: false },
  { name: '项目进度', path: '/tutorial/projectGG-advance', component: './TutorialPage/ProjectManageGG/ProjectDetail', layout: false },

  { name: '开工竣工', path: '/tutorial/kaigong-jungong', component: './TutorialPage/KaiGongJunGong', layout: false },
  { name: '项目开工', path: '/tutorial/tou-chan-da-xiao/start-work-detail', component: './TutorialPage/KaiGongJunGong/StartWorkDetail', layout: false },
  { name: '项目在建', path: '/tutorial/tou-chan-da-xiao/do-work-detail', component: './TutorialPage/KaiGongJunGong/DoWorkDetail', layout: false },
  { name: '项目竣工', path: '/tutorial/tou-chan-da-xiao/end-work-detail', component: './TutorialPage/KaiGongJunGong/EndWorkDetail', layout: false },

  { name: '前期招商', path: '/tutorial/preinvestment', component: './TutorialPage/PreInvestment', layout: false },
  { name: '备案审批', path: '/tutorial/record-approval', component: './TutorialPage/RecordApproval', layout: false },
  { name: '投产达效', path: '/tutorial/tou-chan-da-xiao', component: './TutorialPage/TouChanDaXiao', layout: false },
  {
    name: '四重项目招引',
    path: '/tutorial/preinvestment/fourfold',
    component: './TutorialPage/PreInvestment/Fourfold',
    layout: false
  },
  {
    name: '外资利用',
    path: '/tutorial/preinvestment/foreign-investment',
    component: './TutorialPage/PreInvestment/ForeignInvestment',
    layout: false
  },
  { name: '亿元以上项目', path: '/tutorial/preinvestment/over-million-projects', component: './TutorialPage/PreInvestment/OverMillionProjects', layout: false },
  { name: '项目进度情况', path: '/tutorial/preinvestment/project-progress', component: './TutorialPage/PreInvestment/ProjectProgress', layout: false },
  { name: '未开工项目进度', path: '/tutorial/preinvestment/project-not-start', component: './TutorialPage/PreInvestment/ProjectProgress/BuKaiGong', layout: false },
  { name: '完成投资详情', path: '/tutorial/tou-chan-da-xiao/investment-detail', component: './TutorialPage/TouChanDaXiao/InvestmentDetail', layout: false },
  { name: '进归纳统详情', path: '/tutorial/tou-chan-da-xiao/compliance-detail', component: './TutorialPage/TouChanDaXiao/ComplianceDetail', layout: false },
  { name: '进归纳统详情1', path: '/tutorial/tou-chan-da-xiao/compliance-detail-advance', component: './TutorialPage/TouChanDaXiao/ComplianceDetailAdvance', layout: false },
  { name: '产出效益详情', path: '/tutorial/tou-chan-da-xiao/economic-detail', component: './TutorialPage/TouChanDaXiao/EconomicDetail', layout: false },
  { name: '产出效益详情', path: '/tutorial/tou-chan-da-xiao/economic-detail-advance', component: './TutorialPage/TouChanDaXiao/EconomicDetailAdvance', layout: false },
  { name: '链群体系详情', path: '/tutorial/tou-chan-da-xiao/chain-cluster-detail', component: './TutorialPage/TouChanDaXiao/ChainClusterDetail', layout: false },

  { name: '科创项目', path: '/tutorial/ke-chuang-xiang-mu', component: './TutorialPage/KeChuangXiangMu/ScienceProject', layout: false },
  { name: '科创项目表', path: '/tutorial/ke-chuang-xiang-mu/project-manage', component: './TutorialPage/KeChuangXiangMu/ProjectManage', layout: false },
  { name: '投资进度', path: '/tutorial/tou-zi-jin-du', component: './TutorialPage/TouZiJinDu', layout: false },
  { name: '在建项目', path: '/tutorial/tou-zi-jin-du/progress-detail', component: './TutorialPage/TouZiJinDu/ProgressDetail', layout: false },
  { name: '入库投资', path: '/tutorial/tou-zi-jin-du/progress-detail1', component: './TutorialPage/TouZiJinDu/ProgressDetail1', layout: false },
  { name: '投资完成率', path: '/tutorial/tou-zi-jin-du/progress-detail2', component: './TutorialPage/TouZiJinDu/ProgressDetail2', layout: false },
  { name: '投资完成率', path: '/tutorial/tou-zi-jin-du/progress-detail3', component: './TutorialPage/TouZiJinDu/ProgressDetail3', layout: false },
  { name: '投资项目列表详情', path: '/tutorial/tou-zi-jin-du/progress-detail-adavance', component: './TutorialPage/TouZiJinDu/ProgressDetailAdavance', layout: false },
  {
    path: '/enterprise/tags',
    name: '欢迎',
    icon: 'smile',
    component: './TagManage',
    access: 'normalRouteFilter',
  },
  {
    path: '/enterprise/newtag',
    name: '欢迎',
    icon: 'smile',
    component: './NewTag',
    access: 'normalRouteFilter',
  },
  {
    path: '/enterprise/enterpriseSearch',
    name: '欢迎',
    icon: 'smile',
    component: './EnterpriseSearch',
    access: 'normalRouteFilter',
  },
  { path: '/', name: '欢迎', icon: 'smile', component: './WelcomePage' , layout: false },
  { path: '/welcome/fourWarZone', name: '四大战区', component: './WelcomePage/fourWarZone', layout: false },
  { path: '/welcome/four', name: '四库五率', component: './WelcomePage/four', layout: false },
  { path: '/home', name: '欢迎', icon: 'smile', component: './HomePage'},
  {
    name: '用户管理',
    icon: 'table',
    path: '/user/user',
    component: './UserManage',
    access: 'normalRouteFilter',
  },
  {
    name: '角色管理',
    icon: 'table',
    path: '/user/role',
    component: './RoleManage',
    access: 'normalRouteFilter',
  },
  {
    name: '组织管理',
    icon: 'table',
    path: '/user/organization',
    component: './Organization',
    access: 'normalRouteFilter',
  },
  {
    name: '行政区划',
    icon: 'table',
    path: '/system/administrative-division',
    component: './AreaManage',
    access: 'normalRouteFilter',
  },
  {
    name: '字典管理',
    icon: 'table',
    path: '/system/dict',
    component: './DictManage',
    access: 'normalRouteFilter',
  },
  {
    name: '菜单管理',
    icon: 'table',
    path: '/system/menu',
    component: './MenuManage',
    access: 'normalRouteFilter',
  },
  {
    name: '系统日志',
    icon: 'table',
    path: '/system/log',
    component: './SystemLog',
    access: 'normalRouteFilter',
  },
  {
    name: '系统配置',
    icon: 'table',
    path: '/system/settings',
    component: './SystemSetting',
    access: 'normalRouteFilter',
  },
  {
    name: '流程引擎',
    icon: 'apartment',
    path: '/system/workflow',
    component: './WorkflowManage',
    access: 'normalRouteFilter',
  },
  {
    name: '项目管理',
    icon: 'table',
    path: '/xmgl',
    component: './ProjectManage',
    access: 'normalRouteFilter',
    badge: 5
  },
  {
    name: '项目共享',
    icon: 'share-alt',
    path: '/project-share',
    component: './ProjectShare',
  },
  {
    name: '任务管理',
    icon: 'file-text',
    path: '/task-manage',
    component: './TaskManage',
  },
  {
    name: '项目加分',
    icon: 'plus-circle',
    path: '/project-score',
    component: './ProjectScore',
  },
  {
    name: '组合报表',
    icon: 'file-search',
    path: '/combined-report',
    component: './CombinedReport',
  },
  {
    name: '统计报表（市区）',
    icon: 'bar-chart',
    path: '/statistical-report-district',
    component: './StatisticalReportDistrict',
  },
  {
    name: '新签约总投资项目情况表',
    path: '/statistical-report-district/report1',
    component: './StatisticalReportDistrict/Report1',
    hideInMenu: true,
  },
  {
    name: '新签约项目分产业汇总表',
    path: '/statistical-report-district/report2',
    component: './StatisticalReportDistrict/Report2',
    hideInMenu: true,
  },
  {
    name: '新签约项目进度情况表',
    path: '/statistical-report-district/report3',
    component: './StatisticalReportDistrict/Report3',
    hideInMenu: true,
  },
  {
    name: '招商活动开展登记',
    icon: 'table',
    path: '/investment-activity-register',
    component: './InvestmentActivityRegister',
  },
  {
    name: '招商活动开展审核',
    icon: 'table',
    path: '/investment-activity-audit',
    component: './InvestmentActivityAudit',
  },
  {
    name: '招商团队名录',
    icon: 'team',
    path: '/investment-team-directory',
    component: './InvestmentTeamDirectory',
  },
  {
    name: '因公出访招商登记',
    icon: 'table',
    path: '/official-visit-register',
    component: './OfficialVisitRegister',
  },
  {
    name: '项目审核',
    icon: 'table',
    path: '/project-audit',
    component: './ProjectAudit',
  },
  {
    name: '汇率管理',
    icon: 'table',
    path: '/exchange-rate-manage',
    component: './ExchangeRateManage',
  },
  {
    name: '在谈项目',
    icon: 'table',
    path: '/xmgl9',
    component: './ProjectManage9',
  },
  {
    name: '签约项目',
    icon: 'table',
    path: '/xmgl10',
    component: './ProjectManage10',
  },
  {
    name: '质态评估',
    icon: 'table',
    path: '/xmgl2',
    component: './ProjectManage2',
    access: 'normalRouteFilter',
  },
  {
    name: '签约项目',
    icon: 'table',
    path: '/xmgl3',
    component: './ProjectManage3',
    access: 'normalRouteFilter',
  },
  {
    name: '留言管理',
    icon: 'table',
    path: '/message',
    component: './Message',
  },
  {
    name: '投资意向',
    icon: 'table',
    path: '/intention',
    component: './Intention',
  },
  {
    name: '控制台',
    icon: 'table',
    path: '/kzt',
    component: './Control',
  },
  {
    name: '我的项目',
    icon: 'table',
    path: '/xmgl4',
    component: './ProjectManage4',
    access: 'normalRouteFilter',
  },
  {
    name: '项目推荐',
    icon: 'table',
    path: '/project-recomand',
    component: './ProjectRecomand',
    access: 'normalRouteFilter',
  },
  {
    name: '招商活动列表',
    path: '/project-recomand/recolist',
    component: './ProjectRecomand/recolist',
    access: 'normalRouteFilter',
    hideInMenu: true,
  },
  {
    name: '招商活动详情',
    path: '/project-recomand/detail/:id',
    component: './ProjectRecomand/detail',
    access: 'normalRouteFilter',
    hideInMenu: true,
  },
  {
    name: '项目看板',
    icon: 'table',
    path: '/xmgl8',
    component: './ProjectManage8',
    access: 'normalRouteFilter',
  },
  {
    name: '工改项目',
    icon: 'table',
    path: '/xmgl-gg',
    component: './ProjectManageGG',
    access: 'normalRouteFilter',
  },
  {
    name: '项目审批详情',
    path: '/tutorial/record-approval/detail/approve-datail',
    component: './TutorialPage/RecordApproval/Detail/ApproveDetail',
    layout: false,
  },{
    name: '项目审批详情1',
    path: '/tutorial/record-approval/detail/approve-detail-advance',
    component: './TutorialPage/RecordApproval/Detail/ApproveDetailAdvance',
    layout: false,
  },{
    name: '项目审批详情2',
    path: '/tutorial/record-approval/detail/approve-detail-advance2',
    component: './TutorialPage/RecordApproval/Detail/ApproveDetailAdvance2',
    layout: false,
  },
  {
    name: '用地保障',
    path: '/tutorial/record-approval/detail/land-datail',
    component: './TutorialPage/RecordApproval/Detail/LandDetail',
    layout: false,
  },{
    name: '审批服务',
    path: '/tutorial/record-approval/detail/audit-datail',
    component: './TutorialPage/RecordApproval/Detail/AuditDetail',
    layout: false,
  },{
    name: '链群体系',
    path: '/tutorial/record-approval/detail/chain-datail',
    component: './TutorialPage/RecordApproval/Detail/ChainDetail',
    layout: false,
  },
  {
    name: '项目备案详情',
    path: '/tutorial/record-approval/detail/remark-datail',
    component: './TutorialPage/RecordApproval/Detail/RemarkDetail',
    layout: false,
  },
  {
    name: '项目备案详情1',
    path: '/tutorial/record-approval/detail/remark-datail-advance',
    component: './TutorialPage/RecordApproval/Detail/RemarkDetailAdvance',
    layout: false,
  },
  {
    name: '工改项目详情',
    icon: 'table',
    path: '/xmgl-gg/detail',
    component: './ProjectManageGG/ProjectDetail',
  },
  {
    name: '开工认定',
    icon: 'table',
    path: '/xmgl5',
    component: './ProjectManage5',
    access: 'normalRouteFilter',
  },
  {
    name: '非招商项目开工认定',
    icon: 'table',
    path: '/xmgl7',
    component: './ProjectManage7',
    access: 'normalRouteFilter',
  },
  {
    name: '竣工认定',
    icon: 'table',
    path: '/xmgl6',
    component: './ProjectManage6',
    access: 'normalRouteFilter',
  },
  {
    name: '数据导入',
    icon: 'table',
    path: '/dataAcquisition/dataImport',
    component: './DataImport',
    access: 'normalRouteFilter',
  },
  {
    name: '全链条',
    icon: 'table',
    path: '/dataAcquisition/fullChain',
    component: './FullChain',
    access: 'normalRouteFilter',
  },
  {
    name: '项目详情',
    icon: 'table',
    path: '/xmgl/xmjd',
    component: './ProjectManage/ProjectAdvance',
  },
  {
    name: '项目质效',
    icon: 'table',
    path: '/xmgl/qa-effect',
    component: './ProjectManage/QaEffect',
  },
  {
    name: '项目质态',
    icon: 'table',
    path: '/xmgl/qa-state',
    component: './ProjectManage/QaState',
  },
  {
    name: '签约项目',
    icon: 'table',
    path: '/xmgl/pro-sign',
    component: './ProjectManage3/ProSign',
  },
  {
    name: '签约项目2',
    icon: 'table',
    path: '/xmgl4/pro-sign',
    component: './ProjectManage4/ProSign',
  },
  {
    name: '开工认定',
    icon: 'table',
    path: '/xmgl/pro-start',
    component: './ProjectManage5/ProStart',
  },{
    name: '开工认定2',
    icon: 'table',
    path: '/xmgl4/pro-start',
    component: './ProjectManage4/ProStart',
  },
  {
    name: '非招商项目开工认定',
    icon: 'table',
    path: '/xmgl/pro-other-start',
    component: './ProjectManage7/ProOtherStart',
  },
  {
    name: '竣工认定',
    icon: 'table',
    path: '/xmgl/pro-end',
    component: './ProjectManage6/ProEnd',
  },
  {
    name: '支撑指标',
    icon: 'table',
    path: '/gdp/support',
    component: './SupportKpi',
  },
  {
    name: '监测指标',
    icon: 'table',
    path: '/gdp/monitor',
    component: './MonitorKpi',
  },
  {
    name: '分市区基础数据',
    icon: 'table',
    path: '/gdp/basic-data',
    component: './BasicData',
  },
  {
    name: '分市区基础数据',
    icon: 'table',
    path: '/gdp/basic-data-detail',
    component: './BasicData/BasicDataDetail',
  },
  {
    name: '数据导入',
    icon: 'table',
    path: '/dept-report/:deptId',
    component: './DepartReport',
  },
  {
    name: '数据导入',
    icon: 'table',
    path: '/depart-report',
    component: './DepartReport',
  },
  {
    name: '材料报送任务',
    icon: 'table',
    path: '/file-report',
    component: './FileReport',
  }
  ,{
    name: '三个大抓',
    icon: 'table',
    path: '/three-catch',
    component: './ThreeCatch',
  },{
    name: '部门积分总览',
    icon: 'table',
    path: '/total-point',
    component: './TotalPoint',
  },{
    name: '部门积分总览',
    icon: 'table',
    path: '/project-apeal',
    component: './ProjectApeal',
  },{
    name: '项目申报详情',
    icon: 'table',
    path: '/project-apeal-advance',
    component: './ProjectApeal/ApealAdvance',
  },
  {
    name: '项目申诉',
    icon: 'table',
    path: '/point-scoring',
    component: './PointScoring',
  },
  {
    name: '问题反馈',
    icon: 'table',
    path: '/qa-manage',
    component: './QaManage',
  },
  {
    path: '/qa-manage/detail',
    component: './QaManage/ApealAdvance',
    hideInMenu: true,
  },
  {
    name: '系统日志',
    icon: 'table',
    path: '/system-log',
    component: './SystemLog',
  },
  {
    name: '跟踪服务',
    icon: 'table',
    path: '/service-track',
    component: './ServiceTrack',
    access: 'normalRouteFilter',
  },
  {
    name: '服务记录',
    icon: 'table',
    path: '/service-record',
    component: './ServiceRecord',
    layout: false
  },
  {
    name: '重点项目',
    icon: 'table',
    path: '/key-project',
    component: './KeyProject',
    access: 'normalRouteFilter',
  },
  {
    name: '重点项目详情',
    path: '/key-project/detail',
    component: './KeyProject/Detail',
  },
  {
    name: '重点项目评估',
    icon: 'table',
    path: '/key-project-review',
    component: './KeyProjectReview',
    access: 'normalRouteFilter',
  },
  {
    name: '统计报表（市级）',
    icon: 'table',
    path: '/statistical-report',
    component: './StatisticalReport',
  },
  {
    name: '各市（区）新签约总投资项目情况表',
    path: '/statistical-report/detail1',
    component: './StatisticalReport/Report1',
  },
  {
    name: '项目招引信息',
    path: '/statistical-report/detail2',
    component: './StatisticalReport/Report2',
  },
  {
    name: '全市新签约项目分产业汇总表',
    path: '/statistical-report/detail3',
    component: './StatisticalReport/Report3',
  },
  {
    name: '全市新签约项目进度情况表',
    path: '/statistical-report/detail4',
    component: './StatisticalReport/Report4',
  },
  {
    name: '"三比一提升"市（区）项目签约得分表',
    path: '/statistical-report/detail5',
    component: './StatisticalReport/Report5',
  },
  {
    name: '"三比一提升"重点园区项目签约得分表',
    path: '/statistical-report/detail6',
    component: './StatisticalReport/Report6',
  },
  {
    name: '市领导联系服务"四重"工作产业链项目招引情况表',
    path: '/statistical-report/detail7',
    component: './StatisticalReport/Report7',
  },
  {
    name: '产业链项目明细表',
    path: '/statistical-report/detail8',
    component: './StatisticalReport/Report8',
  },
  {
    name: '生产内表',
    icon: 'table',
    path: '/report-center/project-attraction',
    component: './ReportCenter/ProjectAttraction',
    access: 'normalRouteFilter',
  },
  {
    path: '/report-center/project-digital-list',
    component: './ReportCenter/ProjectManage',
    hideInMenu: true,
    /** 报表穿透新标签打开，不依赖菜单项；登录即可访问 */
    access: 'canAccess',
    layout: false,
  },
  {
    path: '*',
    component: './404',
  },
];
