@file:Suppress("unused")

package com.tzdig.framework.model.dto

import com.tzdig.framework.mybatis.entity.prime.ExtZsProjProjectSigned
import io.swagger.v3.oas.annotations.media.Schema
import java.time.LocalDate

data class ExtZsProjProjectSignedDTO(
    @param:Schema(description = "_id")
    val id: String?,
    @param:Schema(description = "项目名称")
    val name: String?,
    @param:Schema(description = "项目编号")
    val code: String?,
    @param:Schema(description = "区县编码")
    val districtCode: String?,
    @param:Schema(description = "区县")
    val district: String?,
    @param:Schema(description = "园区code")
    val zoneCode: String?,
    @param:Schema(description = "园区名称")
    val zoneName: String?,
    @param:Schema(description = "街镇")
    val townCode: String?,
    @param:Schema(description = "街镇名")
    val townName: String?,
    @param:Schema(description = "项目类别, 1-内资,2-外资 默认1")
    val pType: Short?,
    @param:Schema(description = "总投资额,  内资时单位是亿元,外资时单位是万美元")
    val investMoney: Double?,
    @param:Schema(description = "协议利用外资(万美元)")
    val foreignMoney: Double?,
    @param:Schema(description = "项目类型, t_proj_type")
    val projType: String?,
    @param:Schema(description = "产业大类(不要显示的) t_proj_industry_first")
    val industryFirstCode: String?,
    @param:Schema(description = "产业大类名称t_proj_industry_first")
    val industryFirstName: String?,
    @param:Schema(description = "行业编码(不要显示的)t_proj_industry")
    val industryCode: String?,
    @param:Schema(description = "行业编码(显示的)t_proj_industry")
    val industryName: String?,
    @param:Schema(description = "1-服务业 2-制造业")
    val bIndustry: Short?,
    @param:Schema(description = "投资方名称")
    val investor: String?,
    @param:Schema(description = "10-央企,20-民营巨头 30-世界500强或跨国公司 40-其它")
    val investorType: Short?,
    @param:Schema(description = "90-香港 ,100-台湾,110-日本,&#13;&#10;120-韩国,130-美国,140-欧洲,&#13;&#10;150-新加坡,80-外资其他&#13;&#10;10 北京&#13;&#10;20 上海&#13;&#10;30 广州&#13;&#10;40 深圳&#13;&#10;50 苏州&#13;&#10;60 长三角其他城市&#13;&#10;70 内资其他&#13;&#10;")
    val investorPlace: String?,
    @param:Schema(description = "签约日期")
    val signedDate: LocalDate?,
    @param:Schema(description = "签约信息统计日期")
    val signedStatDate: LocalDate?,
    @param:Schema(description = "项目简介, 大文本框")
    val Desc: String?,
    @param:Schema(description = "备案（核准）项目名称")
    val checkName: String?,
    @param:Schema(description = "备案（核准）投资总额（亿元）")
    val checkMoney: Double?,
    @param:Schema(description = "备案（核准）日期")
    val checkDate: LocalDate?,
    @param:Schema(description = "备案（核准）统计日期")
    val checkStatDate: LocalDate?,
    @param:Schema(description = "统一社会信用代码证")
    val uCode: String?,
    @param:Schema(description = "注册公司名称")
    val companyName: String?,
    @param:Schema(description = "注册资金")
    val regMoney: Double?,
    @param:Schema(description = "注册日期")
    val regDate: LocalDate?,
    @param:Schema(description = "reg_foreign_money")
    val regForeignMoney: Double?,
    @param:Schema(description = "注册信息统计日期：")
    val regStatDate: LocalDate?,
    @param:Schema(description = "是否涉及固定资产投资项目1-是,2-否")
    val isFixedAsset: Short?,
    @param:Schema(description = "是否涉及建设用地")
    val isUseLand: Short?,
    @param:Schema(description = "建设用地规划许可证编号")
    val landLicence: String?,
    @param:Schema(description = "完成报批日期")
    val finishCheckDate: LocalDate?,
    @param:Schema(description = "取得许可证日期")
    val licenceDate: LocalDate?,
    @param:Schema(description = "到账金额")
    val receivedMoney: Double?,
    @param:Schema(description = "0已签约   1已注册   5已备案   4完成报批   2已开工   3已竣工  ")
    val progress: Short?,
    @param:Schema(description = "0-待审核  1-市级审核通过 2-市区审核通过,3-审核不通过  4-保存未提交")
    val checkStatus: Short?,
    @param:Schema(description = "开工日期")
    val startDateCommit: LocalDate?,
    @param:Schema(description = "竣工日期")
    val completeDate: LocalDate?,
    @param:Schema(description = "投资方联系人")
    val linker: String?,
    @param:Schema(description = "投资方联系电话")
    val linkerTel: String?,
    @param:Schema(description = "招商人员")
    val linkerTz: String?,
    @param:Schema(description = "招商人员电话")
    val linkerTzTel: String?,
    @param:Schema(description = "创建人的id,前端界面不管理,插入时用登录人帐号赋值")
    val creatorId: Int?,
    @param:Schema(description = "创建人姓名")
    val creatorName: String?,
    @param:Schema(description = "创建人的部门编码")
    val creatorDept: String?,
    @param:Schema(description = "最后一次审核结果描述")
    val lastCheckDesc: String?,
    @param:Schema(description = "实际投入资金规模（亿元）")
    val actualInvest: Double?,
    @param:Schema(description = "开工认定编码")
    val startCode: String?,
    @param:Schema(description = "实际建成产能")
    val actualOutput: Double?,
    @param:Schema(description = "累计实际投入资金规模（亿元")
    val sumActualInvest: Double?,
    @param:Schema(description = "修改人")
    val updateId: String?,
    @param:Schema(description = "老项目创建人id")
    val oldCreateBy: String?,
    @param:Schema(description = "老项目修改人id&#13;&#10;")
    val oldUpdateBy: String?,
    @param:Schema(description = "老项目的主键ID")
    val oldId: String?,
    @param:Schema(description = "是否为六大产业项目")
    val isSixpro: Short?,
    @param:Schema(description = "六大产业项目编码")
    val sixproCode: String?,
    @param:Schema(description = "备注")
    val remarks: String?,
    @param:Schema(description = "1-正常，2-删除")
    val Status: Short?,
    @param:Schema(description = "排序")
    val orderIdx: Int?,
    @param:Schema(description = "签约金额（外资已根据汇率转换）")
    val qyje: Double?,
    @param:Schema(description = "开工确认 1：是 0：否")
    val kgqr: String?,
    @param:Schema(description = "竣工确认 1：是 0：否")
    val jgqr: String?,
    @param:Schema(description = "项目评级")
    val projLevel: String?,
    @param:Schema(description = "是否为新引进企业")
    val isNew: Short?,
    @param:Schema(description = "是否为世界500强或全球专业领域行业龙头企业")
    val isWorld: Short?,
    @param:Schema(description = "是否为国内500强或国内行业排名前100企业")
    val isChina: Short?,
    @param:Schema(description = "是否为上市公司或上市辅导期企业")
    val isListed: Short?,
    @param:Schema(description = "是否为独角兽企业")
    val isUnicorn: Short?,
    @param:Schema(description = "已投资项目对属地政府亩均税收（万元）")
    val mujunTax: String?,
    @param:Schema(description = "主要客户")
    val mainCustomer: String?,
    @param:Schema(description = "计划总投资（万元）")
    val planTotal: String?,
    @param:Schema(description = "注册资本（万元）")
    val zhuceMoney: String?,
    @param:Schema(description = "计划开工时间")
    val planStartDate: LocalDate?,
    @param:Schema(description = "计划竣工时间")
    val planEndDate: LocalDate?,
    @param:Schema(description = "项目使用主要原、辅材料")
    val projectMaterial: String?,
    @param:Schema(description = "主要流程工艺")
    val mainProcess: String?,
    @param:Schema(description = "是否为新供地项目")
    val isNewproject: String?,
    @param:Schema(description = "项目选址位置")
    val projectAddress: String?,
    @param:Schema(description = "申请用地面积（亩）")
    val sqLandArea: String?,
    @param:Schema(description = "行业是否属于高新技术产业分类目录")
    val isGx: String?,
    @param:Schema(description = "是否为高技术项目")
    val isGjs: String?,
    @param:Schema(description = "是否为国家工业战略性新兴产业")
    val isGyzl: String?,
    @param:Schema(description = "容积率")
    val far: String?,
    @param:Schema(description = "预期开票销售（万元）")
    val yqKpxs: String?,
    @param:Schema(description = "预期税收（万元）")
    val yqSs: String?,
    @param:Schema(description = "预期用工人数（人）")
    val yqWorker: String?,
    @param:Schema(description = "固定资产投资占比（%）")
    val fixedPercent: String?,
    @param:Schema(description = "投资强度（万元/千平方米）")
    val investLevel: String?,
    @param:Schema(description = "预期亩均税收（万元/千平方米）")
    val yqMjtax: String?,
    @param:Schema(description = "是否有产生废水和挥发性有机废水排放")
    val isWaterpf: String?,
    @param:Schema(description = "产生废水是否含氮、磷或使用高挥发性有机化合物含量涂料、油墨、胶粘剂")
    val isWuran: String?,
    @param:Schema(description = "总能耗")
    val totalUse: String?,
    @param:Schema(description = "项目是否含有研发团队、产学研合作及研发机构建设内容")
    val isYanfa: String?,
    @param:Schema(description = "项目是否拥有相关有效发明专利")
    val isZhuanli: String?,
    @param:Schema(description = "是否拟列入重点活动签约项目库")
    val isImportant: String?,
    @param:Schema(description = "是否为招商会项目")
    val isZsh: String?,
    @param:Schema(description = "招商会名称")
    val zshName: String?,
    @param:Schema(description = "预计年销售（万元）")
    val yjYear: String?,
    @param:Schema(description = "备注")
    val remark: String?,
    @param:Schema(description = "是否为瞪羚企业")
    val isGazelle: Short?,
    @param:Schema(description = "是否为专精特新企业")
    val isSpecialized: Short?,
    @param:Schema(description = "设备投资（万元）")
    val deviceInvest: String?,
    @param:Schema(description = "固定资产投资（万元）")
    val fixedInvest: String?,
    @param:Schema(description = "1 自行接洽 2 市级机关推荐")
    val bResource: Int?,
    @param:Schema(description = "市集机关名称")
    val sjjgName: String?,
    @param:Schema(description = "企业联系人")
    val qyLinker: String?,
    @param:Schema(description = "联系电话")
    val qyPhone: String?,
    @param:Schema(description = "申请用地年")
    val sqLandYear: String?,
    @param:Schema(description = "预期产值")
    val yqCz: String?,
    @param:Schema(description = "自评价等级 优良一般")
    val zpjLevel: String?,
    @param:Schema(description = "重点项目类型")
    val importProjType: String?,
    @param:Schema(description = "计划总投资第一期")
    val planTotal1: String?,
    @param:Schema(description = "计划总投资第二期")
    val planTotal2: String?,
    @param:Schema(description = "是否重点项目")
    val isImportProj: String?,
    @param:Schema(description = "风险投资方名称")
    val fxName: String?,
    @param:Schema(description = "预期开票销售（第一年）")
    val yqKpxs1: String?,
    @param:Schema(description = "预期开票销售（第二年）")
    val yqKpxs2: String?,
    @param:Schema(description = "预期开票销售（第三年）")
    val yqKpxs3: String?,
    @param:Schema(description = "预期税收（第一年）")
    val yqSs1: String?,
    @param:Schema(description = "预期税收（第二年）")
    val yqSs2: String?,
    @param:Schema(description = "预期税收（第三年）")
    val yqSs3: String?,
    @param:Schema(description = "预期亩均税收（第一年）")
    val yqMjtax1: String?,
    @param:Schema(description = "预期亩均税收（第二年）")
    val yqMjtax2: String?,
    @param:Schema(description = "预期亩均税收（第三年）")
    val yqMjtax3: String?,
    @param:Schema(description = "投资方实力评估")
    val tzfLevel: String?,
    @param:Schema(description = "投资方风险评估")
    val tzfFx: String?,
    @param:Schema(description = "产业关联度")
    val cyGl: String?,
    @param:Schema(description = "产品市场和工艺水平")
    val cpGy: String?,
    @param:Schema(description = "团队力量")
    val team: String?,
    @param:Schema(description = "专利数")
    val zlNum: String?,
    @param:Schema(description = "参赛获奖情况")
    val hjContent: String?,
    @param:Schema(description = "认定进度")
    val rProgress: String?,
    @param:Schema(description = "是否风险投资")
    val isWarningInvest: String?,
    @param:Schema(description = "是否项目支持")
    val ifSjProj: String?,
    @param:Schema(description = "预期产值（第一年）")
    val yqCz1: String?,
    @param:Schema(description = "预期产值（第二年）")
    val yqCz2: String?,
    @param:Schema(description = "预期产值（第三年）")
    val yqCz3: String?,
    @param:Schema(description = "产品市场前景")
    val cpQj: String?,
    @param:Schema(description = "工艺水平（工作效率）")
    val gyXl: String?,
    @param:Schema(description = "工艺水平（良品率）")
    val gyLp: String?,
    @param:Schema(description = "工艺水平（整体评价）")
    val gyPj: String?,
    @param:Schema(description = "资产负债表")
    val zcfz: String?,
    @param:Schema(description = "利润表")
    val lirun: String?,
    @param:Schema(description = "现金流量表")
    val xjll: String?,
    @param:Schema(description = "固定资产与流动资产占比")
    val zczb: String?,
    @param:Schema(description = "资金来源")
    val zjly: String?,
    @param:Schema(description = "金融机构信用评级")
    val xypj: String?,
    @param:Schema(description = "行业协会评价")
    val xhpj: String?,
    @param:Schema(description = "纳税合规性")
    val hegui: String?,
    @param:Schema(description = "综合评估等级")
    val zhpg: String?,
    @param:Schema(description = "评估状态")
    val pgStatus: String?,
    @param:Schema(description = "是否科创项目")
    val isKcProj: String?,
    @param:Schema(description = "科创项目认定条件")
    val kcProjTj: String?,
    @param:Schema(description = "QFLP外资项目")
    val isQflp: String?,
    @param:Schema(description = "成效情况说明")
    val cgRemark: String?,
    @param:Schema(description = "是否特殊行业")
    val tshy: String?,
    @param:Schema(description = "有无准入限制")
    val zrxz: String?,
    @param:Schema(description = "是否两高项目")
    val lgxm: String?,
    @param:Schema(description = "有无重金属排放")
    val zjspf: String?,
    @param:Schema(description = "产品市场现状")
    val cpscxz: String?,
    @param:Schema(description = "工艺水平")
    val gysp: String?,
    @param:Schema(description = "生产效率")
    val scxl: String?,
    @param:Schema(description = "良品率")
    val lpl: String?,
    @param:Schema(description = "是否高新技术企业")
    val isGxjs: String?,
    @param:Schema(description = "是否建立企业研发中心")
    val ifBuildYfzx: String?,
    @param:Schema(description = "企业研发中心")
    val buildYfzx: String?,
    @param:Schema(description = "省级以上科技或人才等项目")
    val sjProj: String?,
    @param:Schema(description = "厂房租赁面积(平方米)")
    val zlLandArea: String?,
    @param:Schema(description = "折算用地")
    val zlLandAreaZs: String?,
    @param:Schema(description = "质态评估评审结果")
    val ztpgzzcl: String?,
    @param:Schema(description = "批准部门及文号")
    val pzwh: String?,
    @param:Schema(description = "批准日期")
    val pzrq: LocalDate?,
    @param:Schema(description = "成效情况")
    val cxqk: String?,
    @param:Schema(description = "qr_key")
    val qrKey: String?,
    @param:Schema(description = "招商方")
    val zsf: String?,
    @param:Schema(description = "投资方")
    val tzf: String?,
    @param:Schema(description = "投资地址")
    val tzdz: String?,
    @param:Schema(description = "佐证材料")
    val xyzzcl: String?,
    @param:Schema(description = "是否有融资需求")
    val isRzxq: String?,
    @param:Schema(description = "融资金额")
    val rzMoney: String?,
    @param:Schema(description = "科创项目分类")
    val kcProjType: String?,
    @param:Schema(description = "科创佐证材料")
    val kccl: String?,
) {
    fun toExtZsProjProjectSigned(): ExtZsProjProjectSigned =
        ExtZsProjProjectSigned {
            into(this)
        }

    fun into(record: ExtZsProjProjectSigned): ExtZsProjProjectSigned {
        record.id = id
        record.name = name
        record.code = code
        record.districtCode = districtCode
        record.district = district
        record.zoneCode = zoneCode
        record.zoneName = zoneName
        record.townCode = townCode
        record.townName = townName
        record.pType = pType
        record.investMoney = investMoney
        record.foreignMoney = foreignMoney
        record.projType = projType
        record.industryFirstCode = industryFirstCode
        record.industryFirstName = industryFirstName
        record.industryCode = industryCode
        record.industryName = industryName
        record.bIndustry = bIndustry
        record.investor = investor
        record.investorType = investorType
        record.investorPlace = investorPlace
        record.signedDate = signedDate
        record.signedStatDate = signedStatDate
        record.Desc = Desc
        record.checkName = checkName
        record.checkMoney = checkMoney
        record.checkDate = checkDate
        record.checkStatDate = checkStatDate
        record.uCode = uCode
        record.companyName = companyName
        record.regMoney = regMoney
        record.regDate = regDate
        record.regForeignMoney = regForeignMoney
        record.regStatDate = regStatDate
        record.isFixedAsset = isFixedAsset
        record.isUseLand = isUseLand
        record.landLicence = landLicence
        record.finishCheckDate = finishCheckDate
        record.licenceDate = licenceDate
        record.receivedMoney = receivedMoney
        record.progress = progress
        record.checkStatus = checkStatus
        record.startDateCommit = startDateCommit
        record.completeDate = completeDate
        record.linker = linker
        record.linkerTel = linkerTel
        record.linkerTz = linkerTz
        record.linkerTzTel = linkerTzTel
        record.creatorId = creatorId
        record.creatorName = creatorName
        record.creatorDept = creatorDept
        record.lastCheckDesc = lastCheckDesc
        record.actualInvest = actualInvest
        record.startCode = startCode
        record.actualOutput = actualOutput
        record.sumActualInvest = sumActualInvest
        record.updateId = updateId
        record.oldCreateBy = oldCreateBy
        record.oldUpdateBy = oldUpdateBy
        record.oldId = oldId
        record.isSixpro = isSixpro
        record.sixproCode = sixproCode
        record.remarks = remarks
        record.Status = Status
        record.orderIdx = orderIdx
        record.qyje = qyje
        record.kgqr = kgqr
        record.jgqr = jgqr
        record.projLevel = projLevel
        record.isNew = isNew
        record.isWorld = isWorld
        record.isChina = isChina
        record.isListed = isListed
        record.isUnicorn = isUnicorn
        record.mujunTax = mujunTax
        record.mainCustomer = mainCustomer
        record.planTotal = planTotal
        record.zhuceMoney = zhuceMoney
        record.planStartDate = planStartDate
        record.planEndDate = planEndDate
        record.projectMaterial = projectMaterial
        record.mainProcess = mainProcess
        record.isNewproject = isNewproject
        record.projectAddress = projectAddress
        record.sqLandArea = sqLandArea
        record.isGx = isGx
        record.isGjs = isGjs
        record.isGyzl = isGyzl
        record.far = far
        record.yqKpxs = yqKpxs
        record.yqSs = yqSs
        record.yqWorker = yqWorker
        record.fixedPercent = fixedPercent
        record.investLevel = investLevel
        record.yqMjtax = yqMjtax
        record.isWaterpf = isWaterpf
        record.isWuran = isWuran
        record.totalUse = totalUse
        record.isYanfa = isYanfa
        record.isZhuanli = isZhuanli
        record.isImportant = isImportant
        record.isZsh = isZsh
        record.zshName = zshName
        record.yjYear = yjYear
        record.remark = remark
        record.isGazelle = isGazelle
        record.isSpecialized = isSpecialized
        record.deviceInvest = deviceInvest
        record.fixedInvest = fixedInvest
        record.bResource = bResource
        record.sjjgName = sjjgName
        record.qyLinker = qyLinker
        record.qyPhone = qyPhone
        record.sqLandYear = sqLandYear
        record.yqCz = yqCz
        record.zpjLevel = zpjLevel
        record.importProjType = importProjType
        record.planTotal1 = planTotal1
        record.planTotal2 = planTotal2
        record.isImportProj = isImportProj
        record.fxName = fxName
        record.yqKpxs1 = yqKpxs1
        record.yqKpxs2 = yqKpxs2
        record.yqKpxs3 = yqKpxs3
        record.yqSs1 = yqSs1
        record.yqSs2 = yqSs2
        record.yqSs3 = yqSs3
        record.yqMjtax1 = yqMjtax1
        record.yqMjtax2 = yqMjtax2
        record.yqMjtax3 = yqMjtax3
        record.tzfLevel = tzfLevel
        record.tzfFx = tzfFx
        record.cyGl = cyGl
        record.cpGy = cpGy
        record.team = team
        record.zlNum = zlNum
        record.hjContent = hjContent
        record.rProgress = rProgress
        record.isWarningInvest = isWarningInvest
        record.ifSjProj = ifSjProj
        record.yqCz1 = yqCz1
        record.yqCz2 = yqCz2
        record.yqCz3 = yqCz3
        record.cpQj = cpQj
        record.gyXl = gyXl
        record.gyLp = gyLp
        record.gyPj = gyPj
        record.zcfz = zcfz
        record.lirun = lirun
        record.xjll = xjll
        record.zczb = zczb
        record.zjly = zjly
        record.xypj = xypj
        record.xhpj = xhpj
        record.hegui = hegui
        record.zhpg = zhpg
        record.pgStatus = pgStatus
        record.isKcProj = isKcProj
        record.kcProjTj = kcProjTj
        record.isQflp = isQflp
        record.cgRemark = cgRemark
        record.tshy = tshy
        record.zrxz = zrxz
        record.lgxm = lgxm
        record.zjspf = zjspf
        record.cpscxz = cpscxz
        record.gysp = gysp
        record.scxl = scxl
        record.lpl = lpl
        record.isGxjs = isGxjs
        record.ifBuildYfzx = ifBuildYfzx
        record.buildYfzx = buildYfzx
        record.sjProj = sjProj
        record.zlLandArea = zlLandArea
        record.zlLandAreaZs = zlLandAreaZs
        record.ztpgzzcl = ztpgzzcl
        record.pzwh = pzwh
        record.pzrq = pzrq
        record.cxqk = cxqk
        record.qrKey = qrKey
        record.zsf = zsf
        record.tzf = tzf
        record.tzdz = tzdz
        record.xyzzcl = xyzzcl
        record.isRzxq = isRzxq
        record.rzMoney = rzMoney
        record.kcProjType = kcProjType
        record.kccl = kccl
        return record
    }
}
