@file:Suppress("unused")

package com.tzdig.framework.model.dto

import com.tzdig.framework.mybatis.entity.prime.ProjectDigitalInvestmentAttracting
import io.swagger.v3.oas.annotations.media.Schema

data class ProjectDigitalInvestmentAttractingDTO(
//    @param:Schema(description = "项目编号")
//    val projectCode: String?,
//    @param:Schema(description = "项目名称")
//    val projectName: String?,
//    @param:Schema(description = "所属区县")
//    val district: String?,
//    @param:Schema(description = "所属园区")
//    val park: String?,
//    @param:Schema(description = "项目审核状态（0，1：部门审核中，2：部门审核通过，3：部门审核退回，4专班审核中，5专班审核通过，6专班审核退回）")
//    val auditStatus: Int?,
//    @param:Schema(description = "项目审核状态（0，1：部门审核中，2：部门审核通过，3：部门审核退回，4专班审核中，5专班审核通过，6专班审核退回）")
//    val auditStatusKaigong: Int?,
//    @param:Schema(description = "国民经济分类")
//    val nationalEconomicClassification: String?,
//    @param:Schema(description = "统一社会信用代码")
//    val uscc: String?,
//    @param:Schema(description = "企业名称")
//    val companyName: String?,
//    @param:Schema(description = "企业注册资金")
//    val companyRegistrationFunds: Double?,
//    @param:Schema(description = "企业注册日期")
//    val companyRegistrationDate: LocalDate?,
//    @param:Schema(description = "项目类别")
//    val projectCategory: String?,
//    @param:Schema(description = "项目属性")
//    val projectAttribute: String?,
//    @param:Schema(description = "项目内容")
//    val projectContent: String?,
//    @param:Schema(description = "投资标识")
//    val investmentFlag: String?,
//    @param:Schema(description = "国别/地区")
//    val countryRegion: String?,
//    @param:Schema(description = "具体国别/地区")
//    val specificCountryRegion: String?,
//    @param:Schema(description = "投资方")
//    val investor: String?,
//    @param:Schema(description = "投资金额（亿美元/亿元）")
//    val investmentAmount: Double?,
//    @param:Schema(description = "注册资本（亿美元/亿元）")
//    val registeredCapital: String?,
//    @param:Schema(description = "洽谈进度")
//    val negotiationProgress: String?,
//    @param:Schema(description = "产业分类名称")
//    val industryClassification: String?,
//    @param:Schema(description = "当前项目进度")
//    val currentProjectProgress: String?,
//    @param:Schema(description = "入库时间")
//    val entryTime: LocalDateTime?,
//    @param:Schema(description = "注册信息统计日期")
//    val registrationInfoStatisticsDate: LocalDate?,
//    @param:Schema(description = "佐证资料（营业执照）")
//    val certificateDataBusinessLicense: String?,
//    @param:Schema(description = "备案（核准）项目名称")
//    val filingApprovalProjectName: String?,
//    @param:Schema(description = "备案（核准）投资总额（亿元）")
//    val filingApprovalInvestmentTotal: Double?,
//    @param:Schema(description = "备案（核准）日期")
//    val filingApprovalDate: LocalDate?,
//    @param:Schema(description = "备案信息统计日期")
//    val filingInfoStatisticsDate: LocalDate?,
//    @param:Schema(description = "佐证资料（项目备案（核准）文件）")
//    val certificateDataProjectFilingApprovalFile: String?,
//    @param:Schema(description = "是否涉及固定资产投资项目")
//    val isFixedAssetInvestment: Boolean?,
//    @param:Schema(description = "是否涉及建设用地")
//    val isConstructionLand: Boolean?,
//    @param:Schema(description = "建设用地规划许可证编号")
//    val constructionLandPlanningPermitNumber: String?,
//    @param:Schema(description = "取得许可证日期")
//    val permitObtainDate: LocalDate?,
//    @param:Schema(description = "完成报批统计日期")
//    val completionReportStatisticsDate: LocalDate?,
//    @param:Schema(description = "佐证资料")
//    val certificateData: String?,
//    @param:Schema(description = "开工确认日期")
//    val startConfirmDate: LocalDate?,
//    @param:Schema(description = "竣工确认日期")
//    val endConfirmDate: LocalDate?,
//    @param:Schema(description = "是否为新引进企业")
//    val isNewIntroducedEnterprise: Boolean?,
//    @param:Schema(description = "项目评级（内资、外资；金额分级）")
//    val projectRating: String?,
//    @param:Schema(description = "主要投资方名称")
//    val mainInvestorName: String?,
//    @param:Schema(description = "计划总投资（亿元）")
//    val plannedTotalInvestment: String?,
//    @param:Schema(description = "项目选址位置")
//    val projectLocation: String?,
//    @param:Schema(description = "是否为招商会项目")
//    val isRecruitmentFairProject: Boolean?,
//    @param:Schema(description = "招商会名称")
//    val recruitmentFairName: String?,
//    @param:Schema(description = "签约统计时间")
//    val signingTime: LocalDate?,
//    @param:Schema(description = "实际签约时间")
//    val actualSigningTime: LocalDate?,
//    @param:Schema(description = "签约合同")
//    val signingContract: String?,
//    @param:Schema(description = "项目总投资额（亿美元）")
//    val totalInvestmentUsd: Double?,
//    @param:Schema(description = "项目总投资额（亿元）")
//    val totalInvestmentCny: Double?,
//    @param:Schema(description = "项目来源")
//    val projectSource: String?,
//    @param:Schema(description = "厂房类型")
//    val factoryType: String?,
//    @param:Schema(description = "拟用地面积（平方米）")
//    val plannedLandArea: Float?,
//    @param:Schema(description = "拟租厂房面积（平方米）")
//    val plannedRentalFactoryArea: Float?,
//    @param:Schema(description = "拟购厂房面积（平方米）")
//    val plannedPurchaseFactoryArea: Float?,
//    @param:Schema(description = "预计年销量（万元）")
//    val expectedAnnualSales: Float?,
//    @param:Schema(description = "预计年销售（万元）")
//    val expectedAnnualSalesAmount: Float?,
//    @param:Schema(description = "预计年税收（万元）")
//    val expectedAnnualTax: Float?,
//    @param:Schema(description = "项目类型")
//    val projectType: String?,
//    @param:Schema(description = "产业大类名称")
//    val industryMajorClassName: String?,
//    @param:Schema(description = "所属行业")
//    val belongingIndustry: String?,
//    @param:Schema(description = "投资方性质")
//    val investorNature: String?,
//    @param:Schema(description = "项目简介")
//    val projectProfile: String?,
//    @param:Schema(description = "是否为世界500强或全球专业领域行业龙头企业")
//    val isWorldTop500OrLeadingGlobalCompany: Boolean?,
//    @param:Schema(description = "是否为国内500强或国内行业排名前100企业")
//    val isDomesticTop500OrTop100Company: Boolean?,
//    @param:Schema(description = "是否为上市公司或上市辅导期企业")
//    val isPubliclyTradedOrPreIpoCompany: Boolean?,
//    @param:Schema(description = "是否为瞪羚、专精特新、独角兽企业")
//    val isUnicornStartup: Boolean?,
//    @param:Schema(description = "已投资项目对属地政府亩均税收（万元）")
//    val averageTaxPerMuOfExistingInvestment: Float?,
//    @param:Schema(description = "主要客户")
//    val majorCustomers: String?,
//    @param:Schema(description = "固定资产投资（万元）")
//    val fixedAssetInvestment: Float?,
//    @param:Schema(description = "设备投资（万元）")
//    val equipmentInvestment: Float?,
//    @param:Schema(description = "计划开工时间")
//    val plannedStartTime: LocalDate?,
//    @param:Schema(description = "计划竣工时间")
//    val plannedEndTime: LocalDate?,
//    @param:Schema(description = "项目使用主要原、辅材料")
//    val mainRawMaterialsUsed: String?,
//    @param:Schema(description = "主要流程工艺")
//    val mainProcessTechnology: String?,
//    @param:Schema(description = "是否为新供地项目")
//    val isNewSupplyLandProject: Boolean?,
//    @param:Schema(description = "申请用地面积（亩）")
//    val appliedLandArea: Float?,
//    @param:Schema(description = "行业是否属于高新技术产业分类目录")
//    val isHighTechIndustry: Boolean?,
//    @param:Schema(description = "是否为高技术项目")
//    val isHighTechProject: Boolean?,
//    @param:Schema(description = "是否为国家工业战略性新兴产业")
//    val isNationalStrategicEmergingIndustry: Boolean?,
//    @param:Schema(description = "容积率（%）")
//    val plotRatioPercent: Float?,
//    @param:Schema(description = "预期开票销售（万元）")
//    val expectedInvoiceSales: Float?,
//    @param:Schema(description = "预期税收（万元）")
//    val expectedTax: Float?,
//    @param:Schema(description = "预期用工人数（人）")
//    val expectedEmployeeCount: Int?,
//    @param:Schema(description = "固定资产投资占比（%）")
//    val fixedAssetInvestmentPercentage: Float?,
//    @param:Schema(description = "投资强度（万元/千平方米）")
//    val investmentIntensity: String?,
//    @param:Schema(description = "预期亩均税收（万元/千平方米）")
//    val expectedAverageTax: Float?,
//    @param:Schema(description = "是否有产生废水和挥发性有机废水排放")
//    val wastewaterBy1: String?,
//    @param:Schema(description = "产生废水是否含氮、磷或使用高挥发性有机化合物含量涂料、油墨、胶粘剂")
//    val wastewaterBy2: Boolean?,
//    @param:Schema(description = "总能耗")
//    val totalEnergyConsumption: String?,
//    @param:Schema(description = "项目是否含有研发团队、产学研合作及研发机构建设内容")
//    val hasRndTeamAndCooperation: Boolean?,
//    @param:Schema(description = "项目是否拥有相关有效发明专利")
//    val hasValidPatents: Boolean?,
//    @param:Schema(description = "是否拟列入重点活动签约项目库")
//    val isListedAsKeyActivitySigningProject: Boolean?,
//    @param:Schema(description = "备注")
//    val remarks: String?,
//    @param:Schema(description = "协议利用外资（万美元）")
//    val agreementForeignDirectInvestment: Float?,
//    @param:Schema(description = "招商项目ID")
//    val investOnlineId: String?,
//    @param:Schema(description = "项目来源")
//    val source: String?,
//    @param:Schema(description = "市级机关名称")
//    val sjjgName: String?,
//    @param:Schema(description = "是否需要质量评估")
//    val isQualityEvaluation: Boolean?,
//    @param:Schema(description = "是否需要项目审核")
//    val isProjectReview: Boolean?,
//    @param:Schema(description = "是否完成项目审核")
//    val isProjectReviewComplete: Boolean?,
//    @param:Schema(description = "质态评估是否完成")
//    val isQualityEvaluationComplete: Boolean?,
//    @param:Schema(description = "是否开工申请")
//    val isStartApproval: Boolean?,
//    @param:Schema(description = "是否竣工审批")
//    val isCompletionApproval: Boolean?,
//    @param:Schema(description = "0&#61;待审核 1&#61;市级审核通过 2&#61;市区审核通过 3&#61;审核不通过 4&#61;保存未提交")
//    val checkStatus: Short?,
//    @param:Schema(description = "建筑类型")
//    val buildingType: String?,
//    @param:Schema(description = "使用面积")
//    val useArea: String?,
//    @param:Schema(description = "租赁面积")
//    val rentArea: String?,
//    @param:Schema(description = "购买面积")
//    val buyArea: String?,
//    @param:Schema(description = "年度销量")
//    val yearXl: String?,
//    @param:Schema(description = "年度税收")
//    val yearSs: String?,
//    @param:Schema(description = "评估状态")
//    val pgStatus: String?,
//    @param:Schema(description = "是否科创项目")
//    val isKcProj: String?,
//    @param:Schema(description = "科创项目条件")
//    val kcProjTj: String?,
//    @param:Schema(description = "是否QFLP外资项目")
//    val isQflp: String?,
//    @param:Schema(description = "成效说明")
//    val cgRemark: Nothing?,
//    @param:Schema(description = "是否特殊行业")
//    val tshy: String?,
//    @param:Schema(description = "准入限制")
//    val zrxz: String?,
//    @param:Schema(description = "是否两高项目")
//    val lgxm: String?,
//    @param:Schema(description = "是否有重金属排放")
//    val zjspf: String?,
//    @param:Schema(description = "产品市场现状")
//    val cpscxz: String?,
//    @param:Schema(description = "工艺水平")
//    val gysp: String?,
//    @param:Schema(description = "生产效率")
//    val scxl: String?,
//    @param:Schema(description = "良品率")
//    val lpl: String?,
//    @param:Schema(description = "是否高新技术企业")
//    val isGxjs: String?,
//    @param:Schema(description = "是否建立研发中心")
//    val isBuildYfzx: String?,
//    @param:Schema(description = "研发中心名称")
//    val buildYfzx: String?,
//    @param:Schema(description = "预期开票销售（万元）")
//    val yqKpxs: String?,
//    @param:Schema(description = "预期税收（万元）")
//    val yqSs: String?,
//    @param:Schema(description = "预期亩均税收（万元/亩）")
//    val yqMjtax: String?,
//    @param:Schema(description = "预期产值")
//    val yqCz: String?,
//    @param:Schema(description = "认定进度")
//    val rProgress: String?,
//    @param:Schema(description = "换算后签约金额")
//    val qyje: Double?,
//    @param:Schema(description = "产业关联度")
//    val cyGl: String?,
//    @param:Schema(description = "是否有融资需求")
//    val isRzxq: String?,
//    @param:Schema(description = "融资金额")
//    val rzMoney: String?,
//    @param:Schema(description = "初次接洽时间")
//    val firstTime: String?,
//    @param:Schema(description = "租赁厂房面积")
//    val zlLandArea: String?,
//    @param:Schema(description = "租赁厂房面积折算")
//    val zlLandAreaZs: String?,
    @param:Schema(description = "项目是否列统 ")
    val isLt: Boolean?,
    @param:Schema(description = "统计编码")
    val ltCode: String?,
) {
    fun toProjectDigitalInvestmentAttracting(): ProjectDigitalInvestmentAttracting =
        ProjectDigitalInvestmentAttracting {
            into(this)
        }

    fun into(record: ProjectDigitalInvestmentAttracting): ProjectDigitalInvestmentAttracting {
//        record.projectCode = projectCode
//        record.projectName = projectName
//        record.district = district
//        record.park = park
//        record.auditStatus = auditStatus
//        record.auditStatusKaigong = auditStatusKaigong
//        record.nationalEconomicClassification = nationalEconomicClassification
//        record.uscc = uscc
//        record.companyName = companyName
//        record.companyRegistrationFunds = companyRegistrationFunds
//        record.companyRegistrationDate = companyRegistrationDate
//        record.projectCategory = projectCategory
//        record.projectAttribute = projectAttribute
//        record.projectContent = projectContent
//        record.investmentFlag = investmentFlag
//        record.countryRegion = countryRegion
//        record.specificCountryRegion = specificCountryRegion
//        record.investor = investor
//        record.investmentAmount = investmentAmount
//        record.registeredCapital = registeredCapital
//        record.negotiationProgress = negotiationProgress
//        record.industryClassification = industryClassification
//        record.entryTime = entryTime
//        record.registrationInfoStatisticsDate = registrationInfoStatisticsDate
//        record.certificateDataBusinessLicense = certificateDataBusinessLicense
//        record.filingApprovalProjectName = filingApprovalProjectName
//        record.filingApprovalInvestmentTotal = filingApprovalInvestmentTotal
//        record.filingApprovalDate = filingApprovalDate
//        record.filingInfoStatisticsDate = filingInfoStatisticsDate
//        record.certificateDataProjectFilingApprovalFile = certificateDataProjectFilingApprovalFile
//        record.yesFixedAssetInvestment = isFixedAssetInvestment
//        record.isConstructionLand = isConstructionLand
//        record.constructionLandPlanningPermitNumber = constructionLandPlanningPermitNumber
//        record.permitObtainDate = permitObtainDate
//        record.completionReportStatisticsDate = completionReportStatisticsDate
//        record.certificateData = certificateData
//        record.startConfirmDate = startConfirmDate
//        record.endConfirmDate = endConfirmDate
//        record.isNewIntroducedEnterprise = isNewIntroducedEnterprise
//        record.projectRating = projectRating
//        record.mainInvestorName = mainInvestorName
//        record.plannedTotalInvestment = plannedTotalInvestment
//        record.projectLocation = projectLocation
//        record.isRecruitmentFairProject = isRecruitmentFairProject
//        record.recruitmentFairName = recruitmentFairName
//        record.signingTime = signingTime
//        record.actualSigningTime = actualSigningTime
//        record.signingContract = signingContract
//        record.totalInvestmentUsd = totalInvestmentUsd
//        record.totalInvestmentCny = totalInvestmentCny
//        record.projectSource = projectSource
//        record.factoryType = factoryType
//        record.plannedLandArea = plannedLandArea
//        record.plannedRentalFactoryArea = plannedRentalFactoryArea
//        record.plannedPurchaseFactoryArea = plannedPurchaseFactoryArea
//        record.expectedAnnualSales = expectedAnnualSales
//        record.expectedAnnualSalesAmount = expectedAnnualSalesAmount
//        record.expectedAnnualTax = expectedAnnualTax
//        record.projectType = projectType
//        record.industryMajorClassName = industryMajorClassName
//        record.belongingIndustry = belongingIndustry
//        record.investorNature = investorNature
//        record.projectProfile = projectProfile
//        record.isWorldTop500OrLeadingGlobalCompany = isWorldTop500OrLeadingGlobalCompany
//        record.isDomesticTop500OrTop100Company = isDomesticTop500OrTop100Company
//        record.isPubliclyTradedOrPreIPOCompany = isPubliclyTradedOrPreIpoCompany
//        record.isUnicornStartup = isUnicornStartup
//        record.averageTaxPerMuOfExistingInvestment = averageTaxPerMuOfExistingInvestment
//        record.majorCustomers = majorCustomers
//        record.fixedAssetInvestment = fixedAssetInvestment
//        record.equipmentInvestment = equipmentInvestment
//        record.plannedStartTime = plannedStartTime
//        record.plannedEndTime = plannedEndTime
//        record.mainRawMaterialsUsed = mainRawMaterialsUsed
//        record.mainProcessTechnology = mainProcessTechnology
//        record.isNewSupplyLandProject = isNewSupplyLandProject
//        record.appliedLandArea = appliedLandArea
//        record.isHighTechIndustry = isHighTechIndustry
//        record.isHighTechProject = isHighTechProject
//        record.isNationalStrategicEmergingIndustry = isNationalStrategicEmergingIndustry
//        record.plotRatioPercent = plotRatioPercent
//        record.expectedInvoiceSales = expectedInvoiceSales
//        record.expectedTax = expectedTax
//        record.expectedEmployeeCount = expectedEmployeeCount
//        record.fixedAssetInvestmentPercentage = fixedAssetInvestmentPercentage
//        record.investmentIntensity = investmentIntensity
//        record.expectedAverageTax = expectedAverageTax
//        record.wastewaterBy1 = wastewaterBy1
//        record.wastewaterBy2 = wastewaterBy2
//        record.totalEnergyConsumption = totalEnergyConsumption
//        record.hasRndTeamAndCooperation = hasRndTeamAndCooperation
//        record.hasValidPatents = hasValidPatents
//        record.isListedAsKeyActivitySigningProject = isListedAsKeyActivitySigningProject
//        record.remarks = remarks
//        record.agreementForeignDirectInvestment = agreementForeignDirectInvestment
//        record.investOnlineId = investOnlineId
//        record.source = source
//        record.sjjgName = sjjgName
//        record.isQualityEvaluation = isQualityEvaluation
//        record.isProjectReview = isProjectReview
//        record.isProjectReviewComplete = isProjectReviewComplete
//        record.isQualityEvaluationComplete = isQualityEvaluationComplete
//        record.isStartApproval = isStartApproval
//        record.isCompletionApproval = isCompletionApproval
//        record.checkStatus = checkStatus
//        record.buildingType = buildingType
//        record.useArea = useArea
//        record.rentArea = rentArea
//        record.buyArea = buyArea
//        record.yearXl = yearXl
//        record.yearSs = yearSs
//        record.pgStatus = pgStatus
//        record.isKcProj = isKcProj
//        record.kcProjTj = kcProjTj
//        record.isQflp = isQflp
//        record.cgRemark = cgRemark
//        record.tshy = tshy
//        record.zrxz = zrxz
//        record.lgxm = lgxm
//        record.zjspf = zjspf
//        record.cpscxz = cpscxz
//        record.gysp = gysp
//        record.scxl = scxl
//        record.lpl = lpl
//        record.ifGxjs = isGxjs
//        record.ifBuildYfzx = isBuildYfzx
//        record.buildYfzx = buildYfzx
//        record.yqKpxs = yqKpxs
//        record.yqSs = yqSs
//        record.yqMjtax = yqMjtax
//        record.yqCz = yqCz
//        record.rProgress = rProgress
//        record.qyje = qyje
//        record.cyGl = cyGl
//        record.isRzxq = isRzxq
//        record.rzMoney = rzMoney
//        record.firstTime = firstTime
//        record.zlLandArea = zlLandArea
//        record.zlLandAreaZs = zlLandAreaZs
        record.isLt = isLt
        record.ltCode = ltCode
        return record
    }
}
