/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DigitalTaizhouDto
 */
export interface DigitalTaizhouDto {
    /**
     * 指标大类
     * @type {string}
     * @memberof DigitalTaizhouDto
     */
    indicatorCategory?: string;
    /**
     * 指标小类
     * @type {string}
     * @memberof DigitalTaizhouDto
     */
    indicatorSubcategory?: string;
    /**
     * 年份
     * @type {string}
     * @memberof DigitalTaizhouDto
     */
    year?: string;
    /**
     * 季度
     * @type {string}
     * @memberof DigitalTaizhouDto
     */
    quarter?: string;
    /**
     * 累计绝对额
     * @type {number}
     * @memberof DigitalTaizhouDto
     */
    cumulativeAbsoluteAmount?: number;
    /**
     * 期末
     * @type {string}
     * @memberof DigitalTaizhouDto
     */
    endOfPeriodValue?: string;
    /**
     * 单位
     * @type {string}
     * @memberof DigitalTaizhouDto
     */
    unit?: string;
    /**
     * 累计增幅（%）
     * @type {number}
     * @memberof DigitalTaizhouDto
     */
    cumulativeGrowthRate?: number;
}


/**
 * Check if a given object implements the DigitalTaizhouDto interface.
 */
export function instanceOfDigitalTaizhouDto(value: object): value is DigitalTaizhouDto {
    return true;
}

export function DigitalTaizhouDtoFromJSON(json: any): DigitalTaizhouDto {
    return DigitalTaizhouDtoFromJSONTyped(json, false);
}

export function DigitalTaizhouDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigitalTaizhouDto {
    if (json == null) {
        return json;
    }
    return {
        
        'indicatorCategory': json['indicatorCategory'] == null ? undefined : json['indicatorCategory'],
        'indicatorSubcategory': json['indicatorSubcategory'] == null ? undefined : json['indicatorSubcategory'],
        'year': json['year'] == null ? undefined : json['year'],
        'quarter': json['quarter'] == null ? undefined : json['quarter'],
        'cumulativeAbsoluteAmount': json['cumulativeAbsoluteAmount'] == null ? undefined : json['cumulativeAbsoluteAmount'],
        'endOfPeriodValue': json['endOfPeriodValue'] == null ? undefined : json['endOfPeriodValue'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'cumulativeGrowthRate': json['cumulativeGrowthRate'] == null ? undefined : json['cumulativeGrowthRate'],
    };
}

export function DigitalTaizhouDtoToJSON(json: any): DigitalTaizhouDto {
    return DigitalTaizhouDtoToJSONTyped(json, false);
}

export function DigitalTaizhouDtoToJSONTyped(value?: DigitalTaizhouDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'indicatorCategory': value['indicatorCategory'],
        'indicatorSubcategory': value['indicatorSubcategory'],
        'year': value['year'],
        'quarter': value['quarter'],
        'cumulativeAbsoluteAmount': value['cumulativeAbsoluteAmount'],
        'endOfPeriodValue': value['endOfPeriodValue'],
        'unit': value['unit'],
        'cumulativeGrowthRate': value['cumulativeGrowthRate'],
    };
}


