/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DigitalEconomicTaxLevelDto
 */
export interface DigitalEconomicTaxLevelDto {
    /**
     * 统一社会信用代码
     * @type {string}
     * @memberof DigitalEconomicTaxLevelDto
     */
    companyCode?: string;
    /**
     * 公司名称
     * @type {string}
     * @memberof DigitalEconomicTaxLevelDto
     */
    companyName?: string;
    /**
     * 2025年7月当月开票销售档次
     * @type {string}
     * @memberof DigitalEconomicTaxLevelDto
     */
    levelThisMonth?: string;
    /**
     * 2025年1-7月开票销售档次
     * @type {string}
     * @memberof DigitalEconomicTaxLevelDto
     */
    levelThisYear?: string;
    /**
     * 市区
     * @type {string}
     * @memberof DigitalEconomicTaxLevelDto
     */
    district?: string;
}


/**
 * Check if a given object implements the DigitalEconomicTaxLevelDto interface.
 */
export function instanceOfDigitalEconomicTaxLevelDto(value: object): value is DigitalEconomicTaxLevelDto {
    return true;
}

export function DigitalEconomicTaxLevelDtoFromJSON(json: any): DigitalEconomicTaxLevelDto {
    return DigitalEconomicTaxLevelDtoFromJSONTyped(json, false);
}

export function DigitalEconomicTaxLevelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigitalEconomicTaxLevelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'companyCode': json['companyCode'] == null ? undefined : json['companyCode'],
        'companyName': json['companyName'] == null ? undefined : json['companyName'],
        'levelThisMonth': json['levelThisMonth'] == null ? undefined : json['levelThisMonth'],
        'levelThisYear': json['levelThisYear'] == null ? undefined : json['levelThisYear'],
        'district': json['district'] == null ? undefined : json['district'],
    };
}

export function DigitalEconomicTaxLevelDtoToJSON(json: any): DigitalEconomicTaxLevelDto {
    return DigitalEconomicTaxLevelDtoToJSONTyped(json, false);
}

export function DigitalEconomicTaxLevelDtoToJSONTyped(value?: DigitalEconomicTaxLevelDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'companyCode': value['companyCode'],
        'companyName': value['companyName'],
        'levelThisMonth': value['levelThisMonth'],
        'levelThisYear': value['levelThisYear'],
        'district': value['district'],
    };
}


