/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilingStatVo
 */
export interface FilingStatVo {
    /**
     * 新备案项目本月
     * @type {number}
     * @memberof FilingStatVo
     */
    month: number;
    /**
     * 新备案项目本月
     * @type {number}
     * @memberof FilingStatVo
     */
    year: number;
    /**
     * 累计备案总投资
     * @type {number}
     * @memberof FilingStatVo
     */
    total: number;
    /**
     * 需新增用地项目
     * @type {number}
     * @memberof FilingStatVo
     */
    needAddLand: number;
    /**
     * 已取得土地
     * @type {number}
     * @memberof FilingStatVo
     */
    land: number;
    /**
     * 无需新增用地项目
     * @type {number}
     * @memberof FilingStatVo
     */
    noNeedAddLand: number;
    /**
     * 环评
     * @type {number}
     * @memberof FilingStatVo
     */
    environment: number;
    /**
     * 能评
     * @type {number}
     * @memberof FilingStatVo
     */
    energy: number;
    /**
     * 安评
     * @type {number}
     * @memberof FilingStatVo
     */
    security: number;
    /**
     * 施工图审查
     * @type {number}
     * @memberof FilingStatVo
     */
    map: number;
    /**
     * 施工许可证
     * @type {number}
     * @memberof FilingStatVo
     */
    construction: number;
    /**
     * 工业项目
     * @type {number}
     * @memberof FilingStatVo
     */
    industry: number;
    /**
     * 工业项目备案总投资
     * @type {number}
     * @memberof FilingStatVo
     */
    total2: number;
    /**
     * 重点链群项目数
     * @type {number}
     * @memberof FilingStatVo
     */
    keyIndustry: number;
    /**
     * 链群项目备案总投资
     * @type {number}
     * @memberof FilingStatVo
     */
    total3: number;
}


/**
 * Check if a given object implements the FilingStatVo interface.
 */
export function instanceOfFilingStatVo(value: object): value is FilingStatVo {
    if (!('month' in value) || value['month'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('needAddLand' in value) || value['needAddLand'] === undefined) return false;
    if (!('land' in value) || value['land'] === undefined) return false;
    if (!('noNeedAddLand' in value) || value['noNeedAddLand'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('energy' in value) || value['energy'] === undefined) return false;
    if (!('security' in value) || value['security'] === undefined) return false;
    if (!('map' in value) || value['map'] === undefined) return false;
    if (!('construction' in value) || value['construction'] === undefined) return false;
    if (!('industry' in value) || value['industry'] === undefined) return false;
    if (!('total2' in value) || value['total2'] === undefined) return false;
    if (!('keyIndustry' in value) || value['keyIndustry'] === undefined) return false;
    if (!('total3' in value) || value['total3'] === undefined) return false;
    return true;
}

export function FilingStatVoFromJSON(json: any): FilingStatVo {
    return FilingStatVoFromJSONTyped(json, false);
}

export function FilingStatVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilingStatVo {
    if (json == null) {
        return json;
    }
    return {
        
        'month': json['month'],
        'year': json['year'],
        'total': json['total'],
        'needAddLand': json['needAddLand'],
        'land': json['land'],
        'noNeedAddLand': json['noNeedAddLand'],
        'environment': json['environment'],
        'energy': json['energy'],
        'security': json['security'],
        'map': json['map'],
        'construction': json['construction'],
        'industry': json['industry'],
        'total2': json['total2'],
        'keyIndustry': json['keyIndustry'],
        'total3': json['total3'],
    };
}

export function FilingStatVoToJSON(json: any): FilingStatVo {
    return FilingStatVoToJSONTyped(json, false);
}

export function FilingStatVoToJSONTyped(value?: FilingStatVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'month': value['month'],
        'year': value['year'],
        'total': value['total'],
        'needAddLand': value['needAddLand'],
        'land': value['land'],
        'noNeedAddLand': value['noNeedAddLand'],
        'environment': value['environment'],
        'energy': value['energy'],
        'security': value['security'],
        'map': value['map'],
        'construction': value['construction'],
        'industry': value['industry'],
        'total2': value['total2'],
        'keyIndustry': value['keyIndustry'],
        'total3': value['total3'],
    };
}


