/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FixedAssetInvestment
 */
export interface FixedAssetInvestment {
    /**
     * 1-2月完成数
     * @type {number}
     * @memberof FixedAssetInvestment
     */
    monthCompleted?: number;
    /**
     * 一季度预测数
     * @type {number}
     * @memberof FixedAssetInvestment
     */
    q1Forecast?: number;
    /**
     * 一季度投资完成进度
     * @type {number}
     * @memberof FixedAssetInvestment
     */
    q1Progress?: number;
    /**
     * 全年预测数
     * @type {number}
     * @memberof FixedAssetInvestment
     */
    yearForecast?: number;
    /**
     * 全年完成进度
     * @type {number}
     * @memberof FixedAssetInvestment
     */
    yearProgress?: number;
}


/**
 * Check if a given object implements the FixedAssetInvestment interface.
 */
export function instanceOfFixedAssetInvestment(value: object): value is FixedAssetInvestment {
    return true;
}

export function FixedAssetInvestmentFromJSON(json: any): FixedAssetInvestment {
    return FixedAssetInvestmentFromJSONTyped(json, false);
}

export function FixedAssetInvestmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): FixedAssetInvestment {
    if (json == null) {
        return json;
    }
    return {
        
        'monthCompleted': json['monthCompleted'] == null ? undefined : json['monthCompleted'],
        'q1Forecast': json['q1Forecast'] == null ? undefined : json['q1Forecast'],
        'q1Progress': json['q1Progress'] == null ? undefined : json['q1Progress'],
        'yearForecast': json['yearForecast'] == null ? undefined : json['yearForecast'],
        'yearProgress': json['yearProgress'] == null ? undefined : json['yearProgress'],
    };
}

export function FixedAssetInvestmentToJSON(json: any): FixedAssetInvestment {
    return FixedAssetInvestmentToJSONTyped(json, false);
}

export function FixedAssetInvestmentToJSONTyped(value?: FixedAssetInvestment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'monthCompleted': value['monthCompleted'],
        'q1Forecast': value['q1Forecast'],
        'q1Progress': value['q1Progress'],
        'yearForecast': value['yearForecast'],
        'yearProgress': value['yearProgress'],
    };
}


