/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForeignCapitalVo
 */
export interface ForeignCapitalVo {
    /**
     * 新设企业数（当期）
     * @type {number}
     * @memberof ForeignCapitalVo
     */
    newEnterpriseCountCurrent?: number;
    /**
     * 合同外资累计金额
     * @type {number}
     * @memberof ForeignCapitalVo
     */
    contractedForeignCapitalAmount?: number;
    /**
     * 实际使用外资金额
     * @type {number}
     * @memberof ForeignCapitalVo
     */
    actuallyUtilizedForeignCapitalAmount?: number;
}


/**
 * Check if a given object implements the ForeignCapitalVo interface.
 */
export function instanceOfForeignCapitalVo(value: object): value is ForeignCapitalVo {
    return true;
}

export function ForeignCapitalVoFromJSON(json: any): ForeignCapitalVo {
    return ForeignCapitalVoFromJSONTyped(json, false);
}

export function ForeignCapitalVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForeignCapitalVo {
    if (json == null) {
        return json;
    }
    return {
        
        'newEnterpriseCountCurrent': json['newEnterpriseCountCurrent'] == null ? undefined : json['newEnterpriseCountCurrent'],
        'contractedForeignCapitalAmount': json['contractedForeignCapitalAmount'] == null ? undefined : json['contractedForeignCapitalAmount'],
        'actuallyUtilizedForeignCapitalAmount': json['actuallyUtilizedForeignCapitalAmount'] == null ? undefined : json['actuallyUtilizedForeignCapitalAmount'],
    };
}

export function ForeignCapitalVoToJSON(json: any): ForeignCapitalVo {
    return ForeignCapitalVoToJSONTyped(json, false);
}

export function ForeignCapitalVoToJSONTyped(value?: ForeignCapitalVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newEnterpriseCountCurrent': value['newEnterpriseCountCurrent'],
        'contractedForeignCapitalAmount': value['contractedForeignCapitalAmount'],
        'actuallyUtilizedForeignCapitalAmount': value['actuallyUtilizedForeignCapitalAmount'],
    };
}


