/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { StatisticalInvestment } from './StatisticalInvestment';
import {
    StatisticalInvestmentFromJSON,
    StatisticalInvestmentFromJSONTyped,
    StatisticalInvestmentToJSON,
    StatisticalInvestmentToJSONTyped,
} from './StatisticalInvestment';
import type { IndustrialChainDistribution } from './IndustrialChainDistribution';
import {
    IndustrialChainDistributionFromJSON,
    IndustrialChainDistributionFromJSONTyped,
    IndustrialChainDistributionToJSON,
    IndustrialChainDistributionToJSONTyped,
} from './IndustrialChainDistribution';
import type { InvestmentCompletion } from './InvestmentCompletion';
import {
    InvestmentCompletionFromJSON,
    InvestmentCompletionFromJSONTyped,
    InvestmentCompletionToJSON,
    InvestmentCompletionToJSONTyped,
} from './InvestmentCompletion';
import type { UnderConstruction } from './UnderConstruction';
import {
    UnderConstructionFromJSON,
    UnderConstructionFromJSONTyped,
    UnderConstructionToJSON,
    UnderConstructionToJSONTyped,
} from './UnderConstruction';

/**
 * 
 * @export
 * @interface InvestmentOverview
 */
export interface InvestmentOverview {
    /**
     * 
     * @type {UnderConstruction}
     * @memberof InvestmentOverview
     */
    underConstruction: UnderConstruction;
    /**
     * 
     * @type {StatisticalInvestment}
     * @memberof InvestmentOverview
     */
    statisticalInvestment: StatisticalInvestment;
    /**
     * 
     * @type {InvestmentCompletion}
     * @memberof InvestmentOverview
     */
    investmentCompletion: InvestmentCompletion;
    /**
     * 
     * @type {IndustrialChainDistribution}
     * @memberof InvestmentOverview
     */
    industrialChainDistribution: IndustrialChainDistribution;
}


/**
 * Check if a given object implements the InvestmentOverview interface.
 */
export function instanceOfInvestmentOverview(value: object): value is InvestmentOverview {
    if (!('underConstruction' in value) || value['underConstruction'] === undefined) return false;
    if (!('statisticalInvestment' in value) || value['statisticalInvestment'] === undefined) return false;
    if (!('investmentCompletion' in value) || value['investmentCompletion'] === undefined) return false;
    if (!('industrialChainDistribution' in value) || value['industrialChainDistribution'] === undefined) return false;
    return true;
}

export function InvestmentOverviewFromJSON(json: any): InvestmentOverview {
    return InvestmentOverviewFromJSONTyped(json, false);
}

export function InvestmentOverviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvestmentOverview {
    if (json == null) {
        return json;
    }
    return {
        
        'underConstruction': UnderConstructionFromJSON(json['underConstruction']),
        'statisticalInvestment': StatisticalInvestmentFromJSON(json['statisticalInvestment']),
        'investmentCompletion': InvestmentCompletionFromJSON(json['investmentCompletion']),
        'industrialChainDistribution': IndustrialChainDistributionFromJSON(json['industrialChainDistribution']),
    };
}

export function InvestmentOverviewToJSON(json: any): InvestmentOverview {
    return InvestmentOverviewToJSONTyped(json, false);
}

export function InvestmentOverviewToJSONTyped(value?: InvestmentOverview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'underConstruction': UnderConstructionToJSON(value['underConstruction']),
        'statisticalInvestment': StatisticalInvestmentToJSON(value['statisticalInvestment']),
        'investmentCompletion': InvestmentCompletionToJSON(value['investmentCompletion']),
        'industrialChainDistribution': IndustrialChainDistributionToJSON(value['industrialChainDistribution']),
    };
}


