/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LhbInvestmentFixedAssetsQo
 */
export interface LhbInvestmentFixedAssetsQo {
    /**
     * 市或区的名称
     * @type {string}
     * @memberof LhbInvestmentFixedAssetsQo
     */
    regionName?: string;
    /**
     * 累计完成数值
     * @type {number}
     * @memberof LhbInvestmentFixedAssetsQo
     */
    cumulativeAmount?: number;
    /**
     * 一季度预测数值
     * @type {number}
     * @memberof LhbInvestmentFixedAssetsQo
     */
    q1Forecast?: number;
    /**
     * 一季度完成进度百分比
     * @type {number}
     * @memberof LhbInvestmentFixedAssetsQo
     */
    q1ProgressRate?: number;
    /**
     * 全年预测数值
     * @type {number}
     * @memberof LhbInvestmentFixedAssetsQo
     */
    annualForecast?: number;
    /**
     * 全年完成进度百分比
     * @type {number}
     * @memberof LhbInvestmentFixedAssetsQo
     */
    annualProgressRate?: number;
}


/**
 * Check if a given object implements the LhbInvestmentFixedAssetsQo interface.
 */
export function instanceOfLhbInvestmentFixedAssetsQo(value: object): value is LhbInvestmentFixedAssetsQo {
    return true;
}

export function LhbInvestmentFixedAssetsQoFromJSON(json: any): LhbInvestmentFixedAssetsQo {
    return LhbInvestmentFixedAssetsQoFromJSONTyped(json, false);
}

export function LhbInvestmentFixedAssetsQoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LhbInvestmentFixedAssetsQo {
    if (json == null) {
        return json;
    }
    return {
        
        'regionName': json['regionName'] == null ? undefined : json['regionName'],
        'cumulativeAmount': json['cumulativeAmount'] == null ? undefined : json['cumulativeAmount'],
        'q1Forecast': json['q1Forecast'] == null ? undefined : json['q1Forecast'],
        'q1ProgressRate': json['q1ProgressRate'] == null ? undefined : json['q1ProgressRate'],
        'annualForecast': json['annualForecast'] == null ? undefined : json['annualForecast'],
        'annualProgressRate': json['annualProgressRate'] == null ? undefined : json['annualProgressRate'],
    };
}

export function LhbInvestmentFixedAssetsQoToJSON(json: any): LhbInvestmentFixedAssetsQo {
    return LhbInvestmentFixedAssetsQoToJSONTyped(json, false);
}

export function LhbInvestmentFixedAssetsQoToJSONTyped(value?: LhbInvestmentFixedAssetsQo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'regionName': value['regionName'],
        'cumulativeAmount': value['cumulativeAmount'],
        'q1Forecast': value['q1Forecast'],
        'q1ProgressRate': value['q1ProgressRate'],
        'annualForecast': value['annualForecast'],
        'annualProgressRate': value['annualProgressRate'],
    };
}


