/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { TProjMoney } from './TProjMoney';
import {
    TProjMoneyFromJSON,
    TProjMoneyFromJSONTyped,
    TProjMoneyToJSON,
    TProjMoneyToJSONTyped,
} from './TProjMoney';

/**
 * 
 * @export
 * @interface PageableResultTProjMoney
 */
export interface PageableResultTProjMoney {
    /**
     * 
     * @type {number}
     * @memberof PageableResultTProjMoney
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTProjMoney
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTProjMoney
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTProjMoney
     */
    total: number;
    /**
     * 
     * @type {Array<TProjMoney>}
     * @memberof PageableResultTProjMoney
     */
    records: Array<TProjMoney>;
}


/**
 * Check if a given object implements the PageableResultTProjMoney interface.
 */
export function instanceOfPageableResultTProjMoney(value: object): value is PageableResultTProjMoney {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultTProjMoneyFromJSON(json: any): PageableResultTProjMoney {
    return PageableResultTProjMoneyFromJSONTyped(json, false);
}

export function PageableResultTProjMoneyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultTProjMoney {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(TProjMoneyFromJSON)),
    };
}

export function PageableResultTProjMoneyToJSON(json: any): PageableResultTProjMoney {
    return PageableResultTProjMoneyToJSONTyped(json, false);
}

export function PageableResultTProjMoneyToJSONTyped(value?: PageableResultTProjMoney | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(TProjMoneyToJSON)),
    };
}


