/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { TLy } from './TLy';
import {
    TLyFromJSON,
    TLyFromJSONTyped,
    TLyToJSON,
    TLyToJSONTyped,
} from './TLy';

/**
 * 
 * @export
 * @interface PageableResultTLy
 */
export interface PageableResultTLy {
    /**
     * 
     * @type {number}
     * @memberof PageableResultTLy
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTLy
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTLy
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultTLy
     */
    total: number;
    /**
     * 
     * @type {Array<TLy>}
     * @memberof PageableResultTLy
     */
    records: Array<TLy>;
}


/**
 * Check if a given object implements the PageableResultTLy interface.
 */
export function instanceOfPageableResultTLy(value: object): value is PageableResultTLy {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultTLyFromJSON(json: any): PageableResultTLy {
    return PageableResultTLyFromJSONTyped(json, false);
}

export function PageableResultTLyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultTLy {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(TLyFromJSON)),
    };
}

export function PageableResultTLyToJSON(json: any): PageableResultTLy {
    return PageableResultTLyToJSONTyped(json, false);
}

export function PageableResultTLyToJSONTyped(value?: PageableResultTLy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(TLyToJSON)),
    };
}


