/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionDto
 */
export interface PermissionDto {
    /**
     * 权限描述
     * @type {string}
     * @memberof PermissionDto
     */
    description: string;
}


/**
 * Check if a given object implements the PermissionDto interface.
 */
export function instanceOfPermissionDto(value: object): value is PermissionDto {
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function PermissionDtoFromJSON(json: any): PermissionDto {
    return PermissionDtoFromJSONTyped(json, false);
}

export function PermissionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
    };
}

export function PermissionDtoToJSON(json: any): PermissionDto {
    return PermissionDtoToJSONTyped(json, false);
}

export function PermissionDtoToJSONTyped(value?: PermissionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
    };
}


