/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectTimeFlowVo
 */
export interface ProjectTimeFlowVo {
    /**
     * 是否为主节点
     * @type {boolean}
     * @memberof ProjectTimeFlowVo
     */
    isPrimary: boolean;
    /**
     * 项目进展
     * @type {string}
     * @memberof ProjectTimeFlowVo
     */
    progress: string;
    /**
     * 标题
     * @type {string}
     * @memberof ProjectTimeFlowVo
     */
    title: string;
    /**
     * 时间
     * @type {Date}
     * @memberof ProjectTimeFlowVo
     */
    time?: Date;
    /**
     * 审核人名称
     * @type {string}
     * @memberof ProjectTimeFlowVo
     */
    name?: string;
    /**
     * 审核结果
     * @type {string}
     * @memberof ProjectTimeFlowVo
     */
    result?: string;
    /**
     * 审核评价
     * @type {string}
     * @memberof ProjectTimeFlowVo
     */
    comment?: string;
    /**
     * 是否完成
     * @type {boolean}
     * @memberof ProjectTimeFlowVo
     */
    completed?: boolean;
}


/**
 * Check if a given object implements the ProjectTimeFlowVo interface.
 */
export function instanceOfProjectTimeFlowVo(value: object): value is ProjectTimeFlowVo {
    if (!('isPrimary' in value) || value['isPrimary'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ProjectTimeFlowVoFromJSON(json: any): ProjectTimeFlowVo {
    return ProjectTimeFlowVoFromJSONTyped(json, false);
}

export function ProjectTimeFlowVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectTimeFlowVo {
    if (json == null) {
        return json;
    }
    return {
        
        'isPrimary': json['isPrimary'],
        'progress': json['progress'],
        'title': json['title'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'name': json['name'] == null ? undefined : json['name'],
        'result': json['result'] == null ? undefined : json['result'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'completed': json['completed'] == null ? undefined : json['completed'],
    };
}

export function ProjectTimeFlowVoToJSON(json: any): ProjectTimeFlowVo {
    return ProjectTimeFlowVoToJSONTyped(json, false);
}

export function ProjectTimeFlowVoToJSONTyped(value?: ProjectTimeFlowVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isPrimary': value['isPrimary'],
        'progress': value['progress'],
        'title': value['title'],
        'time': value['time'] == null ? undefined : ((value['time']).toISOString()),
        'name': value['name'],
        'result': value['result'],
        'comment': value['comment'],
        'completed': value['completed'],
    };
}


