/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectOnlineApprovalInfoDetailDto
 */
export interface ProjectOnlineApprovalInfoDetailDto {
    /**
     * 在线审批ID
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoDetailDto
     */
    onlineApprovalId?: string;
    /**
     * 在线审批信息ID
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoDetailDto
     */
    onlineApprovalInfoId?: string;
    /**
     * 办理环节
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoDetailDto
     */
    handlingProcess?: string;
    /**
     * 办理日期
     * @type {Date}
     * @memberof ProjectOnlineApprovalInfoDetailDto
     */
    handlingDate?: Date;
    /**
     * 办理部门
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoDetailDto
     */
    handlingDepartment?: string;
    /**
     * 部门区划
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoDetailDto
     */
    administrativeDivision?: string;
    /**
     * 内部办理科室
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoDetailDto
     */
    internalHandlingDepartment?: string;
    /**
     * 其他办理科室
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoDetailDto
     */
    otherHandlingDepartment?: string;
    /**
     * 备注
     * @type {string}
     * @memberof ProjectOnlineApprovalInfoDetailDto
     */
    remark?: string;
}


/**
 * Check if a given object implements the ProjectOnlineApprovalInfoDetailDto interface.
 */
export function instanceOfProjectOnlineApprovalInfoDetailDto(value: object): value is ProjectOnlineApprovalInfoDetailDto {
    return true;
}

export function ProjectOnlineApprovalInfoDetailDtoFromJSON(json: any): ProjectOnlineApprovalInfoDetailDto {
    return ProjectOnlineApprovalInfoDetailDtoFromJSONTyped(json, false);
}

export function ProjectOnlineApprovalInfoDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectOnlineApprovalInfoDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'onlineApprovalId': json['onlineApprovalId'] == null ? undefined : json['onlineApprovalId'],
        'onlineApprovalInfoId': json['onlineApprovalInfoId'] == null ? undefined : json['onlineApprovalInfoId'],
        'handlingProcess': json['handlingProcess'] == null ? undefined : json['handlingProcess'],
        'handlingDate': json['handlingDate'] == null ? undefined : (new Date(json['handlingDate'])),
        'handlingDepartment': json['handlingDepartment'] == null ? undefined : json['handlingDepartment'],
        'administrativeDivision': json['administrativeDivision'] == null ? undefined : json['administrativeDivision'],
        'internalHandlingDepartment': json['internalHandlingDepartment'] == null ? undefined : json['internalHandlingDepartment'],
        'otherHandlingDepartment': json['otherHandlingDepartment'] == null ? undefined : json['otherHandlingDepartment'],
        'remark': json['remark'] == null ? undefined : json['remark'],
    };
}

export function ProjectOnlineApprovalInfoDetailDtoToJSON(json: any): ProjectOnlineApprovalInfoDetailDto {
    return ProjectOnlineApprovalInfoDetailDtoToJSONTyped(json, false);
}

export function ProjectOnlineApprovalInfoDetailDtoToJSONTyped(value?: ProjectOnlineApprovalInfoDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'onlineApprovalId': value['onlineApprovalId'],
        'onlineApprovalInfoId': value['onlineApprovalInfoId'],
        'handlingProcess': value['handlingProcess'],
        'handlingDate': value['handlingDate'] == null ? undefined : ((value['handlingDate']).toISOString().substring(0,10)),
        'handlingDepartment': value['handlingDepartment'],
        'administrativeDivision': value['administrativeDivision'],
        'internalHandlingDepartment': value['internalHandlingDepartment'],
        'otherHandlingDepartment': value['otherHandlingDepartment'],
        'remark': value['remark'],
    };
}


