/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectOnlineApprovalVo1
 */
export interface ProjectOnlineApprovalVo1 {
    /**
     * 主键
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    id?: string;
    /**
     * 项目审批类型
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    approvalType?: string;
    /**
     * 备案目录
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    filingCatalog?: string;
    /**
     * 备案目录分类
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    filingCatalogCategory?: string;
    /**
     * 项目代码
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    projectCode?: string;
    /**
     * 项目名称
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    projectName?: string;
    /**
     * 是否补办项目
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    isSupplementaryProject?: string;
    /**
     * 申报时间
     * @type {Date}
     * @memberof ProjectOnlineApprovalVo1
     */
    applicationTime?: Date;
    /**
     * 审核备类型
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    reviewFilingType?: string;
    /**
     * 项目类型
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    projectType?: string;
    /**
     * 建设性质
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    constructionNature?: string;
    /**
     * 项目属性
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    projectAttributes?: string;
    /**
     * 拟开工时间（年）
     * @type {number}
     * @memberof ProjectOnlineApprovalVo1
     */
    plannedStartYear?: number;
    /**
     * 拟建成时间（年）
     * @type {number}
     * @memberof ProjectOnlineApprovalVo1
     */
    plannedEndYear?: number;
    /**
     * 建设地点
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    constructionLocation?: string;
    /**
     * 国标行业
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    nationalIndustryStandard?: string;
    /**
     * 国标行业代码
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    nationalIndustryCode?: string;
    /**
     * 管理行业
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    managementIndustry?: string;
    /**
     * 建设规模及内容
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    constructionScaleAndContent?: string;
    /**
     * 总投资（万元）
     * @type {number}
     * @memberof ProjectOnlineApprovalVo1
     */
    totalInvestment?: number;
    /**
     * 用地面积（公顷）
     * @type {number}
     * @memberof ProjectOnlineApprovalVo1
     */
    landArea?: number;
    /**
     * 新增用地面积（公顷）
     * @type {number}
     * @memberof ProjectOnlineApprovalVo1
     */
    newLandArea?: number;
    /**
     * 农用地面积（公顷）
     * @type {number}
     * @memberof ProjectOnlineApprovalVo1
     */
    agriculturalLandArea?: number;
    /**
     * 项目资本金（万元）
     * @type {number}
     * @memberof ProjectOnlineApprovalVo1
     */
    projectCapital?: number;
    /**
     * 资金来源
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    fundingSource?: string;
    /**
     * 是否技改项目
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    isTechnicalReformProject?: string;
    /**
     * 产业政策类型
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    industrialPolicyType?: string;
    /**
     * 产业结构调整指导目录
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    industryAdjustmentGuidanceCatalog?: string;
    /**
     * 是否属于房屋市政工程
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    isInfrastructureEngineering?: string;
    /**
     * 是否同意投资平台为项目单位提供融资对接服务
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    agreeToProvideFinancingServices?: string;
    /**
     * 法人单位
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    legalCompany?: string;
    /**
     * 法人单位登记注册类型
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    legalCompanyRegistrationType?: string;
    /**
     * 法人单位证照类型
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    legalCompanyDocumentType?: string;
    /**
     * 法人单位证照号码
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    legalCompanyDocumentNumber?: string;
    /**
     * 法人单位控股情况
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    legalCompanyHoldingSituation?: string;
    /**
     * 法人单位联系人
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    legalCompanyContactName?: string;
    /**
     * 法人单位手机号码
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    legalCompanyContactPhone?: string;
    /**
     * 法人单位电子邮箱
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    legalCompanyContactEmail?: string;
    /**
     * 法人单位法人代表姓名
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    legalCompanyLegalRepresentative?: string;
    /**
     * 法人单位是否为该项目的控股单位
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    isLegalCompanyControllingForProject?: string;
    /**
     * 申报单位
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    applicationCompany?: string;
    /**
     * 申报单位登记注册类型
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    applicationCompanyRegistrationType?: string;
    /**
     * 申报单位证照类型
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    applicationCompanyDocumentType?: string;
    /**
     * 申报单位证照号码
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    applicationCompanyDocumentNumber?: string;
    /**
     * 申报单位控股情况
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    applicationCompanyHoldingSituation?: string;
    /**
     * 申报单位联系人
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    applicationCompanyContactName?: string;
    /**
     * 申报单位手机号码
     * @type {string}
     * @memberof ProjectOnlineApprovalVo1
     */
    applicationCompanyContactPhone?: string;
}


/**
 * Check if a given object implements the ProjectOnlineApprovalVo1 interface.
 */
export function instanceOfProjectOnlineApprovalVo1(value: object): value is ProjectOnlineApprovalVo1 {
    return true;
}

export function ProjectOnlineApprovalVo1FromJSON(json: any): ProjectOnlineApprovalVo1 {
    return ProjectOnlineApprovalVo1FromJSONTyped(json, false);
}

export function ProjectOnlineApprovalVo1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectOnlineApprovalVo1 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'approvalType': json['approvalType'] == null ? undefined : json['approvalType'],
        'filingCatalog': json['filingCatalog'] == null ? undefined : json['filingCatalog'],
        'filingCatalogCategory': json['filingCatalogCategory'] == null ? undefined : json['filingCatalogCategory'],
        'projectCode': json['projectCode'] == null ? undefined : json['projectCode'],
        'projectName': json['projectName'] == null ? undefined : json['projectName'],
        'isSupplementaryProject': json['isSupplementaryProject'] == null ? undefined : json['isSupplementaryProject'],
        'applicationTime': json['applicationTime'] == null ? undefined : (new Date(json['applicationTime'])),
        'reviewFilingType': json['reviewFilingType'] == null ? undefined : json['reviewFilingType'],
        'projectType': json['projectType'] == null ? undefined : json['projectType'],
        'constructionNature': json['constructionNature'] == null ? undefined : json['constructionNature'],
        'projectAttributes': json['projectAttributes'] == null ? undefined : json['projectAttributes'],
        'plannedStartYear': json['plannedStartYear'] == null ? undefined : json['plannedStartYear'],
        'plannedEndYear': json['plannedEndYear'] == null ? undefined : json['plannedEndYear'],
        'constructionLocation': json['constructionLocation'] == null ? undefined : json['constructionLocation'],
        'nationalIndustryStandard': json['nationalIndustryStandard'] == null ? undefined : json['nationalIndustryStandard'],
        'nationalIndustryCode': json['nationalIndustryCode'] == null ? undefined : json['nationalIndustryCode'],
        'managementIndustry': json['managementIndustry'] == null ? undefined : json['managementIndustry'],
        'constructionScaleAndContent': json['constructionScaleAndContent'] == null ? undefined : json['constructionScaleAndContent'],
        'totalInvestment': json['totalInvestment'] == null ? undefined : json['totalInvestment'],
        'landArea': json['landArea'] == null ? undefined : json['landArea'],
        'newLandArea': json['newLandArea'] == null ? undefined : json['newLandArea'],
        'agriculturalLandArea': json['agriculturalLandArea'] == null ? undefined : json['agriculturalLandArea'],
        'projectCapital': json['projectCapital'] == null ? undefined : json['projectCapital'],
        'fundingSource': json['fundingSource'] == null ? undefined : json['fundingSource'],
        'isTechnicalReformProject': json['isTechnicalReformProject'] == null ? undefined : json['isTechnicalReformProject'],
        'industrialPolicyType': json['industrialPolicyType'] == null ? undefined : json['industrialPolicyType'],
        'industryAdjustmentGuidanceCatalog': json['industryAdjustmentGuidanceCatalog'] == null ? undefined : json['industryAdjustmentGuidanceCatalog'],
        'isInfrastructureEngineering': json['isInfrastructureEngineering'] == null ? undefined : json['isInfrastructureEngineering'],
        'agreeToProvideFinancingServices': json['agreeToProvideFinancingServices'] == null ? undefined : json['agreeToProvideFinancingServices'],
        'legalCompany': json['legalCompany'] == null ? undefined : json['legalCompany'],
        'legalCompanyRegistrationType': json['legalCompanyRegistrationType'] == null ? undefined : json['legalCompanyRegistrationType'],
        'legalCompanyDocumentType': json['legalCompanyDocumentType'] == null ? undefined : json['legalCompanyDocumentType'],
        'legalCompanyDocumentNumber': json['legalCompanyDocumentNumber'] == null ? undefined : json['legalCompanyDocumentNumber'],
        'legalCompanyHoldingSituation': json['legalCompanyHoldingSituation'] == null ? undefined : json['legalCompanyHoldingSituation'],
        'legalCompanyContactName': json['legalCompanyContactName'] == null ? undefined : json['legalCompanyContactName'],
        'legalCompanyContactPhone': json['legalCompanyContactPhone'] == null ? undefined : json['legalCompanyContactPhone'],
        'legalCompanyContactEmail': json['legalCompanyContactEmail'] == null ? undefined : json['legalCompanyContactEmail'],
        'legalCompanyLegalRepresentative': json['legalCompanyLegalRepresentative'] == null ? undefined : json['legalCompanyLegalRepresentative'],
        'isLegalCompanyControllingForProject': json['isLegalCompanyControllingForProject'] == null ? undefined : json['isLegalCompanyControllingForProject'],
        'applicationCompany': json['applicationCompany'] == null ? undefined : json['applicationCompany'],
        'applicationCompanyRegistrationType': json['applicationCompanyRegistrationType'] == null ? undefined : json['applicationCompanyRegistrationType'],
        'applicationCompanyDocumentType': json['applicationCompanyDocumentType'] == null ? undefined : json['applicationCompanyDocumentType'],
        'applicationCompanyDocumentNumber': json['applicationCompanyDocumentNumber'] == null ? undefined : json['applicationCompanyDocumentNumber'],
        'applicationCompanyHoldingSituation': json['applicationCompanyHoldingSituation'] == null ? undefined : json['applicationCompanyHoldingSituation'],
        'applicationCompanyContactName': json['applicationCompanyContactName'] == null ? undefined : json['applicationCompanyContactName'],
        'applicationCompanyContactPhone': json['applicationCompanyContactPhone'] == null ? undefined : json['applicationCompanyContactPhone'],
    };
}

export function ProjectOnlineApprovalVo1ToJSON(json: any): ProjectOnlineApprovalVo1 {
    return ProjectOnlineApprovalVo1ToJSONTyped(json, false);
}

export function ProjectOnlineApprovalVo1ToJSONTyped(value?: ProjectOnlineApprovalVo1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'approvalType': value['approvalType'],
        'filingCatalog': value['filingCatalog'],
        'filingCatalogCategory': value['filingCatalogCategory'],
        'projectCode': value['projectCode'],
        'projectName': value['projectName'],
        'isSupplementaryProject': value['isSupplementaryProject'],
        'applicationTime': value['applicationTime'] == null ? undefined : ((value['applicationTime']).toISOString()),
        'reviewFilingType': value['reviewFilingType'],
        'projectType': value['projectType'],
        'constructionNature': value['constructionNature'],
        'projectAttributes': value['projectAttributes'],
        'plannedStartYear': value['plannedStartYear'],
        'plannedEndYear': value['plannedEndYear'],
        'constructionLocation': value['constructionLocation'],
        'nationalIndustryStandard': value['nationalIndustryStandard'],
        'nationalIndustryCode': value['nationalIndustryCode'],
        'managementIndustry': value['managementIndustry'],
        'constructionScaleAndContent': value['constructionScaleAndContent'],
        'totalInvestment': value['totalInvestment'],
        'landArea': value['landArea'],
        'newLandArea': value['newLandArea'],
        'agriculturalLandArea': value['agriculturalLandArea'],
        'projectCapital': value['projectCapital'],
        'fundingSource': value['fundingSource'],
        'isTechnicalReformProject': value['isTechnicalReformProject'],
        'industrialPolicyType': value['industrialPolicyType'],
        'industryAdjustmentGuidanceCatalog': value['industryAdjustmentGuidanceCatalog'],
        'isInfrastructureEngineering': value['isInfrastructureEngineering'],
        'agreeToProvideFinancingServices': value['agreeToProvideFinancingServices'],
        'legalCompany': value['legalCompany'],
        'legalCompanyRegistrationType': value['legalCompanyRegistrationType'],
        'legalCompanyDocumentType': value['legalCompanyDocumentType'],
        'legalCompanyDocumentNumber': value['legalCompanyDocumentNumber'],
        'legalCompanyHoldingSituation': value['legalCompanyHoldingSituation'],
        'legalCompanyContactName': value['legalCompanyContactName'],
        'legalCompanyContactPhone': value['legalCompanyContactPhone'],
        'legalCompanyContactEmail': value['legalCompanyContactEmail'],
        'legalCompanyLegalRepresentative': value['legalCompanyLegalRepresentative'],
        'isLegalCompanyControllingForProject': value['isLegalCompanyControllingForProject'],
        'applicationCompany': value['applicationCompany'],
        'applicationCompanyRegistrationType': value['applicationCompanyRegistrationType'],
        'applicationCompanyDocumentType': value['applicationCompanyDocumentType'],
        'applicationCompanyDocumentNumber': value['applicationCompanyDocumentNumber'],
        'applicationCompanyHoldingSituation': value['applicationCompanyHoldingSituation'],
        'applicationCompanyContactName': value['applicationCompanyContactName'],
        'applicationCompanyContactPhone': value['applicationCompanyContactPhone'],
    };
}


