/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectDivisionItemCostVo
 */
export interface ProjectDivisionItemCostVo {
    /**
     * 
     * @type {string}
     * @memberof ProjectDivisionItemCostVo
     */
    id: string;
    /**
     * 市（区）代码
     * @type {string}
     * @memberof ProjectDivisionItemCostVo
     */
    district: string;
    /**
     * 园区代码
     * @type {string}
     * @memberof ProjectDivisionItemCostVo
     */
    park: string;
    /**
     * 已完成施工图审查项目数量
     * @type {number}
     * @memberof ProjectDivisionItemCostVo
     */
    drawingReviewFinishCount: number;
    /**
     * 已提交施工图审查项目数量
     * @type {number}
     * @memberof ProjectDivisionItemCostVo
     */
    drawingReviewSubmitCount: number;
    /**
     * 施工图总用时
     * @type {number}
     * @memberof ProjectDivisionItemCostVo
     */
    drawingReviewCostTime: number;
    /**
     * 已完成环评项目数量
     * @type {number}
     * @memberof ProjectDivisionItemCostVo
     */
    envAssessmentFinishCount: number;
    /**
     * 已提交环评项目数量
     * @type {number}
     * @memberof ProjectDivisionItemCostVo
     */
    envAssessmentSubmitCount: number;
    /**
     * 环评总用时
     * @type {number}
     * @memberof ProjectDivisionItemCostVo
     */
    envAssessmentCostTime: number;
    /**
     * 已完成能评项目数量
     * @type {number}
     * @memberof ProjectDivisionItemCostVo
     */
    energyAssessmentFinishCount: number;
    /**
     * 已提交能评项目数量
     * @type {number}
     * @memberof ProjectDivisionItemCostVo
     */
    energyAssessmentSubmitCount: number;
    /**
     * 能评总用时
     * @type {number}
     * @memberof ProjectDivisionItemCostVo
     */
    energyAssessmentCostTime: number;
    /**
     * 施工许可数量
     * @type {number}
     * @memberof ProjectDivisionItemCostVo
     */
    constructionPermitsCount: number;
    /**
     * children
     * @type {Array<ProjectDivisionItemCostVo>}
     * @memberof ProjectDivisionItemCostVo
     */
    children: Array<ProjectDivisionItemCostVo>;
    /**
     * 园区名称
     * @type {string}
     * @memberof ProjectDivisionItemCostVo
     */
    parkName: string;
    /**
     * 市（区）名称
     * @type {string}
     * @memberof ProjectDivisionItemCostVo
     */
    districtName: string;
    /**
     * 施工图平均用时
     * @type {number}
     * @memberof ProjectDivisionItemCostVo
     */
    avgDrawingReviewCostTime: number;
    /**
     * 环评平均用时
     * @type {number}
     * @memberof ProjectDivisionItemCostVo
     */
    avgEnvAssessmentCostTime: number;
    /**
     * 能评平均用时
     * @type {number}
     * @memberof ProjectDivisionItemCostVo
     */
    avgEnergyAssessmentCostTime: number;
}


/**
 * Check if a given object implements the ProjectDivisionItemCostVo interface.
 */
export function instanceOfProjectDivisionItemCostVo(value: object): value is ProjectDivisionItemCostVo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('district' in value) || value['district'] === undefined) return false;
    if (!('park' in value) || value['park'] === undefined) return false;
    if (!('drawingReviewFinishCount' in value) || value['drawingReviewFinishCount'] === undefined) return false;
    if (!('drawingReviewSubmitCount' in value) || value['drawingReviewSubmitCount'] === undefined) return false;
    if (!('drawingReviewCostTime' in value) || value['drawingReviewCostTime'] === undefined) return false;
    if (!('envAssessmentFinishCount' in value) || value['envAssessmentFinishCount'] === undefined) return false;
    if (!('envAssessmentSubmitCount' in value) || value['envAssessmentSubmitCount'] === undefined) return false;
    if (!('envAssessmentCostTime' in value) || value['envAssessmentCostTime'] === undefined) return false;
    if (!('energyAssessmentFinishCount' in value) || value['energyAssessmentFinishCount'] === undefined) return false;
    if (!('energyAssessmentSubmitCount' in value) || value['energyAssessmentSubmitCount'] === undefined) return false;
    if (!('energyAssessmentCostTime' in value) || value['energyAssessmentCostTime'] === undefined) return false;
    if (!('constructionPermitsCount' in value) || value['constructionPermitsCount'] === undefined) return false;
    if (!('children' in value) || value['children'] === undefined) return false;
    if (!('parkName' in value) || value['parkName'] === undefined) return false;
    if (!('districtName' in value) || value['districtName'] === undefined) return false;
    if (!('avgDrawingReviewCostTime' in value) || value['avgDrawingReviewCostTime'] === undefined) return false;
    if (!('avgEnvAssessmentCostTime' in value) || value['avgEnvAssessmentCostTime'] === undefined) return false;
    if (!('avgEnergyAssessmentCostTime' in value) || value['avgEnergyAssessmentCostTime'] === undefined) return false;
    return true;
}

export function ProjectDivisionItemCostVoFromJSON(json: any): ProjectDivisionItemCostVo {
    return ProjectDivisionItemCostVoFromJSONTyped(json, false);
}

export function ProjectDivisionItemCostVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDivisionItemCostVo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'district': json['district'],
        'park': json['park'],
        'drawingReviewFinishCount': json['drawingReviewFinishCount'],
        'drawingReviewSubmitCount': json['drawingReviewSubmitCount'],
        'drawingReviewCostTime': json['drawingReviewCostTime'],
        'envAssessmentFinishCount': json['envAssessmentFinishCount'],
        'envAssessmentSubmitCount': json['envAssessmentSubmitCount'],
        'envAssessmentCostTime': json['envAssessmentCostTime'],
        'energyAssessmentFinishCount': json['energyAssessmentFinishCount'],
        'energyAssessmentSubmitCount': json['energyAssessmentSubmitCount'],
        'energyAssessmentCostTime': json['energyAssessmentCostTime'],
        'constructionPermitsCount': json['constructionPermitsCount'],
        'children': ((json['children'] as Array<any>).map(ProjectDivisionItemCostVoFromJSON)),
        'parkName': json['parkName'],
        'districtName': json['districtName'],
        'avgDrawingReviewCostTime': json['avgDrawingReviewCostTime'],
        'avgEnvAssessmentCostTime': json['avgEnvAssessmentCostTime'],
        'avgEnergyAssessmentCostTime': json['avgEnergyAssessmentCostTime'],
    };
}

export function ProjectDivisionItemCostVoToJSON(json: any): ProjectDivisionItemCostVo {
    return ProjectDivisionItemCostVoToJSONTyped(json, false);
}

export function ProjectDivisionItemCostVoToJSONTyped(value?: ProjectDivisionItemCostVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'district': value['district'],
        'park': value['park'],
        'drawingReviewFinishCount': value['drawingReviewFinishCount'],
        'drawingReviewSubmitCount': value['drawingReviewSubmitCount'],
        'drawingReviewCostTime': value['drawingReviewCostTime'],
        'envAssessmentFinishCount': value['envAssessmentFinishCount'],
        'envAssessmentSubmitCount': value['envAssessmentSubmitCount'],
        'envAssessmentCostTime': value['envAssessmentCostTime'],
        'energyAssessmentFinishCount': value['energyAssessmentFinishCount'],
        'energyAssessmentSubmitCount': value['energyAssessmentSubmitCount'],
        'energyAssessmentCostTime': value['energyAssessmentCostTime'],
        'constructionPermitsCount': value['constructionPermitsCount'],
        'children': ((value['children'] as Array<any>).map(ProjectDivisionItemCostVoToJSON)),
        'parkName': value['parkName'],
        'districtName': value['districtName'],
        'avgDrawingReviewCostTime': value['avgDrawingReviewCostTime'],
        'avgEnvAssessmentCostTime': value['avgEnvAssessmentCostTime'],
        'avgEnergyAssessmentCostTime': value['avgEnergyAssessmentCostTime'],
    };
}


