/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectDcdxCompletionInvestmentDto
 */
export interface ProjectDcdxCompletionInvestmentDto {
    /**
     * 市区名称
     * @type {string}
     * @memberof ProjectDcdxCompletionInvestmentDto
     */
    district?: string;
    /**
     * 园区名称
     * @type {string}
     * @memberof ProjectDcdxCompletionInvestmentDto
     */
    park?: string;
    /**
     * 年份
     * @type {number}
     * @memberof ProjectDcdxCompletionInvestmentDto
     */
    year?: number;
    /**
     * 竣工项目数
     * @type {number}
     * @memberof ProjectDcdxCompletionInvestmentDto
     */
    completedProjectCount?: number;
    /**
     * 签约投资额（万元）
     * @type {number}
     * @memberof ProjectDcdxCompletionInvestmentDto
     */
    signedInvestment?: number;
    /**
     * 完成投资额（万元）
     * @type {number}
     * @memberof ProjectDcdxCompletionInvestmentDto
     */
    completedInvestment?: number;
    /**
     * 其中：固定资产投资（万元）
     * @type {number}
     * @memberof ProjectDcdxCompletionInvestmentDto
     */
    fixedAssetInvestment?: number;
    /**
     * 设备投资（万元）
     * @type {number}
     * @memberof ProjectDcdxCompletionInvestmentDto
     */
    equipmentInvestment?: number;
    /**
     * 投资完成比重（完成/签约，小数形式）
     * @type {number}
     * @memberof ProjectDcdxCompletionInvestmentDto
     */
    investmentCompletionRatio?: number;
    /**
     * 所属产业链群
     * @type {string}
     * @memberof ProjectDcdxCompletionInvestmentDto
     */
    industrialChainCluster?: string;
    /**
     * 是否产业链群
     * @type {boolean}
     * @memberof ProjectDcdxCompletionInvestmentDto
     */
    isLq?: boolean;
}


/**
 * Check if a given object implements the ProjectDcdxCompletionInvestmentDto interface.
 */
export function instanceOfProjectDcdxCompletionInvestmentDto(value: object): value is ProjectDcdxCompletionInvestmentDto {
    return true;
}

export function ProjectDcdxCompletionInvestmentDtoFromJSON(json: any): ProjectDcdxCompletionInvestmentDto {
    return ProjectDcdxCompletionInvestmentDtoFromJSONTyped(json, false);
}

export function ProjectDcdxCompletionInvestmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDcdxCompletionInvestmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'district': json['district'] == null ? undefined : json['district'],
        'park': json['park'] == null ? undefined : json['park'],
        'year': json['year'] == null ? undefined : json['year'],
        'completedProjectCount': json['completedProjectCount'] == null ? undefined : json['completedProjectCount'],
        'signedInvestment': json['signedInvestment'] == null ? undefined : json['signedInvestment'],
        'completedInvestment': json['completedInvestment'] == null ? undefined : json['completedInvestment'],
        'fixedAssetInvestment': json['fixedAssetInvestment'] == null ? undefined : json['fixedAssetInvestment'],
        'equipmentInvestment': json['equipmentInvestment'] == null ? undefined : json['equipmentInvestment'],
        'investmentCompletionRatio': json['investmentCompletionRatio'] == null ? undefined : json['investmentCompletionRatio'],
        'industrialChainCluster': json['industrialChainCluster'] == null ? undefined : json['industrialChainCluster'],
        'isLq': json['isLq'] == null ? undefined : json['isLq'],
    };
}

export function ProjectDcdxCompletionInvestmentDtoToJSON(json: any): ProjectDcdxCompletionInvestmentDto {
    return ProjectDcdxCompletionInvestmentDtoToJSONTyped(json, false);
}

export function ProjectDcdxCompletionInvestmentDtoToJSONTyped(value?: ProjectDcdxCompletionInvestmentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'district': value['district'],
        'park': value['park'],
        'year': value['year'],
        'completedProjectCount': value['completedProjectCount'],
        'signedInvestment': value['signedInvestment'],
        'completedInvestment': value['completedInvestment'],
        'fixedAssetInvestment': value['fixedAssetInvestment'],
        'equipmentInvestment': value['equipmentInvestment'],
        'investmentCompletionRatio': value['investmentCompletionRatio'],
        'industrialChainCluster': value['industrialChainCluster'],
        'isLq': value['isLq'],
    };
}


