/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectStageCountVo
 */
export interface ProjectStageCountVo {
    /**
     * 
     * @type {string}
     * @memberof ProjectStageCountVo
     */
    id?: string;
    /**
     * 市（区）代码
     * @type {string}
     * @memberof ProjectStageCountVo
     */
    district?: string;
    /**
     * 园区代码
     * @type {string}
     * @memberof ProjectStageCountVo
     */
    park?: string;
    /**
     * 立项用地规划许可阶段
     * @type {number}
     * @memberof ProjectStageCountVo
     */
    stageApprovalCount?: number;
    /**
     * 工程建设许可和施工许可阶段
     * @type {number}
     * @memberof ProjectStageCountVo
     */
    stageECCount?: number;
    /**
     * 施工许可阶段
     * @type {number}
     * @memberof ProjectStageCountVo
     */
    stagePermitStageCount?: number;
    /**
     * 竣工验收阶段
     * @type {number}
     * @memberof ProjectStageCountVo
     */
    stageCompleted?: number;
    /**
     * children
     * @type {Array<ProjectStageCountVo>}
     * @memberof ProjectStageCountVo
     */
    children?: Array<ProjectStageCountVo>;
    /**
     * 市（区）名称
     * @type {string}
     * @memberof ProjectStageCountVo
     */
    districtName?: string;
    /**
     * 园区
     * @type {string}
     * @memberof ProjectStageCountVo
     */
    parkName?: string;
}


/**
 * Check if a given object implements the ProjectStageCountVo interface.
 */
export function instanceOfProjectStageCountVo(value: object): value is ProjectStageCountVo {
    return true;
}

export function ProjectStageCountVoFromJSON(json: any): ProjectStageCountVo {
    return ProjectStageCountVoFromJSONTyped(json, false);
}

export function ProjectStageCountVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectStageCountVo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'district': json['district'] == null ? undefined : json['district'],
        'park': json['park'] == null ? undefined : json['park'],
        'stageApprovalCount': json['stageApprovalCount'] == null ? undefined : json['stageApprovalCount'],
        'stageECCount': json['stageECCount'] == null ? undefined : json['stageECCount'],
        'stagePermitStageCount': json['stagePermitStageCount'] == null ? undefined : json['stagePermitStageCount'],
        'stageCompleted': json['stageCompleted'] == null ? undefined : json['stageCompleted'],
        'children': json['children'] == null ? undefined : ((json['children'] as Array<any>).map(ProjectStageCountVoFromJSON)),
        'districtName': json['districtName'] == null ? undefined : json['districtName'],
        'parkName': json['parkName'] == null ? undefined : json['parkName'],
    };
}

export function ProjectStageCountVoToJSON(json: any): ProjectStageCountVo {
    return ProjectStageCountVoToJSONTyped(json, false);
}

export function ProjectStageCountVoToJSONTyped(value?: ProjectStageCountVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'district': value['district'],
        'park': value['park'],
        'stageApprovalCount': value['stageApprovalCount'],
        'stageECCount': value['stageECCount'],
        'stagePermitStageCount': value['stagePermitStageCount'],
        'stageCompleted': value['stageCompleted'],
        'children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(ProjectStageCountVoToJSON)),
        'districtName': value['districtName'],
        'parkName': value['parkName'],
    };
}


