/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Statistic4KuVo
 */
export interface Statistic4KuVo {
    /**
     * 签约库数量
     * @type {number}
     * @memberof Statistic4KuVo
     */
    signData?: number;
    /**
     * 备案库数量
     * @type {number}
     * @memberof Statistic4KuVo
     */
    recordData?: number;
    /**
     * 开工库数量
     * @type {number}
     * @memberof Statistic4KuVo
     */
    buildData?: number;
    /**
     * 投产库数量
     * @type {number}
     * @memberof Statistic4KuVo
     */
    productData?: number;
}


/**
 * Check if a given object implements the Statistic4KuVo interface.
 */
export function instanceOfStatistic4KuVo(value: object): value is Statistic4KuVo {
    return true;
}

export function Statistic4KuVoFromJSON(json: any): Statistic4KuVo {
    return Statistic4KuVoFromJSONTyped(json, false);
}

export function Statistic4KuVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Statistic4KuVo {
    if (json == null) {
        return json;
    }
    return {
        
        'signData': json['signData'] == null ? undefined : json['signData'],
        'recordData': json['recordData'] == null ? undefined : json['recordData'],
        'buildData': json['buildData'] == null ? undefined : json['buildData'],
        'productData': json['productData'] == null ? undefined : json['productData'],
    };
}

export function Statistic4KuVoToJSON(json: any): Statistic4KuVo {
    return Statistic4KuVoToJSONTyped(json, false);
}

export function Statistic4KuVoToJSONTyped(value?: Statistic4KuVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signData': value['signData'],
        'recordData': value['recordData'],
        'buildData': value['buildData'],
        'productData': value['productData'],
    };
}


