/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatIndustryOutputVo
 */
export interface StatIndustryOutputVo {
    /**
     * 主键
     * @type {string}
     * @memberof StatIndustryOutputVo
     */
    id?: string;
    /**
     * 年份
     * @type {number}
     * @memberof StatIndustryOutputVo
     */
    year?: number;
    /**
     * 月份
     * @type {number}
     * @memberof StatIndustryOutputVo
     */
    month?: number;
    /**
     * 父指标
     * @type {string}
     * @memberof StatIndustryOutputVo
     */
    parentIndicator?: string;
    /**
     * 指标名称
     * @type {string}
     * @memberof StatIndustryOutputVo
     */
    indicator?: string;
    /**
     * 本期
     * @type {number}
     * @memberof StatIndustryOutputVo
     */
    current?: number;
    /**
     * 同期
     * @type {number}
     * @memberof StatIndustryOutputVo
     */
    last?: number;
    /**
     * 增长(%)
     * @type {number}
     * @memberof StatIndustryOutputVo
     */
    growth?: number;
    /**
     * 
     * @type {string}
     * @memberof StatIndustryOutputVo
     */
    children: string;
}


/**
 * Check if a given object implements the StatIndustryOutputVo interface.
 */
export function instanceOfStatIndustryOutputVo(value: object): value is StatIndustryOutputVo {
    if (!('children' in value) || value['children'] === undefined) return false;
    return true;
}

export function StatIndustryOutputVoFromJSON(json: any): StatIndustryOutputVo {
    return StatIndustryOutputVoFromJSONTyped(json, false);
}

export function StatIndustryOutputVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatIndustryOutputVo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'year': json['year'] == null ? undefined : json['year'],
        'month': json['month'] == null ? undefined : json['month'],
        'parentIndicator': json['parentIndicator'] == null ? undefined : json['parentIndicator'],
        'indicator': json['indicator'] == null ? undefined : json['indicator'],
        'current': json['current'] == null ? undefined : json['current'],
        'last': json['last'] == null ? undefined : json['last'],
        'growth': json['growth'] == null ? undefined : json['growth'],
        'children': json['children'],
    };
}

export function StatIndustryOutputVoToJSON(json: any): StatIndustryOutputVo {
    return StatIndustryOutputVoToJSONTyped(json, false);
}

export function StatIndustryOutputVoToJSONTyped(value?: StatIndustryOutputVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'year': value['year'],
        'month': value['month'],
        'parentIndicator': value['parentIndicator'],
        'indicator': value['indicator'],
        'current': value['current'],
        'last': value['last'],
        'growth': value['growth'],
        'children': value['children'],
    };
}


