/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 签约项目统计请求参数
 * @export
 * @interface StatisticsSignedProjectReqDto
 */
export interface StatisticsSignedProjectReqDto {
    /**
     * 投资金额条件：1-1亿，5-5亿，10-10亿
     * @type {number}
     * @memberof StatisticsSignedProjectReqDto
     */
    rmb: number;
    /**
     * 当前统计开始日期
     * @type {string}
     * @memberof StatisticsSignedProjectReqDto
     */
    currStartDate: string;
    /**
     * 当前统计结束日期
     * @type {string}
     * @memberof StatisticsSignedProjectReqDto
     */
    currEndDate: string;
    /**
     * 去年同期开始日期
     * @type {string}
     * @memberof StatisticsSignedProjectReqDto
     */
    lastYearStartDate?: string;
    /**
     * 去年同期结束日期
     * @type {string}
     * @memberof StatisticsSignedProjectReqDto
     */
    lastYearEndDate?: string;
    /**
     * 年度
     * @type {number}
     * @memberof StatisticsSignedProjectReqDto
     */
    year?: number;
    /**
     * 部门编码
     * @type {string}
     * @memberof StatisticsSignedProjectReqDto
     */
    deptCode?: string;
    /**
     * 区域编码
     * @type {string}
     * @memberof StatisticsSignedProjectReqDto
     */
    districtCode?: string;
    /**
     * 级别
     * @type {number}
     * @memberof StatisticsSignedProjectReqDto
     */
    level?: number;
    /**
     * 类型
     * @type {number}
     * @memberof StatisticsSignedProjectReqDto
     */
    type?: number;
    /**
     * 项目类型编码
     * @type {string}
     * @memberof StatisticsSignedProjectReqDto
     */
    projType?: string;
    /**
     * 
     * @type {number}
     * @memberof StatisticsSignedProjectReqDto
     */
    ptype?: number;
}


/**
 * Check if a given object implements the StatisticsSignedProjectReqDto interface.
 */
export function instanceOfStatisticsSignedProjectReqDto(value: object): value is StatisticsSignedProjectReqDto {
    if (!('rmb' in value) || value['rmb'] === undefined) return false;
    if (!('currStartDate' in value) || value['currStartDate'] === undefined) return false;
    if (!('currEndDate' in value) || value['currEndDate'] === undefined) return false;
    return true;
}

export function StatisticsSignedProjectReqDtoFromJSON(json: any): StatisticsSignedProjectReqDto {
    return StatisticsSignedProjectReqDtoFromJSONTyped(json, false);
}

export function StatisticsSignedProjectReqDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatisticsSignedProjectReqDto {
    if (json == null) {
        return json;
    }
    return {
        
        'rmb': json['rmb'],
        'currStartDate': json['currStartDate'],
        'currEndDate': json['currEndDate'],
        'lastYearStartDate': json['lastYearStartDate'] == null ? undefined : json['lastYearStartDate'],
        'lastYearEndDate': json['lastYearEndDate'] == null ? undefined : json['lastYearEndDate'],
        'year': json['year'] == null ? undefined : json['year'],
        'deptCode': json['deptCode'] == null ? undefined : json['deptCode'],
        'districtCode': json['districtCode'] == null ? undefined : json['districtCode'],
        'level': json['level'] == null ? undefined : json['level'],
        'type': json['type'] == null ? undefined : json['type'],
        'projType': json['projType'] == null ? undefined : json['projType'],
        'ptype': json['ptype'] == null ? undefined : json['ptype'],
    };
}

export function StatisticsSignedProjectReqDtoToJSON(json: any): StatisticsSignedProjectReqDto {
    return StatisticsSignedProjectReqDtoToJSONTyped(json, false);
}

export function StatisticsSignedProjectReqDtoToJSONTyped(value?: StatisticsSignedProjectReqDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rmb': value['rmb'],
        'currStartDate': value['currStartDate'],
        'currEndDate': value['currEndDate'],
        'lastYearStartDate': value['lastYearStartDate'],
        'lastYearEndDate': value['lastYearEndDate'],
        'year': value['year'],
        'deptCode': value['deptCode'],
        'districtCode': value['districtCode'],
        'level': value['level'],
        'type': value['type'],
        'projType': value['projType'],
        'ptype': value['ptype'],
    };
}


