/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemWorkflowVo
 */
export interface SystemWorkflowVo {
    /**
     * 主键
     * @type {string}
     * @memberof SystemWorkflowVo
     */
    id?: string;
    /**
     * 工作流代码
     * @type {string}
     * @memberof SystemWorkflowVo
     */
    code?: string;
    /**
     * 工作流名称
     * @type {string}
     * @memberof SystemWorkflowVo
     */
    name?: string;
}


/**
 * Check if a given object implements the SystemWorkflowVo interface.
 */
export function instanceOfSystemWorkflowVo(value: object): value is SystemWorkflowVo {
    return true;
}

export function SystemWorkflowVoFromJSON(json: any): SystemWorkflowVo {
    return SystemWorkflowVoFromJSONTyped(json, false);
}

export function SystemWorkflowVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemWorkflowVo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function SystemWorkflowVoToJSON(json: any): SystemWorkflowVo {
    return SystemWorkflowVoToJSONTyped(json, false);
}

export function SystemWorkflowVoToJSONTyped(value?: SystemWorkflowVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
    };
}


