/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemWorkflowLogDto
 */
export interface SystemWorkflowLogDto {
    /**
     * 工作流代码
     * @type {string}
     * @memberof SystemWorkflowLogDto
     */
    workflowCode?: string;
    /**
     * 审核记录ID
     * @type {string}
     * @memberof SystemWorkflowLogDto
     */
    recordId?: string;
    /**
     * 用户ID
     * @type {string}
     * @memberof SystemWorkflowLogDto
     */
    userid?: string;
    /**
     * 用户姓名
     * @type {string}
     * @memberof SystemWorkflowLogDto
     */
    userName?: string;
    /**
     * 审核结果
     * @type {boolean}
     * @memberof SystemWorkflowLogDto
     */
    result?: boolean;
    /**
     * 审核意见
     * @type {string}
     * @memberof SystemWorkflowLogDto
     */
    content?: string;
    /**
     * 节点代码
     * @type {string}
     * @memberof SystemWorkflowLogDto
     */
    nodeCode?: string;
}


/**
 * Check if a given object implements the SystemWorkflowLogDto interface.
 */
export function instanceOfSystemWorkflowLogDto(value: object): value is SystemWorkflowLogDto {
    return true;
}

export function SystemWorkflowLogDtoFromJSON(json: any): SystemWorkflowLogDto {
    return SystemWorkflowLogDtoFromJSONTyped(json, false);
}

export function SystemWorkflowLogDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemWorkflowLogDto {
    if (json == null) {
        return json;
    }
    return {
        
        'workflowCode': json['workflowCode'] == null ? undefined : json['workflowCode'],
        'recordId': json['recordId'] == null ? undefined : json['recordId'],
        'userid': json['userid'] == null ? undefined : json['userid'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'result': json['result'] == null ? undefined : json['result'],
        'content': json['content'] == null ? undefined : json['content'],
        'nodeCode': json['nodeCode'] == null ? undefined : json['nodeCode'],
    };
}

export function SystemWorkflowLogDtoToJSON(json: any): SystemWorkflowLogDto {
    return SystemWorkflowLogDtoToJSONTyped(json, false);
}

export function SystemWorkflowLogDtoToJSONTyped(value?: SystemWorkflowLogDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workflowCode': value['workflowCode'],
        'recordId': value['recordId'],
        'userid': value['userid'],
        'userName': value['userName'],
        'result': value['result'],
        'content': value['content'],
        'nodeCode': value['nodeCode'],
    };
}


