/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemWorkflowLogVo
 */
export interface SystemWorkflowLogVo {
    /**
     * 主键
     * @type {string}
     * @memberof SystemWorkflowLogVo
     */
    id?: string;
    /**
     * 工作流代码
     * @type {string}
     * @memberof SystemWorkflowLogVo
     */
    workflowCode?: string;
    /**
     * 审核记录ID
     * @type {string}
     * @memberof SystemWorkflowLogVo
     */
    recordId?: string;
    /**
     * 用户ID
     * @type {string}
     * @memberof SystemWorkflowLogVo
     */
    userid?: string;
    /**
     * 用户姓名
     * @type {string}
     * @memberof SystemWorkflowLogVo
     */
    userName?: string;
    /**
     * 审核结果
     * @type {boolean}
     * @memberof SystemWorkflowLogVo
     */
    result?: boolean;
    /**
     * 审核意见
     * @type {string}
     * @memberof SystemWorkflowLogVo
     */
    content?: string;
    /**
     * 节点代码
     * @type {string}
     * @memberof SystemWorkflowLogVo
     */
    nodeCode?: string;
}


/**
 * Check if a given object implements the SystemWorkflowLogVo interface.
 */
export function instanceOfSystemWorkflowLogVo(value: object): value is SystemWorkflowLogVo {
    return true;
}

export function SystemWorkflowLogVoFromJSON(json: any): SystemWorkflowLogVo {
    return SystemWorkflowLogVoFromJSONTyped(json, false);
}

export function SystemWorkflowLogVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemWorkflowLogVo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'workflowCode': json['workflowCode'] == null ? undefined : json['workflowCode'],
        'recordId': json['recordId'] == null ? undefined : json['recordId'],
        'userid': json['userid'] == null ? undefined : json['userid'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'result': json['result'] == null ? undefined : json['result'],
        'content': json['content'] == null ? undefined : json['content'],
        'nodeCode': json['nodeCode'] == null ? undefined : json['nodeCode'],
    };
}

export function SystemWorkflowLogVoToJSON(json: any): SystemWorkflowLogVo {
    return SystemWorkflowLogVoToJSONTyped(json, false);
}

export function SystemWorkflowLogVoToJSONTyped(value?: SystemWorkflowLogVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workflowCode': value['workflowCode'],
        'recordId': value['recordId'],
        'userid': value['userid'],
        'userName': value['userName'],
        'result': value['result'],
        'content': value['content'],
        'nodeCode': value['nodeCode'],
    };
}


