/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TBizInvest
 */
export interface TBizInvest {
    /**
     * 
     * @type {string}
     * @memberof TBizInvest
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TBizInvest
     */
    deleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TBizInvest
     */
    createTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TBizInvest
     */
    updateTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof TBizInvest
     */
    companyName?: string;
    /**
     * 
     * @type {number}
     * @memberof TBizInvest
     */
    zoneId?: number;
    /**
     * 
     * @type {string}
     * @memberof TBizInvest
     */
    zoneCode?: string;
    /**
     * 
     * @type {string}
     * @memberof TBizInvest
     */
    zoneName?: string;
    /**
     * 
     * @type {string}
     * @memberof TBizInvest
     */
    industryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof TBizInvest
     */
    industryName?: string;
    /**
     * 联系人
     * @type {string}
     * @memberof TBizInvest
     */
    linker?: string;
    /**
     * 
     * @type {string}
     * @memberof TBizInvest
     */
    linkerTel?: string;
    /**
     * 
     * @type {Date}
     * @memberof TBizInvest
     */
    ct?: Date;
    /**
     * 
     * @type {string}
     * @memberof TBizInvest
     */
    ip?: string;
    /**
     * 
     * @type {string}
     * @memberof TBizInvest
     */
    investDesc?: string;
    /**
     * 
     * @type {string}
     * @memberof TBizInvest
     */
    zoneTel?: string;
    /**
     * 
     * @type {number}
     * @memberof TBizInvest
     */
    status?: number;
    /**
     * 
     * @type {number}
     * @memberof TBizInvest
     */
    feebackIs?: number;
    /**
     * 
     * @type {number}
     * @memberof TBizInvest
     */
    ly?: number;
}


/**
 * Check if a given object implements the TBizInvest interface.
 */
export function instanceOfTBizInvest(value: object): value is TBizInvest {
    return true;
}

export function TBizInvestFromJSON(json: any): TBizInvest {
    return TBizInvestFromJSONTyped(json, false);
}

export function TBizInvestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TBizInvest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'createTime': json['createTime'] == null ? undefined : (new Date(json['createTime'])),
        'updateTime': json['updateTime'] == null ? undefined : (new Date(json['updateTime'])),
        'companyName': json['companyName'] == null ? undefined : json['companyName'],
        'zoneId': json['zoneId'] == null ? undefined : json['zoneId'],
        'zoneCode': json['zoneCode'] == null ? undefined : json['zoneCode'],
        'zoneName': json['zoneName'] == null ? undefined : json['zoneName'],
        'industryCode': json['industryCode'] == null ? undefined : json['industryCode'],
        'industryName': json['industryName'] == null ? undefined : json['industryName'],
        'linker': json['linker'] == null ? undefined : json['linker'],
        'linkerTel': json['linkerTel'] == null ? undefined : json['linkerTel'],
        'ct': json['ct'] == null ? undefined : (new Date(json['ct'])),
        'ip': json['ip'] == null ? undefined : json['ip'],
        'investDesc': json['investDesc'] == null ? undefined : json['investDesc'],
        'zoneTel': json['zoneTel'] == null ? undefined : json['zoneTel'],
        'status': json['status'] == null ? undefined : json['status'],
        'feebackIs': json['feebackIs'] == null ? undefined : json['feebackIs'],
        'ly': json['ly'] == null ? undefined : json['ly'],
    };
}

export function TBizInvestToJSON(json: any): TBizInvest {
    return TBizInvestToJSONTyped(json, false);
}

export function TBizInvestToJSONTyped(value?: TBizInvest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'deleted': value['deleted'],
        'createTime': value['createTime'] == null ? undefined : ((value['createTime']).toISOString()),
        'updateTime': value['updateTime'] == null ? undefined : ((value['updateTime']).toISOString()),
        'companyName': value['companyName'],
        'zoneId': value['zoneId'],
        'zoneCode': value['zoneCode'],
        'zoneName': value['zoneName'],
        'industryCode': value['industryCode'],
        'industryName': value['industryName'],
        'linker': value['linker'],
        'linkerTel': value['linkerTel'],
        'ct': value['ct'] == null ? undefined : ((value['ct']).toISOString()),
        'ip': value['ip'],
        'investDesc': value['investDesc'],
        'zoneTel': value['zoneTel'],
        'status': value['status'],
        'feebackIs': value['feebackIs'],
        'ly': value['ly'],
    };
}


