/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ZsxtApiTProjBusinessTripCreatePostRequest
 */
export interface ZsxtApiTProjBusinessTripCreatePostRequest {
    /**
     * 市（区）
     * @type {string}
     * @memberof ZsxtApiTProjBusinessTripCreatePostRequest
     */
    code: string;
    /**
     * 市（区）
     * @type {string}
     * @memberof ZsxtApiTProjBusinessTripCreatePostRequest
     */
    name: string;
    /**
     * 园区code
     * @type {string}
     * @memberof ZsxtApiTProjBusinessTripCreatePostRequest
     */
    zoneCode: string;
    /**
     * 园区名称
     * @type {string}
     * @memberof ZsxtApiTProjBusinessTripCreatePostRequest
     */
    zoneName: string;
    /**
     * 街镇
     * @type {string}
     * @memberof ZsxtApiTProjBusinessTripCreatePostRequest
     */
    townCode: string;
    /**
     * 街镇名
     * @type {string}
     * @memberof ZsxtApiTProjBusinessTripCreatePostRequest
     */
    townName: string;
    /**
     * 团组名称
     * @type {string}
     * @memberof ZsxtApiTProjBusinessTripCreatePostRequest
     */
    groupName: string;
    /**
     * 主要成员
     * @type {string}
     * @memberof ZsxtApiTProjBusinessTripCreatePostRequest
     */
    mainMembers: string;
    /**
     * 出访地（国家、地区）
     * @type {string}
     * @memberof ZsxtApiTProjBusinessTripCreatePostRequest
     */
    visitDestination: string;
    /**
     * 主要开展活动和拜访企业
     * @type {string}
     * @memberof ZsxtApiTProjBusinessTripCreatePostRequest
     */
    activitiesAndVisits: string;
    /**
     * 取得成果
     * @type {string}
     * @memberof ZsxtApiTProjBusinessTripCreatePostRequest
     */
    achievements: string;
    /**
     * 下一步打算
     * @type {string}
     * @memberof ZsxtApiTProjBusinessTripCreatePostRequest
     */
    nextPlan: string;
    /**
     * 年份
     * @type {string}
     * @memberof ZsxtApiTProjBusinessTripCreatePostRequest
     */
    year: string;
}


/**
 * Check if a given object implements the ZsxtApiTProjBusinessTripCreatePostRequest interface.
 */
export function instanceOfZsxtApiTProjBusinessTripCreatePostRequest(value: object): value is ZsxtApiTProjBusinessTripCreatePostRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('zoneCode' in value) || value['zoneCode'] === undefined) return false;
    if (!('zoneName' in value) || value['zoneName'] === undefined) return false;
    if (!('townCode' in value) || value['townCode'] === undefined) return false;
    if (!('townName' in value) || value['townName'] === undefined) return false;
    if (!('groupName' in value) || value['groupName'] === undefined) return false;
    if (!('mainMembers' in value) || value['mainMembers'] === undefined) return false;
    if (!('visitDestination' in value) || value['visitDestination'] === undefined) return false;
    if (!('activitiesAndVisits' in value) || value['activitiesAndVisits'] === undefined) return false;
    if (!('achievements' in value) || value['achievements'] === undefined) return false;
    if (!('nextPlan' in value) || value['nextPlan'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    return true;
}

export function ZsxtApiTProjBusinessTripCreatePostRequestFromJSON(json: any): ZsxtApiTProjBusinessTripCreatePostRequest {
    return ZsxtApiTProjBusinessTripCreatePostRequestFromJSONTyped(json, false);
}

export function ZsxtApiTProjBusinessTripCreatePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZsxtApiTProjBusinessTripCreatePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
        'zoneCode': json['zoneCode'],
        'zoneName': json['zoneName'],
        'townCode': json['townCode'],
        'townName': json['townName'],
        'groupName': json['groupName'],
        'mainMembers': json['mainMembers'],
        'visitDestination': json['visitDestination'],
        'activitiesAndVisits': json['activitiesAndVisits'],
        'achievements': json['achievements'],
        'nextPlan': json['nextPlan'],
        'year': json['year'],
    };
}

export function ZsxtApiTProjBusinessTripCreatePostRequestToJSON(json: any): ZsxtApiTProjBusinessTripCreatePostRequest {
    return ZsxtApiTProjBusinessTripCreatePostRequestToJSONTyped(json, false);
}

export function ZsxtApiTProjBusinessTripCreatePostRequestToJSONTyped(value?: ZsxtApiTProjBusinessTripCreatePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        'zoneCode': value['zoneCode'],
        'zoneName': value['zoneName'],
        'townCode': value['townCode'],
        'townName': value['townName'],
        'groupName': value['groupName'],
        'mainMembers': value['mainMembers'],
        'visitDestination': value['visitDestination'],
        'activitiesAndVisits': value['activitiesAndVisits'],
        'achievements': value['achievements'],
        'nextPlan': value['nextPlan'],
        'year': value['year'],
    };
}


