/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndexEnterpriseVo
 */
export interface IndexEnterpriseVo {
    /**
     * 指标名称
     * @type {string}
     * @memberof IndexEnterpriseVo
     */
    index?: string;
    /**
     * 季度
     * @type {number}
     * @memberof IndexEnterpriseVo
     */
    quarter?: number;
    /**
     * 样本单位数量
     * @type {number}
     * @memberof IndexEnterpriseVo
     */
    count?: number;
    /**
     * 营收（亿元）
     * @type {number}
     * @memberof IndexEnterpriseVo
     */
    revenue?: number;
    /**
     * 同比
     * @type {number}
     * @memberof IndexEnterpriseVo
     */
    tb?: number;
}

export function IndexEnterpriseVoFromJSON(json: any): IndexEnterpriseVo {
    return IndexEnterpriseVoFromJSONTyped(json, false);
}

export function IndexEnterpriseVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexEnterpriseVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'index': !exists(json, 'index') ? undefined : json['index'],
        'quarter': !exists(json, 'quarter') ? undefined : json['quarter'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'revenue': !exists(json, 'revenue') ? undefined : json['revenue'],
        'tb': !exists(json, 'tb') ? undefined : json['tb'],
    };
}

export function IndexEnterpriseVoToJSON(value?: IndexEnterpriseVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'index': value.index,
        'quarter': value.quarter,
        'count': value.count,
        'revenue': value.revenue,
        'tb': value.tb,
    };
}


