/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndustryChainDto
 */
export interface IndustryChainDto {
    /**
     * 产业集群分类
     * @type {string}
     * @memberof IndustryChainDto
     */
    cluster?: string;
    /**
     * 所属产业链
     * @type {string}
     * @memberof IndustryChainDto
     */
    chains?: string;
    /**
     * 企业数量
     * @type {number}
     * @memberof IndustryChainDto
     */
    companyNumber?: number;
    /**
     * 本期产值
     * @type {number}
     * @memberof IndustryChainDto
     */
    output?: number;
    /**
     * 产值增长 （%）
     * @type {number}
     * @memberof IndustryChainDto
     */
    outputIncrement?: number;
    /**
     * 本期营收（亿元）
     * @type {number}
     * @memberof IndustryChainDto
     */
    revenue?: number;
    /**
     * 营收增长(%)
     * @type {number}
     * @memberof IndustryChainDto
     */
    revenueIncrement?: number;
    /**
     * 本期利润
     * @type {number}
     * @memberof IndustryChainDto
     */
    profit?: number;
    /**
     * 利润增长（%）
     * @type {number}
     * @memberof IndustryChainDto
     */
    profitIncrement?: number;
}

export function IndustryChainDtoFromJSON(json: any): IndustryChainDto {
    return IndustryChainDtoFromJSONTyped(json, false);
}

export function IndustryChainDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndustryChainDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cluster': !exists(json, 'cluster') ? undefined : json['cluster'],
        'chains': !exists(json, 'chains') ? undefined : json['chains'],
        'companyNumber': !exists(json, 'companyNumber') ? undefined : json['companyNumber'],
        'output': !exists(json, 'output') ? undefined : json['output'],
        'outputIncrement': !exists(json, 'outputIncrement') ? undefined : json['outputIncrement'],
        'revenue': !exists(json, 'revenue') ? undefined : json['revenue'],
        'revenueIncrement': !exists(json, 'revenueIncrement') ? undefined : json['revenueIncrement'],
        'profit': !exists(json, 'profit') ? undefined : json['profit'],
        'profitIncrement': !exists(json, 'profitIncrement') ? undefined : json['profitIncrement'],
    };
}

export function IndustryChainDtoToJSON(value?: IndustryChainDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cluster': value.cluster,
        'chains': value.chains,
        'companyNumber': value.companyNumber,
        'output': value.output,
        'outputIncrement': value.outputIncrement,
        'revenue': value.revenue,
        'revenueIncrement': value.revenueIncrement,
        'profit': value.profit,
        'profitIncrement': value.profitIncrement,
    };
}


