/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrganizationVo,
    OrganizationVoFromJSON,
    OrganizationVoFromJSONTyped,
    OrganizationVoToJSON,
} from './';

/**
 * 
 * @export
 * @interface PageableResultOrganizationVo
 */
export interface PageableResultOrganizationVo {
    /**
     * 
     * @type {number}
     * @memberof PageableResultOrganizationVo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultOrganizationVo
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultOrganizationVo
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultOrganizationVo
     */
    total: number;
    /**
     * 
     * @type {Array<OrganizationVo>}
     * @memberof PageableResultOrganizationVo
     */
    records: Array<OrganizationVo>;
}

export function PageableResultOrganizationVoFromJSON(json: any): PageableResultOrganizationVo {
    return PageableResultOrganizationVoFromJSONTyped(json, false);
}

export function PageableResultOrganizationVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultOrganizationVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(OrganizationVoFromJSON)),
    };
}

export function PageableResultOrganizationVoToJSON(value?: PageableResultOrganizationVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'size': value.size,
        'totalPage': value.totalPage,
        'total': value.total,
        'records': ((value.records as Array<any>).map(OrganizationVoToJSON)),
    };
}


