/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParkGdpVo
 */
export interface ParkGdpVo {
    /**
     * 板块
     * @type {string}
     * @memberof ParkGdpVo
     */
    park: string;
    /**
     * 板块Label
     * @type {string}
     * @memberof ParkGdpVo
     */
    parkLabel: string;
    /**
     * 数量
     * @type {number}
     * @memberof ParkGdpVo
     */
    groupCount: number;
    /**
     * 实绩
     * @type {number}
     * @memberof ParkGdpVo
     */
    actualValue: number;
}

export function ParkGdpVoFromJSON(json: any): ParkGdpVo {
    return ParkGdpVoFromJSONTyped(json, false);
}

export function ParkGdpVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParkGdpVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'park': json['park'],
        'parkLabel': json['parkLabel'],
        'groupCount': json['groupCount'],
        'actualValue': json['actualValue'],
    };
}

export function ParkGdpVoToJSON(value?: ParkGdpVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'park': value.park,
        'parkLabel': value.parkLabel,
        'groupCount': value.groupCount,
        'actualValue': value.actualValue,
    };
}


