/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectDigitalInvestmentAttractingVo
 */
export interface ProjectDigitalInvestmentAttractingVo {
    /**
     * 主键
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    id?: string;
    /**
     * 项目编号
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectCode?: string;
    /**
     * 项目名称
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectName?: string;
    /**
     * 所属区县
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    district?: string;
    /**
     * 所属园区
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    park?: string;
    /**
     * 国民经济分类
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    nationalEconomicClassification?: string;
    /**
     * 统一社会信用代码
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    uscc?: string;
    /**
     * 企业名称
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    companyName?: string;
    /**
     * 企业注册资金
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    companyRegistrationFunds?: number;
    /**
     * 企业注册日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    companyRegistrationDate?: Date;
    /**
     * 项目类别
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectCategory?: string;
    /**
     * 项目属性
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectAttribute?: string;
    /**
     * 项目内容
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectContent?: string;
    /**
     * 投资标识
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investmentFlag?: string;
    /**
     * 投资标识
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investmentFlagLabel?: string;
    /**
     * 国别/地区
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    countryRegion?: string;
    /**
     * 具体国别/地区
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    specificCountryRegion?: string;
    /**
     * 投资方
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investor?: string;
    /**
     * 投资金额（亿美元/亿元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investmentAmount?: number;
    /**
     * 注册资本（亿美元/亿元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    registeredCapital?: number;
    /**
     * 洽谈进度
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    negotiationProgress?: string;
    /**
     * 国民经济行业分类
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    industryClassification?: string;
    /**
     * 当前项目进度
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    currentProjectProgress?: string;
    /**
     * 当前项目进度
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    currentProjectProgressLabel?: string;
    /**
     * 入库时间
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    entryTime?: Date;
    /**
     * 注册信息统计日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    registrationInfoStatisticsDate?: Date;
    /**
     * 佐证资料（营业执照）
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    certificateDataBusinessLicense?: string;
    /**
     * 备案（核准）项目名称
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    filingApprovalProjectName?: string;
    /**
     * 备案（核准）投资总额（亿元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    filingApprovalInvestmentTotal?: number;
    /**
     * 备案（核准）日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    filingApprovalDate?: Date;
    /**
     * 备案信息统计日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    filingInfoStatisticsDate?: Date;
    /**
     * 佐证资料（项目备案（核准）文件）
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    certificateDataProjectFilingApprovalFile?: string;
    /**
     * 是否涉及固定资产投资项目
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isFixedAssetInvestment?: boolean;
    /**
     * 是否涉及固定资产投资项目
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isFixedAssetInvestmentLabel?: string;
    /**
     * 是否涉及建设用地
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isConstructionLand?: boolean;
    /**
     * 是否涉及建设用地
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isConstructionLandLabel?: string;
    /**
     * 建设用地规划许可证编号
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    constructionLandPlanningPermitNumber?: string;
    /**
     * 取得许可证日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    permitObtainDate?: Date;
    /**
     * 完成报批统计日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    completionReportStatisticsDate?: Date;
    /**
     * 佐证资料
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    certificateData?: string;
    /**
     * 开工确认日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    startConfirmDate?: Date;
    /**
     * 竣工确认日期
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    endConfirmDate?: Date;
    /**
     * 是否为新引进企业
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isNewIntroducedEnterprise?: boolean;
    /**
     * 是否为新引进企业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isNewIntroducedEnterpriseLabel?: string;
    /**
     * 项目评级（内资、外资；金额分级）
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectRating?: string;
    /**
     * 主要投资方名称
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    mainInvestorName?: string;
    /**
     * 计划总投资（亿元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plannedTotalInvestment?: number;
    /**
     * 项目选址位置
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectLocation?: string;
    /**
     * 是否为招商会项目
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isRecruitmentFairProject?: boolean;
    /**
     * 是否为招商会项目
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isRecruitmentFairProjectLabel?: string;
    /**
     * 招商会名称
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    recruitmentFairName?: string;
    /**
     * 签约时间
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    signingTime?: Date;
    /**
     * 签约合同
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    signingContract?: string;
    /**
     * 项目总投资额（亿美元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    totalInvestmentUsd?: number;
    /**
     * 项目总投资额（亿元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    totalInvestmentCny?: number;
    /**
     * 项目来源
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectSource?: string;
    /**
     * 厂房类型
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    factoryType?: string;
    /**
     * 拟用地面积（平方米）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plannedLandArea?: number;
    /**
     * 拟租厂房面积（平方米）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plannedRentalFactoryArea?: number;
    /**
     * 拟购厂房面积（平方米）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plannedPurchaseFactoryArea?: number;
    /**
     * 预计年销量（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedAnnualSales?: number;
    /**
     * 预计年销售（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedAnnualSalesAmount?: number;
    /**
     * 预计年税收（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedAnnualTax?: number;
    /**
     * 项目类型
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectType?: string;
    /**
     * 产业大类名称
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    industryMajorClassName?: string;
    /**
     * 所属行业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    belongingIndustry?: string;
    /**
     * 投资方性质
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investorNature?: string;
    /**
     * 项目简介
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    projectProfile?: string;
    /**
     * 是否为世界500强或全球专业领域行业龙头企业
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isWorldTop500OrLeadingGlobalCompany?: boolean;
    /**
     * 是否为世界500强或全球专业领域行业龙头企业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isWorldTop500OrLeadingGlobalCompanyLabel?: string;
    /**
     * 是否为国内500强或国内行业排名前100企业
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isDomesticTop500OrTop100Company?: boolean;
    /**
     * 是否为国内500强或国内行业排名前100企业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isDomesticTop500OrTop100CompanyLabel?: string;
    /**
     * 是否为上市公司或上市辅导期企业
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isPubliclyTradedOrPreIPOCompany?: boolean;
    /**
     * 是否为上市公司或上市辅导期企业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isPubliclyTradedOrPreIPOCompanyLabel?: string;
    /**
     * 是否为瞪羚、专精特新、独角兽企业
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isUnicornStartup?: boolean;
    /**
     * 是否为瞪羚、专精特新、独角兽企业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isUnicornStartupLabel?: string;
    /**
     * 已投资项目对属地政府亩均税收（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    averageTaxPerMuOfExistingInvestment?: number;
    /**
     * 主要客户
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    majorCustomers?: string;
    /**
     * 固定资产投资（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    fixedAssetInvestment?: number;
    /**
     * 设备投资（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    equipmentInvestment?: number;
    /**
     * 计划开工时间
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plannedStartTime?: Date;
    /**
     * 计划竣工时间
     * @type {Date}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plannedEndTime?: Date;
    /**
     * 项目使用主要原、辅材料
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    mainRawMaterialsUsed?: string;
    /**
     * 主要流程工艺
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    mainProcessTechnology?: string;
    /**
     * 是否为新供地项目
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isNewSupplyLandProject?: boolean;
    /**
     * 申请用地面积（亩）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    appliedLandArea?: number;
    /**
     * 行业是否属于高新技术产业分类目录
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isHighTechIndustry?: boolean;
    /**
     * 行业是否属于高新技术产业分类目录
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isHighTechIndustryLabel?: string;
    /**
     * 是否为高技术项目
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isHighTechProject?: boolean;
    /**
     * 是否为高技术项目
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isHighTechProjectLabel?: string;
    /**
     * 是否为国家工业战略性新兴产业
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isNationalStrategicEmergingIndustry?: boolean;
    /**
     * 是否为国家工业战略性新兴产业
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isNationalStrategicEmergingIndustryLabel?: string;
    /**
     * 容积率（%）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    plotRatioPercent?: number;
    /**
     * 预期开票销售（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedInvoiceSales?: number;
    /**
     * 预期税收（万元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedTax?: number;
    /**
     * 预期用工人数（人）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedEmployeeCount?: number;
    /**
     * 固定资产投资占比（%）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    fixedAssetInvestmentPercentage?: number;
    /**
     * 投资强度（万元/千平方米）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investmentIntensity?: number;
    /**
     * 预期亩均税收（万元/千平方米）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    expectedAverageTax?: number;
    /**
     * 是否有产生废水和挥发性有机废水排放
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    wastewaterBy1?: boolean;
    /**
     * 是否有产生废水和挥发性有机废水排放
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    wastewaterBy1Label?: string;
    /**
     * 产生废水是否含氮、磷或使用高挥发性有机化合物含量涂料、油墨、胶粘剂
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    wastewaterBy2?: boolean;
    /**
     * 产生废水是否含氮、磷或使用高挥发性有机化合物含量涂料、油墨、胶粘剂
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    wastewaterBy2Label?: string;
    /**
     * 总能耗
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    totalEnergyConsumption?: number;
    /**
     * 项目是否含有研发团队、产学研合作及研发机构建设内容
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    hasRndTeamAndCooperation?: boolean;
    /**
     * 项目是否含有研发团队、产学研合作及研发机构建设内容
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    hasRndTeamAndCooperationLabel?: string;
    /**
     * 项目是否拥有相关有效发明专利
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    hasValidPatents?: boolean;
    /**
     * 项目是否拥有相关有效发明专利
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    hasValidPatentsLabel?: string;
    /**
     * 是否拟列入重点活动签约项目库
     * @type {boolean}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isListedAsKeyActivitySigningProject?: boolean;
    /**
     * 是否拟列入重点活动签约项目库
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    isListedAsKeyActivitySigningProjectLabel?: string;
    /**
     * 备注
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    remarks?: string;
    /**
     * 协议利用外资（万美元）
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    agreementForeignDirectInvestment?: number;
    /**
     * 招商项目ID
     * @type {number}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    investOnlineId?: number;
    /**
     * 在线审批ID
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    onlineApprovalId?: string;
    /**
     * 工改ID
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    constructionApprovalId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    domesticTop500OrTop100CompanyLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    nationalStrategicEmergingIndustryLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    listedAsKeyActivitySigningProjectLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    publiclyTradedOrPreIPOCompanyLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    worldTop500OrLeadingGlobalCompanyLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    newIntroducedEnterpriseLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    recruitmentFairProjectLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    fixedAssetInvestmentLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    highTechIndustryLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    highTechProjectLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    constructionLandLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDigitalInvestmentAttractingVo
     */
    unicornStartupLabel?: string;
}

export function ProjectDigitalInvestmentAttractingVoFromJSON(json: any): ProjectDigitalInvestmentAttractingVo {
    return ProjectDigitalInvestmentAttractingVoFromJSONTyped(json, false);
}

export function ProjectDigitalInvestmentAttractingVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDigitalInvestmentAttractingVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'projectCode': !exists(json, 'projectCode') ? undefined : json['projectCode'],
        'projectName': !exists(json, 'projectName') ? undefined : json['projectName'],
        'district': !exists(json, 'district') ? undefined : json['district'],
        'park': !exists(json, 'park') ? undefined : json['park'],
        'nationalEconomicClassification': !exists(json, 'nationalEconomicClassification') ? undefined : json['nationalEconomicClassification'],
        'uscc': !exists(json, 'uscc') ? undefined : json['uscc'],
        'companyName': !exists(json, 'companyName') ? undefined : json['companyName'],
        'companyRegistrationFunds': !exists(json, 'companyRegistrationFunds') ? undefined : json['companyRegistrationFunds'],
        'companyRegistrationDate': !exists(json, 'companyRegistrationDate') ? undefined : (new Date(json['companyRegistrationDate'])),
        'projectCategory': !exists(json, 'projectCategory') ? undefined : json['projectCategory'],
        'projectAttribute': !exists(json, 'projectAttribute') ? undefined : json['projectAttribute'],
        'projectContent': !exists(json, 'projectContent') ? undefined : json['projectContent'],
        'investmentFlag': !exists(json, 'investmentFlag') ? undefined : json['investmentFlag'],
        'investmentFlagLabel': !exists(json, 'investmentFlagLabel') ? undefined : json['investmentFlagLabel'],
        'countryRegion': !exists(json, 'countryRegion') ? undefined : json['countryRegion'],
        'specificCountryRegion': !exists(json, 'specificCountryRegion') ? undefined : json['specificCountryRegion'],
        'investor': !exists(json, 'investor') ? undefined : json['investor'],
        'investmentAmount': !exists(json, 'investmentAmount') ? undefined : json['investmentAmount'],
        'registeredCapital': !exists(json, 'registeredCapital') ? undefined : json['registeredCapital'],
        'negotiationProgress': !exists(json, 'negotiationProgress') ? undefined : json['negotiationProgress'],
        'industryClassification': !exists(json, 'industryClassification') ? undefined : json['industryClassification'],
        'currentProjectProgress': !exists(json, 'currentProjectProgress') ? undefined : json['currentProjectProgress'],
        'currentProjectProgressLabel': !exists(json, 'currentProjectProgressLabel') ? undefined : json['currentProjectProgressLabel'],
        'entryTime': !exists(json, 'entryTime') ? undefined : (new Date(json['entryTime'])),
        'registrationInfoStatisticsDate': !exists(json, 'registrationInfoStatisticsDate') ? undefined : (new Date(json['registrationInfoStatisticsDate'])),
        'certificateDataBusinessLicense': !exists(json, 'certificateDataBusinessLicense') ? undefined : json['certificateDataBusinessLicense'],
        'filingApprovalProjectName': !exists(json, 'filingApprovalProjectName') ? undefined : json['filingApprovalProjectName'],
        'filingApprovalInvestmentTotal': !exists(json, 'filingApprovalInvestmentTotal') ? undefined : json['filingApprovalInvestmentTotal'],
        'filingApprovalDate': !exists(json, 'filingApprovalDate') ? undefined : (new Date(json['filingApprovalDate'])),
        'filingInfoStatisticsDate': !exists(json, 'filingInfoStatisticsDate') ? undefined : (new Date(json['filingInfoStatisticsDate'])),
        'certificateDataProjectFilingApprovalFile': !exists(json, 'certificateDataProjectFilingApprovalFile') ? undefined : json['certificateDataProjectFilingApprovalFile'],
        'isFixedAssetInvestment': !exists(json, 'isFixedAssetInvestment') ? undefined : json['isFixedAssetInvestment'],
        'isFixedAssetInvestmentLabel': !exists(json, 'isFixedAssetInvestmentLabel') ? undefined : json['isFixedAssetInvestmentLabel'],
        'isConstructionLand': !exists(json, 'isConstructionLand') ? undefined : json['isConstructionLand'],
        'isConstructionLandLabel': !exists(json, 'isConstructionLandLabel') ? undefined : json['isConstructionLandLabel'],
        'constructionLandPlanningPermitNumber': !exists(json, 'constructionLandPlanningPermitNumber') ? undefined : json['constructionLandPlanningPermitNumber'],
        'permitObtainDate': !exists(json, 'permitObtainDate') ? undefined : (new Date(json['permitObtainDate'])),
        'completionReportStatisticsDate': !exists(json, 'completionReportStatisticsDate') ? undefined : (new Date(json['completionReportStatisticsDate'])),
        'certificateData': !exists(json, 'certificateData') ? undefined : json['certificateData'],
        'startConfirmDate': !exists(json, 'startConfirmDate') ? undefined : (new Date(json['startConfirmDate'])),
        'endConfirmDate': !exists(json, 'endConfirmDate') ? undefined : (new Date(json['endConfirmDate'])),
        'isNewIntroducedEnterprise': !exists(json, 'isNewIntroducedEnterprise') ? undefined : json['isNewIntroducedEnterprise'],
        'isNewIntroducedEnterpriseLabel': !exists(json, 'isNewIntroducedEnterpriseLabel') ? undefined : json['isNewIntroducedEnterpriseLabel'],
        'projectRating': !exists(json, 'projectRating') ? undefined : json['projectRating'],
        'mainInvestorName': !exists(json, 'mainInvestorName') ? undefined : json['mainInvestorName'],
        'plannedTotalInvestment': !exists(json, 'plannedTotalInvestment') ? undefined : json['plannedTotalInvestment'],
        'projectLocation': !exists(json, 'projectLocation') ? undefined : json['projectLocation'],
        'isRecruitmentFairProject': !exists(json, 'isRecruitmentFairProject') ? undefined : json['isRecruitmentFairProject'],
        'isRecruitmentFairProjectLabel': !exists(json, 'isRecruitmentFairProjectLabel') ? undefined : json['isRecruitmentFairProjectLabel'],
        'recruitmentFairName': !exists(json, 'recruitmentFairName') ? undefined : json['recruitmentFairName'],
        'signingTime': !exists(json, 'signingTime') ? undefined : (new Date(json['signingTime'])),
        'signingContract': !exists(json, 'signingContract') ? undefined : json['signingContract'],
        'totalInvestmentUsd': !exists(json, 'totalInvestmentUsd') ? undefined : json['totalInvestmentUsd'],
        'totalInvestmentCny': !exists(json, 'totalInvestmentCny') ? undefined : json['totalInvestmentCny'],
        'projectSource': !exists(json, 'projectSource') ? undefined : json['projectSource'],
        'factoryType': !exists(json, 'factoryType') ? undefined : json['factoryType'],
        'plannedLandArea': !exists(json, 'plannedLandArea') ? undefined : json['plannedLandArea'],
        'plannedRentalFactoryArea': !exists(json, 'plannedRentalFactoryArea') ? undefined : json['plannedRentalFactoryArea'],
        'plannedPurchaseFactoryArea': !exists(json, 'plannedPurchaseFactoryArea') ? undefined : json['plannedPurchaseFactoryArea'],
        'expectedAnnualSales': !exists(json, 'expectedAnnualSales') ? undefined : json['expectedAnnualSales'],
        'expectedAnnualSalesAmount': !exists(json, 'expectedAnnualSalesAmount') ? undefined : json['expectedAnnualSalesAmount'],
        'expectedAnnualTax': !exists(json, 'expectedAnnualTax') ? undefined : json['expectedAnnualTax'],
        'projectType': !exists(json, 'projectType') ? undefined : json['projectType'],
        'industryMajorClassName': !exists(json, 'industryMajorClassName') ? undefined : json['industryMajorClassName'],
        'belongingIndustry': !exists(json, 'belongingIndustry') ? undefined : json['belongingIndustry'],
        'investorNature': !exists(json, 'investorNature') ? undefined : json['investorNature'],
        'projectProfile': !exists(json, 'projectProfile') ? undefined : json['projectProfile'],
        'isWorldTop500OrLeadingGlobalCompany': !exists(json, 'isWorldTop500OrLeadingGlobalCompany') ? undefined : json['isWorldTop500OrLeadingGlobalCompany'],
        'isWorldTop500OrLeadingGlobalCompanyLabel': !exists(json, 'isWorldTop500OrLeadingGlobalCompanyLabel') ? undefined : json['isWorldTop500OrLeadingGlobalCompanyLabel'],
        'isDomesticTop500OrTop100Company': !exists(json, 'isDomesticTop500OrTop100Company') ? undefined : json['isDomesticTop500OrTop100Company'],
        'isDomesticTop500OrTop100CompanyLabel': !exists(json, 'isDomesticTop500OrTop100CompanyLabel') ? undefined : json['isDomesticTop500OrTop100CompanyLabel'],
        'isPubliclyTradedOrPreIPOCompany': !exists(json, 'isPubliclyTradedOrPreIPOCompany') ? undefined : json['isPubliclyTradedOrPreIPOCompany'],
        'isPubliclyTradedOrPreIPOCompanyLabel': !exists(json, 'isPubliclyTradedOrPreIPOCompanyLabel') ? undefined : json['isPubliclyTradedOrPreIPOCompanyLabel'],
        'isUnicornStartup': !exists(json, 'isUnicornStartup') ? undefined : json['isUnicornStartup'],
        'isUnicornStartupLabel': !exists(json, 'isUnicornStartupLabel') ? undefined : json['isUnicornStartupLabel'],
        'averageTaxPerMuOfExistingInvestment': !exists(json, 'averageTaxPerMuOfExistingInvestment') ? undefined : json['averageTaxPerMuOfExistingInvestment'],
        'majorCustomers': !exists(json, 'majorCustomers') ? undefined : json['majorCustomers'],
        'fixedAssetInvestment': !exists(json, 'fixedAssetInvestment') ? undefined : json['fixedAssetInvestment'],
        'equipmentInvestment': !exists(json, 'equipmentInvestment') ? undefined : json['equipmentInvestment'],
        'plannedStartTime': !exists(json, 'plannedStartTime') ? undefined : (new Date(json['plannedStartTime'])),
        'plannedEndTime': !exists(json, 'plannedEndTime') ? undefined : (new Date(json['plannedEndTime'])),
        'mainRawMaterialsUsed': !exists(json, 'mainRawMaterialsUsed') ? undefined : json['mainRawMaterialsUsed'],
        'mainProcessTechnology': !exists(json, 'mainProcessTechnology') ? undefined : json['mainProcessTechnology'],
        'isNewSupplyLandProject': !exists(json, 'isNewSupplyLandProject') ? undefined : json['isNewSupplyLandProject'],
        'appliedLandArea': !exists(json, 'appliedLandArea') ? undefined : json['appliedLandArea'],
        'isHighTechIndustry': !exists(json, 'isHighTechIndustry') ? undefined : json['isHighTechIndustry'],
        'isHighTechIndustryLabel': !exists(json, 'isHighTechIndustryLabel') ? undefined : json['isHighTechIndustryLabel'],
        'isHighTechProject': !exists(json, 'isHighTechProject') ? undefined : json['isHighTechProject'],
        'isHighTechProjectLabel': !exists(json, 'isHighTechProjectLabel') ? undefined : json['isHighTechProjectLabel'],
        'isNationalStrategicEmergingIndustry': !exists(json, 'isNationalStrategicEmergingIndustry') ? undefined : json['isNationalStrategicEmergingIndustry'],
        'isNationalStrategicEmergingIndustryLabel': !exists(json, 'isNationalStrategicEmergingIndustryLabel') ? undefined : json['isNationalStrategicEmergingIndustryLabel'],
        'plotRatioPercent': !exists(json, 'plotRatioPercent') ? undefined : json['plotRatioPercent'],
        'expectedInvoiceSales': !exists(json, 'expectedInvoiceSales') ? undefined : json['expectedInvoiceSales'],
        'expectedTax': !exists(json, 'expectedTax') ? undefined : json['expectedTax'],
        'expectedEmployeeCount': !exists(json, 'expectedEmployeeCount') ? undefined : json['expectedEmployeeCount'],
        'fixedAssetInvestmentPercentage': !exists(json, 'fixedAssetInvestmentPercentage') ? undefined : json['fixedAssetInvestmentPercentage'],
        'investmentIntensity': !exists(json, 'investmentIntensity') ? undefined : json['investmentIntensity'],
        'expectedAverageTax': !exists(json, 'expectedAverageTax') ? undefined : json['expectedAverageTax'],
        'wastewaterBy1': !exists(json, 'wastewaterBy1') ? undefined : json['wastewaterBy1'],
        'wastewaterBy1Label': !exists(json, 'wastewaterBy1Label') ? undefined : json['wastewaterBy1Label'],
        'wastewaterBy2': !exists(json, 'wastewaterBy2') ? undefined : json['wastewaterBy2'],
        'wastewaterBy2Label': !exists(json, 'wastewaterBy2Label') ? undefined : json['wastewaterBy2Label'],
        'totalEnergyConsumption': !exists(json, 'totalEnergyConsumption') ? undefined : json['totalEnergyConsumption'],
        'hasRndTeamAndCooperation': !exists(json, 'hasRndTeamAndCooperation') ? undefined : json['hasRndTeamAndCooperation'],
        'hasRndTeamAndCooperationLabel': !exists(json, 'hasRndTeamAndCooperationLabel') ? undefined : json['hasRndTeamAndCooperationLabel'],
        'hasValidPatents': !exists(json, 'hasValidPatents') ? undefined : json['hasValidPatents'],
        'hasValidPatentsLabel': !exists(json, 'hasValidPatentsLabel') ? undefined : json['hasValidPatentsLabel'],
        'isListedAsKeyActivitySigningProject': !exists(json, 'isListedAsKeyActivitySigningProject') ? undefined : json['isListedAsKeyActivitySigningProject'],
        'isListedAsKeyActivitySigningProjectLabel': !exists(json, 'isListedAsKeyActivitySigningProjectLabel') ? undefined : json['isListedAsKeyActivitySigningProjectLabel'],
        'remarks': !exists(json, 'remarks') ? undefined : json['remarks'],
        'agreementForeignDirectInvestment': !exists(json, 'agreementForeignDirectInvestment') ? undefined : json['agreementForeignDirectInvestment'],
        'investOnlineId': !exists(json, 'investOnlineId') ? undefined : json['investOnlineId'],
        'onlineApprovalId': !exists(json, 'onlineApprovalId') ? undefined : json['onlineApprovalId'],
        'constructionApprovalId': !exists(json, 'constructionApprovalId') ? undefined : json['constructionApprovalId'],
        'domesticTop500OrTop100CompanyLabel': !exists(json, 'domesticTop500OrTop100CompanyLabel') ? undefined : json['domesticTop500OrTop100CompanyLabel'],
        'nationalStrategicEmergingIndustryLabel': !exists(json, 'nationalStrategicEmergingIndustryLabel') ? undefined : json['nationalStrategicEmergingIndustryLabel'],
        'listedAsKeyActivitySigningProjectLabel': !exists(json, 'listedAsKeyActivitySigningProjectLabel') ? undefined : json['listedAsKeyActivitySigningProjectLabel'],
        'publiclyTradedOrPreIPOCompanyLabel': !exists(json, 'publiclyTradedOrPreIPOCompanyLabel') ? undefined : json['publiclyTradedOrPreIPOCompanyLabel'],
        'worldTop500OrLeadingGlobalCompanyLabel': !exists(json, 'worldTop500OrLeadingGlobalCompanyLabel') ? undefined : json['worldTop500OrLeadingGlobalCompanyLabel'],
        'newIntroducedEnterpriseLabel': !exists(json, 'newIntroducedEnterpriseLabel') ? undefined : json['newIntroducedEnterpriseLabel'],
        'recruitmentFairProjectLabel': !exists(json, 'recruitmentFairProjectLabel') ? undefined : json['recruitmentFairProjectLabel'],
        'fixedAssetInvestmentLabel': !exists(json, 'fixedAssetInvestmentLabel') ? undefined : json['fixedAssetInvestmentLabel'],
        'highTechIndustryLabel': !exists(json, 'highTechIndustryLabel') ? undefined : json['highTechIndustryLabel'],
        'highTechProjectLabel': !exists(json, 'highTechProjectLabel') ? undefined : json['highTechProjectLabel'],
        'constructionLandLabel': !exists(json, 'constructionLandLabel') ? undefined : json['constructionLandLabel'],
        'unicornStartupLabel': !exists(json, 'unicornStartupLabel') ? undefined : json['unicornStartupLabel'],
    };
}

export function ProjectDigitalInvestmentAttractingVoToJSON(value?: ProjectDigitalInvestmentAttractingVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'projectCode': value.projectCode,
        'projectName': value.projectName,
        'district': value.district,
        'park': value.park,
        'nationalEconomicClassification': value.nationalEconomicClassification,
        'uscc': value.uscc,
        'companyName': value.companyName,
        'companyRegistrationFunds': value.companyRegistrationFunds,
        'companyRegistrationDate': value.companyRegistrationDate === undefined ? undefined : (value.companyRegistrationDate.toISOString().substr(0,10)),
        'projectCategory': value.projectCategory,
        'projectAttribute': value.projectAttribute,
        'projectContent': value.projectContent,
        'investmentFlag': value.investmentFlag,
        'investmentFlagLabel': value.investmentFlagLabel,
        'countryRegion': value.countryRegion,
        'specificCountryRegion': value.specificCountryRegion,
        'investor': value.investor,
        'investmentAmount': value.investmentAmount,
        'registeredCapital': value.registeredCapital,
        'negotiationProgress': value.negotiationProgress,
        'industryClassification': value.industryClassification,
        'currentProjectProgress': value.currentProjectProgress,
        'currentProjectProgressLabel': value.currentProjectProgressLabel,
        'entryTime': value.entryTime === undefined ? undefined : (value.entryTime.toISOString()),
        'registrationInfoStatisticsDate': value.registrationInfoStatisticsDate === undefined ? undefined : (value.registrationInfoStatisticsDate.toISOString().substr(0,10)),
        'certificateDataBusinessLicense': value.certificateDataBusinessLicense,
        'filingApprovalProjectName': value.filingApprovalProjectName,
        'filingApprovalInvestmentTotal': value.filingApprovalInvestmentTotal,
        'filingApprovalDate': value.filingApprovalDate === undefined ? undefined : (value.filingApprovalDate.toISOString().substr(0,10)),
        'filingInfoStatisticsDate': value.filingInfoStatisticsDate === undefined ? undefined : (value.filingInfoStatisticsDate.toISOString().substr(0,10)),
        'certificateDataProjectFilingApprovalFile': value.certificateDataProjectFilingApprovalFile,
        'isFixedAssetInvestment': value.isFixedAssetInvestment,
        'isFixedAssetInvestmentLabel': value.isFixedAssetInvestmentLabel,
        'isConstructionLand': value.isConstructionLand,
        'isConstructionLandLabel': value.isConstructionLandLabel,
        'constructionLandPlanningPermitNumber': value.constructionLandPlanningPermitNumber,
        'permitObtainDate': value.permitObtainDate === undefined ? undefined : (value.permitObtainDate.toISOString().substr(0,10)),
        'completionReportStatisticsDate': value.completionReportStatisticsDate === undefined ? undefined : (value.completionReportStatisticsDate.toISOString().substr(0,10)),
        'certificateData': value.certificateData,
        'startConfirmDate': value.startConfirmDate === undefined ? undefined : (value.startConfirmDate.toISOString().substr(0,10)),
        'endConfirmDate': value.endConfirmDate === undefined ? undefined : (value.endConfirmDate.toISOString().substr(0,10)),
        'isNewIntroducedEnterprise': value.isNewIntroducedEnterprise,
        'isNewIntroducedEnterpriseLabel': value.isNewIntroducedEnterpriseLabel,
        'projectRating': value.projectRating,
        'mainInvestorName': value.mainInvestorName,
        'plannedTotalInvestment': value.plannedTotalInvestment,
        'projectLocation': value.projectLocation,
        'isRecruitmentFairProject': value.isRecruitmentFairProject,
        'isRecruitmentFairProjectLabel': value.isRecruitmentFairProjectLabel,
        'recruitmentFairName': value.recruitmentFairName,
        'signingTime': value.signingTime === undefined ? undefined : (value.signingTime.toISOString().substr(0,10)),
        'signingContract': value.signingContract,
        'totalInvestmentUsd': value.totalInvestmentUsd,
        'totalInvestmentCny': value.totalInvestmentCny,
        'projectSource': value.projectSource,
        'factoryType': value.factoryType,
        'plannedLandArea': value.plannedLandArea,
        'plannedRentalFactoryArea': value.plannedRentalFactoryArea,
        'plannedPurchaseFactoryArea': value.plannedPurchaseFactoryArea,
        'expectedAnnualSales': value.expectedAnnualSales,
        'expectedAnnualSalesAmount': value.expectedAnnualSalesAmount,
        'expectedAnnualTax': value.expectedAnnualTax,
        'projectType': value.projectType,
        'industryMajorClassName': value.industryMajorClassName,
        'belongingIndustry': value.belongingIndustry,
        'investorNature': value.investorNature,
        'projectProfile': value.projectProfile,
        'isWorldTop500OrLeadingGlobalCompany': value.isWorldTop500OrLeadingGlobalCompany,
        'isWorldTop500OrLeadingGlobalCompanyLabel': value.isWorldTop500OrLeadingGlobalCompanyLabel,
        'isDomesticTop500OrTop100Company': value.isDomesticTop500OrTop100Company,
        'isDomesticTop500OrTop100CompanyLabel': value.isDomesticTop500OrTop100CompanyLabel,
        'isPubliclyTradedOrPreIPOCompany': value.isPubliclyTradedOrPreIPOCompany,
        'isPubliclyTradedOrPreIPOCompanyLabel': value.isPubliclyTradedOrPreIPOCompanyLabel,
        'isUnicornStartup': value.isUnicornStartup,
        'isUnicornStartupLabel': value.isUnicornStartupLabel,
        'averageTaxPerMuOfExistingInvestment': value.averageTaxPerMuOfExistingInvestment,
        'majorCustomers': value.majorCustomers,
        'fixedAssetInvestment': value.fixedAssetInvestment,
        'equipmentInvestment': value.equipmentInvestment,
        'plannedStartTime': value.plannedStartTime === undefined ? undefined : (value.plannedStartTime.toISOString().substr(0,10)),
        'plannedEndTime': value.plannedEndTime === undefined ? undefined : (value.plannedEndTime.toISOString().substr(0,10)),
        'mainRawMaterialsUsed': value.mainRawMaterialsUsed,
        'mainProcessTechnology': value.mainProcessTechnology,
        'isNewSupplyLandProject': value.isNewSupplyLandProject,
        'appliedLandArea': value.appliedLandArea,
        'isHighTechIndustry': value.isHighTechIndustry,
        'isHighTechIndustryLabel': value.isHighTechIndustryLabel,
        'isHighTechProject': value.isHighTechProject,
        'isHighTechProjectLabel': value.isHighTechProjectLabel,
        'isNationalStrategicEmergingIndustry': value.isNationalStrategicEmergingIndustry,
        'isNationalStrategicEmergingIndustryLabel': value.isNationalStrategicEmergingIndustryLabel,
        'plotRatioPercent': value.plotRatioPercent,
        'expectedInvoiceSales': value.expectedInvoiceSales,
        'expectedTax': value.expectedTax,
        'expectedEmployeeCount': value.expectedEmployeeCount,
        'fixedAssetInvestmentPercentage': value.fixedAssetInvestmentPercentage,
        'investmentIntensity': value.investmentIntensity,
        'expectedAverageTax': value.expectedAverageTax,
        'wastewaterBy1': value.wastewaterBy1,
        'wastewaterBy1Label': value.wastewaterBy1Label,
        'wastewaterBy2': value.wastewaterBy2,
        'wastewaterBy2Label': value.wastewaterBy2Label,
        'totalEnergyConsumption': value.totalEnergyConsumption,
        'hasRndTeamAndCooperation': value.hasRndTeamAndCooperation,
        'hasRndTeamAndCooperationLabel': value.hasRndTeamAndCooperationLabel,
        'hasValidPatents': value.hasValidPatents,
        'hasValidPatentsLabel': value.hasValidPatentsLabel,
        'isListedAsKeyActivitySigningProject': value.isListedAsKeyActivitySigningProject,
        'isListedAsKeyActivitySigningProjectLabel': value.isListedAsKeyActivitySigningProjectLabel,
        'remarks': value.remarks,
        'agreementForeignDirectInvestment': value.agreementForeignDirectInvestment,
        'investOnlineId': value.investOnlineId,
        'onlineApprovalId': value.onlineApprovalId,
        'constructionApprovalId': value.constructionApprovalId,
        'domesticTop500OrTop100CompanyLabel': value.domesticTop500OrTop100CompanyLabel,
        'nationalStrategicEmergingIndustryLabel': value.nationalStrategicEmergingIndustryLabel,
        'listedAsKeyActivitySigningProjectLabel': value.listedAsKeyActivitySigningProjectLabel,
        'publiclyTradedOrPreIPOCompanyLabel': value.publiclyTradedOrPreIPOCompanyLabel,
        'worldTop500OrLeadingGlobalCompanyLabel': value.worldTop500OrLeadingGlobalCompanyLabel,
        'newIntroducedEnterpriseLabel': value.newIntroducedEnterpriseLabel,
        'recruitmentFairProjectLabel': value.recruitmentFairProjectLabel,
        'fixedAssetInvestmentLabel': value.fixedAssetInvestmentLabel,
        'highTechIndustryLabel': value.highTechIndustryLabel,
        'highTechProjectLabel': value.highTechProjectLabel,
        'constructionLandLabel': value.constructionLandLabel,
        'unicornStartupLabel': value.unicornStartupLabel,
    };
}


