/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectInvestmentAttractingCountVo
 */
export interface ProjectInvestmentAttractingCountVo {
    /**
     * 当前项目进度
     * @type {string}
     * @memberof ProjectInvestmentAttractingCountVo
     */
    currentProjectProgress?: string;
    /**
     * 当前项目进度
     * @type {string}
     * @memberof ProjectInvestmentAttractingCountVo
     */
    currentProjectProgressLabel?: string;
    /**
     * 数量
     * @type {number}
     * @memberof ProjectInvestmentAttractingCountVo
     */
    count: number;
}

export function ProjectInvestmentAttractingCountVoFromJSON(json: any): ProjectInvestmentAttractingCountVo {
    return ProjectInvestmentAttractingCountVoFromJSONTyped(json, false);
}

export function ProjectInvestmentAttractingCountVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectInvestmentAttractingCountVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentProjectProgress': !exists(json, 'currentProjectProgress') ? undefined : json['currentProjectProgress'],
        'currentProjectProgressLabel': !exists(json, 'currentProjectProgressLabel') ? undefined : json['currentProjectProgressLabel'],
        'count': json['count'],
    };
}

export function ProjectInvestmentAttractingCountVoToJSON(value?: ProjectInvestmentAttractingCountVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currentProjectProgress': value.currentProjectProgress,
        'currentProjectProgressLabel': value.currentProjectProgressLabel,
        'count': value.count,
    };
}


