/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleValueDtoBoolean
 */
export interface SimpleValueDtoBoolean {
    /**
     * 
     * @type {boolean}
     * @memberof SimpleValueDtoBoolean
     */
    value: boolean;
}

export function SimpleValueDtoBooleanFromJSON(json: any): SimpleValueDtoBoolean {
    return SimpleValueDtoBooleanFromJSONTyped(json, false);
}

export function SimpleValueDtoBooleanFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleValueDtoBoolean {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function SimpleValueDtoBooleanToJSON(value?: SimpleValueDtoBoolean | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}


