/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemDictVo
 */
export interface SystemDictVo {
    /**
     * 字典代码
     * @type {string}
     * @memberof SystemDictVo
     */
    code: string;
    /**
     * 字典名称
     * @type {string}
     * @memberof SystemDictVo
     */
    label: string;
    /**
     * 是否启用
     * @type {boolean}
     * @memberof SystemDictVo
     */
    enabled: boolean;
    /**
     * 排序
     * @type {number}
     * @memberof SystemDictVo
     */
    sort: number;
}

export function SystemDictVoFromJSON(json: any): SystemDictVo {
    return SystemDictVoFromJSONTyped(json, false);
}

export function SystemDictVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemDictVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'label': json['label'],
        'enabled': json['enabled'],
        'sort': json['sort'],
    };
}

export function SystemDictVoToJSON(value?: SystemDictVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'label': value.label,
        'enabled': value.enabled,
        'sort': value.sort,
    };
}


