server:
  prefer-ip-prefix: '192.177.35.'

spring:
  datasource:
    url: jdbc:mysql://192.177.35.97:3306/test
    username: test
    password: test
  data:
    redis:
      host: 192.177.35.97
      password: enterprise-lifecycle
      database: 1

springdoc:
  api-docs:
    enabled: true

mybatis-flex:
  datasource:
    internet-supervise:
      url: jdbc:oracle:thin:@//172.22.59.7:1521/ythqzj
      username: sjzt_qysmzq
      password: sJZt_QysMzq@0417
      read-only: false
    invest-online:
      url: jdbc:mysql://192.177.35.97:3306/invest_online
      username: enterprise_lifecycle
      password: enterprise_lifecycle
      # url: jdbc:mysql://172.22.26.71:54930/invest_online
      # username: zs_test
      # password: Dj3wGnmur5SV
      read-only: true

s3:
  provider: obs
  endpoint: obsv3.tz-telecom-zww.tztelecom.com
  bucket: qyqsmzq
  access-key: 'WEROGAUDXFYPQDCKLG8I'
  secret-key: 'mBoSSdid8hRsL3iOlfPwK8gV5zRmRR0vAKIEEKCP'
