server:
  prefer-ip-prefix: '127.0.0.'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enterprise_lifecycle
    username: enterprise_lifecycle
    password: enterprise_lifecycle
  data:
    redis:
      host: localhost
      password: enterprise-lifecycle

springdoc:
  api-docs:
    enabled: true

mybatis-flex:
  datasource:
    internet-supervise:
      url: jdbc:oracle:thin:@//localhost:1521/ythqzj
      username: sjzt_qysmzq
      password: sJZt_QysMzq@0417
      read-only: false
    invest-online:
      url: jdbc:mysql://localhost:3306/invest_online
      username: enterprise_lifecycle
      password: enterprise_lifecycle
      # url: jdbc:mysql://localhost:3306/invest_online
      # username: zs_test
      # password: Dj3wGnmur5SV
      read-only: true

s3:
  provider: obs
  endpoint: http://localhost:9000
  bucket: qyqsmzq
  access-key: 'WEROGAUDXFYPQDCKLG8I'
  secret-key: 'mBoSSdid8hRsL3iOlfPwK8gV5zRmRR0vAKIEEKCP'

feign:
  open-api: http://localhost:9093
