/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndustryChainVo
 */
export interface IndustryChainVo {
    /**
     * 所属产业链
     * @type {string}
     * @memberof IndustryChainVo
     */
    chains?: string;
    /**
     * 企业数量
     * @type {number}
     * @memberof IndustryChainVo
     */
    companyNumber?: number;
    /**
     * 本期产值
     * @type {number}
     * @memberof IndustryChainVo
     */
    output?: number;
    /**
     * 产值增长 （%）
     * @type {number}
     * @memberof IndustryChainVo
     */
    outputIncrement?: number;
    /**
     * 本期营收（亿元）
     * @type {number}
     * @memberof IndustryChainVo
     */
    revenue?: number;
    /**
     * 营收增长(%)
     * @type {number}
     * @memberof IndustryChainVo
     */
    revenueIncrement?: number;
    /**
     * 本期利润
     * @type {number}
     * @memberof IndustryChainVo
     */
    profit?: number;
    /**
     * 利润增长（%）
     * @type {number}
     * @memberof IndustryChainVo
     */
    profitIncrement?: number;
}


/**
 * Check if a given object implements the IndustryChainVo interface.
 */
export function instanceOfIndustryChainVo(value: object): value is IndustryChainVo {
    return true;
}

export function IndustryChainVoFromJSON(json: any): IndustryChainVo {
    return IndustryChainVoFromJSONTyped(json, false);
}

export function IndustryChainVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndustryChainVo {
    if (json == null) {
        return json;
    }
    return {
        
        'chains': json['chains'] == null ? undefined : json['chains'],
        'companyNumber': json['companyNumber'] == null ? undefined : json['companyNumber'],
        'output': json['output'] == null ? undefined : json['output'],
        'outputIncrement': json['outputIncrement'] == null ? undefined : json['outputIncrement'],
        'revenue': json['revenue'] == null ? undefined : json['revenue'],
        'revenueIncrement': json['revenueIncrement'] == null ? undefined : json['revenueIncrement'],
        'profit': json['profit'] == null ? undefined : json['profit'],
        'profitIncrement': json['profitIncrement'] == null ? undefined : json['profitIncrement'],
    };
}

export function IndustryChainVoToJSON(json: any): IndustryChainVo {
    return IndustryChainVoToJSONTyped(json, false);
}

export function IndustryChainVoToJSONTyped(value?: IndustryChainVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chains': value['chains'],
        'companyNumber': value['companyNumber'],
        'output': value['output'],
        'outputIncrement': value['outputIncrement'],
        'revenue': value['revenue'],
        'revenueIncrement': value['revenueIncrement'],
        'profit': value['profit'],
        'profitIncrement': value['profitIncrement'],
    };
}


