/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { ProjectOnlineApprovalVo } from './ProjectOnlineApprovalVo';
import {
    ProjectOnlineApprovalVoFromJSON,
    ProjectOnlineApprovalVoFromJSONTyped,
    ProjectOnlineApprovalVoToJSON,
    ProjectOnlineApprovalVoToJSONTyped,
} from './ProjectOnlineApprovalVo';

/**
 * 
 * @export
 * @interface PageableResultProjectOnlineApprovalVo
 */
export interface PageableResultProjectOnlineApprovalVo {
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectOnlineApprovalVo
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectOnlineApprovalVo
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectOnlineApprovalVo
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultProjectOnlineApprovalVo
     */
    total: number;
    /**
     * 
     * @type {Array<ProjectOnlineApprovalVo>}
     * @memberof PageableResultProjectOnlineApprovalVo
     */
    records: Array<ProjectOnlineApprovalVo>;
}


/**
 * Check if a given object implements the PageableResultProjectOnlineApprovalVo interface.
 */
export function instanceOfPageableResultProjectOnlineApprovalVo(value: object): value is PageableResultProjectOnlineApprovalVo {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultProjectOnlineApprovalVoFromJSON(json: any): PageableResultProjectOnlineApprovalVo {
    return PageableResultProjectOnlineApprovalVoFromJSONTyped(json, false);
}

export function PageableResultProjectOnlineApprovalVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultProjectOnlineApprovalVo {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(ProjectOnlineApprovalVoFromJSON)),
    };
}

export function PageableResultProjectOnlineApprovalVoToJSON(json: any): PageableResultProjectOnlineApprovalVo {
    return PageableResultProjectOnlineApprovalVoToJSONTyped(json, false);
}

export function PageableResultProjectOnlineApprovalVoToJSONTyped(value?: PageableResultProjectOnlineApprovalVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(ProjectOnlineApprovalVoToJSON)),
    };
}


