/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { FormIndicatorRecord } from './FormIndicatorRecord';
import {
    FormIndicatorRecordFromJSON,
    FormIndicatorRecordFromJSONTyped,
    FormIndicatorRecordToJSON,
    FormIndicatorRecordToJSONTyped,
} from './FormIndicatorRecord';

/**
 * 
 * @export
 * @interface PageableResultFormIndicatorRecord
 */
export interface PageableResultFormIndicatorRecord {
    /**
     * 
     * @type {number}
     * @memberof PageableResultFormIndicatorRecord
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultFormIndicatorRecord
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultFormIndicatorRecord
     */
    totalPage: number;
    /**
     * 
     * @type {number}
     * @memberof PageableResultFormIndicatorRecord
     */
    total: number;
    /**
     * 
     * @type {Array<FormIndicatorRecord>}
     * @memberof PageableResultFormIndicatorRecord
     */
    records: Array<FormIndicatorRecord>;
}


/**
 * Check if a given object implements the PageableResultFormIndicatorRecord interface.
 */
export function instanceOfPageableResultFormIndicatorRecord(value: object): value is PageableResultFormIndicatorRecord {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function PageableResultFormIndicatorRecordFromJSON(json: any): PageableResultFormIndicatorRecord {
    return PageableResultFormIndicatorRecordFromJSONTyped(json, false);
}

export function PageableResultFormIndicatorRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageableResultFormIndicatorRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'size': json['size'],
        'totalPage': json['totalPage'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(FormIndicatorRecordFromJSON)),
    };
}

export function PageableResultFormIndicatorRecordToJSON(json: any): PageableResultFormIndicatorRecord {
    return PageableResultFormIndicatorRecordToJSONTyped(json, false);
}

export function PageableResultFormIndicatorRecordToJSONTyped(value?: PageableResultFormIndicatorRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'size': value['size'],
        'totalPage': value['totalPage'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(FormIndicatorRecordToJSON)),
    };
}


