/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectInvestmentVo
 */
export interface ProjectInvestmentVo {
    /**
     * 年份
     * @type {number}
     * @memberof ProjectInvestmentVo
     */
    year: number;
    /**
     * 项目总数
     * @type {number}
     * @memberof ProjectInvestmentVo
     */
    projectTotal: number;
    /**
     * 地区项目总数
     * @type {number}
     * @memberof ProjectInvestmentVo
     */
    areaTotal: number;
    /**
     * 地区
     * @type {string}
     * @memberof ProjectInvestmentVo
     */
    area: string;
    /**
     * 占比
     * @type {number}
     * @memberof ProjectInvestmentVo
     */
    ratio: number;
}


/**
 * Check if a given object implements the ProjectInvestmentVo interface.
 */
export function instanceOfProjectInvestmentVo(value: object): value is ProjectInvestmentVo {
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('projectTotal' in value) || value['projectTotal'] === undefined) return false;
    if (!('areaTotal' in value) || value['areaTotal'] === undefined) return false;
    if (!('area' in value) || value['area'] === undefined) return false;
    if (!('ratio' in value) || value['ratio'] === undefined) return false;
    return true;
}

export function ProjectInvestmentVoFromJSON(json: any): ProjectInvestmentVo {
    return ProjectInvestmentVoFromJSONTyped(json, false);
}

export function ProjectInvestmentVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectInvestmentVo {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'],
        'projectTotal': json['projectTotal'],
        'areaTotal': json['areaTotal'],
        'area': json['area'],
        'ratio': json['ratio'],
    };
}

export function ProjectInvestmentVoToJSON(json: any): ProjectInvestmentVo {
    return ProjectInvestmentVoToJSONTyped(json, false);
}

export function ProjectInvestmentVoToJSONTyped(value?: ProjectInvestmentVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'projectTotal': value['projectTotal'],
        'areaTotal': value['areaTotal'],
        'area': value['area'],
        'ratio': value['ratio'],
    };
}


