/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { mapValues } from '../runtime';
import type { AreaVo } from './AreaVo';
import {
    AreaVoFromJSON,
    AreaVoFromJSONTyped,
    AreaVoToJSON,
    AreaVoToJSONTyped,
} from './AreaVo';

/**
 * 
 * @export
 * @interface UserDataGrantsVo
 */
export interface UserDataGrantsVo {
    /**
     * 用户ID
     * @type {string}
     * @memberof UserDataGrantsVo
     */
    userid: string;
    /**
     * 区划
     * @type {Array<AreaVo>}
     * @memberof UserDataGrantsVo
     */
    areas: Array<AreaVo>;
    /**
     * Cascader数据
     * @type {Array<Array<string>>}
     * @memberof UserDataGrantsVo
     */
    data4cascader: Array<Array<string>>;
}


/**
 * Check if a given object implements the UserDataGrantsVo interface.
 */
export function instanceOfUserDataGrantsVo(value: object): value is UserDataGrantsVo {
    if (!('userid' in value) || value['userid'] === undefined) return false;
    if (!('areas' in value) || value['areas'] === undefined) return false;
    if (!('data4cascader' in value) || value['data4cascader'] === undefined) return false;
    return true;
}

export function UserDataGrantsVoFromJSON(json: any): UserDataGrantsVo {
    return UserDataGrantsVoFromJSONTyped(json, false);
}

export function UserDataGrantsVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDataGrantsVo {
    if (json == null) {
        return json;
    }
    return {
        
        'userid': json['userid'],
        'areas': ((json['areas'] as Array<any>).map(AreaVoFromJSON)),
        'data4cascader': json['data4cascader'],
    };
}

export function UserDataGrantsVoToJSON(json: any): UserDataGrantsVo {
    return UserDataGrantsVoToJSONTyped(json, false);
}

export function UserDataGrantsVoToJSONTyped(value?: UserDataGrantsVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userid': value['userid'],
        'areas': ((value['areas'] as Array<any>).map(AreaVoToJSON)),
        'data4cascader': value['data4cascader'],
    };
}


