drop table if exists project_digital_investment_attracting;
create table project_digital_investment_attracting
(
    id                                            char(20)              not null comment '主键' primary key,
    deleted                                       boolean default false not null comment '逻辑删除',
    create_time                                   datetime              not null comment '创建时间',
    update_time                                   datetime              not null comment '修改时间',
    project_code                                  varchar(64)           null comment '项目编号',
    project_name                                  varchar(128)          null comment '项目名称',
    district                                      varchar(64)           null comment '所属区县',
    park                                          varchar(64)           null comment '所属园区',
    national_economic_classification              varchar(64)           null comment '国民经济分类',
    uscc                                          varchar(32)           null comment '统一社会信用代码',
    company_name                                  varchar(128)          null comment '企业名称',
    company_registration_funds                    int                   null comment '企业注册资金',
    company_registration_date                     date                  null comment '企业注册日期',
    project_category                              varchar(64)           null comment '项目类别',
    project_attribute                             varchar(64)           null comment '项目属性',
    project_content                               text                  null comment '项目内容',
    investment_flag                               varchar(50)           null comment '投资标识',
    country_region                                varchar(64)           null comment '国别/地区',
    specific_country_region                       varchar(64)           null comment '具体国别/地区',
    investor                                      varchar(128)          null comment '投资方',
    investment_amount                             float                 null comment '投资金额（亿美元/亿元）',
    registered_capital                            float                 null comment '注册资本（亿美元/亿元）',
    negotiation_progress                          varchar(128)          null comment '洽谈进度',
    industry_classification                       varchar(128)          null comment '国民经济行业分类',
    current_project_progress                      varchar(128)          null comment '当前项目进度',
    entry_time                                    datetime              null comment '入库时间',
    registration_info_statistics_date             date                  null comment '注册信息统计日期',
    certificate_data_business_license             varchar(128)          null comment '佐证资料（营业执照）',
    filing_approval_project_name                  varchar(128)          null comment '备案（核准）项目名称',
    filing_approval_investment_total              float                 null comment '备案（核准）投资总额（亿元）',
    filing_approval_date                          date                  null comment '备案（核准）日期',
    filing_info_statistics_date                   date                  null comment '备案信息统计日期',
    certificate_data_project_filing_approval_file varchar(128)          null comment '佐证资料（项目备案（核准）文件）',
    is_fixed_asset_investment                     boolean               null comment '是否涉及固定资产投资项目',
    is_construction_land                          boolean               null comment '是否涉及建设用地',
    construction_land_planning_permit_number      varchar(128)          null comment '建设用地规划许可证编号',
    permit_obtain_date                            date                  null comment '取得许可证日期',
    completion_report_statistics_date             date                  null comment '完成报批统计日期',
    certificate_data                              varchar(128)          null comment '佐证资料',
    start_confirm_date                            date                  null comment '开工确认日期',
    end_confirm_date                              date                  null comment '竣工确认日期',
    is_new_introduced_enterprise                  boolean               null comment '是否为新引进企业',
    project_rating                                varchar(128)          null comment '项目评级（内资、外资；金额分级）',
    main_investor_name                            varchar(128)          null comment '主要投资方名称',
    planned_total_investment                      float                 null comment '计划总投资（亿元）',
    project_location                              varchar(512)          null comment '项目选址位置',
    is_recruitment_fair_project                   boolean               null comment '是否为招商会项目',
    recruitment_fair_name                         varchar(128)          null comment '招商会名称',
    signing_time                                  datetime              null comment '签约时间',
    signing_contract                              varchar(128)          null comment '签约合同',
    total_investment_usd                          float                 null comment '项目总投资额（亿美元）',
    total_investment_cny                          float                 null comment '项目总投资额（亿元）',
    project_source                                varchar(128)          null comment '项目来源',
    factory_type                                  varchar(128)          null comment '厂房类型',
    planned_land_area                             float                 null comment '拟用地面积（平方米）',
    planned_rental_factory_area                   float                 null comment '拟租厂房面积（平方米）',
    planned_purchase_factory_area                 float                 null comment '拟购厂房面积（平方米）',
    expected_annual_sales                         float                 null comment '预计年销量（万元）',
    expected_annual_sales_amount                  float                 null comment '预计年销售（万元）',
    expected_annual_tax                           float                 null comment '预计年税收（万元）',
    project_type                                  varchar(128)          null comment '项目类型',
    industry_major_class_name                     varchar(128)          null comment '产业大类名称',
    belonging_industry                            varchar(128)          null comment '所属行业',
    investor_nature                               varchar(128)          null comment '投资方性质',
    project_profile                               text                  null comment '项目简介',
    is_world_top_500_or_leading_global_company    boolean               null comment '是否为世界500强或全球专业领域行业龙头企业',
    is_domestic_top_500_or_top_100_company        boolean               null comment '是否为国内500强或国内行业排名前100企业',
    is_publicly_traded_or_pre_IPO_company         boolean               null comment '是否为上市公司或上市辅导期企业',
    is_unicorn_startup                            boolean               null comment '是否为瞪羚、专精特新、独角兽企业',
    average_tax_per_mu_of_existing_investment     float                 null comment '已投资项目对属地政府亩均税收（万元）',
    major_customers                               varchar(128)          null comment '主要客户',
    fixed_asset_investment                        float                 null comment '固定资产投资（万元）',
    equipment_investment                          float                 null comment '设备投资（万元）',
    planned_start_time                            date                  null comment '计划开工时间',
    planned_end_time                              date                  null comment '计划竣工时间',
    main_raw_materials_used                       varchar(512)          null comment '项目使用主要原、辅材料',
    main_process_technology                       varchar(512)          null comment '主要流程工艺',
    is_new_supply_land_project                    boolean               null comment '是否为新供地项目',
    applied_land_area                             float                 null comment '申请用地面积（亩）',
    is_high_tech_industry                         boolean               null comment '行业是否属于高新技术产业分类目录',
    is_high_tech_project                          boolean               null comment '是否为高技术项目',
    is_national_strategic_emerging_industry       boolean               null comment '是否为国家工业战略性新兴产业',
    plot_ratio_percent                            float                 null comment '容积率（%）',
    expected_invoice_sales                        float                 null comment '预期开票销售（万元）',
    expected_tax                                  float                 null comment '预期税收（万元）',
    expected_employee_count                       int                   null comment '预期用工人数（人）',
    fixed_asset_investment_percentage             float                 null comment '固定资产投资占比（%）',
    investment_intensity                          float                 null comment '投资强度（万元/千平方米）',
    expected_average_tax                          float                 null comment '预期亩均税收（万元/千平方米）',
    wastewater_by1                                boolean               null comment '是否有产生废水和挥发性有机废水排放',
    wastewater_by2                                boolean               null comment '产生废水是否含氮、磷或使用高挥发性有机化合物含量涂料、油墨、胶粘剂',
    total_energy_consumption                      float                 null comment '总能耗',
    has_rnd_team_and_cooperation                  boolean               null comment '项目是否含有研发团队、产学研合作及研发机构建设内容',
    has_valid_patents                             boolean               null comment '项目是否拥有相关有效发明专利',
    is_listed_as_key_activity_signing_project     boolean               null comment '是否拟列入重点活动签约项目库',
    remarks                                       text                  null comment '备注',
    agreement_foreign_direct_investment           float                 null comment '协议利用外资（万美元）'
) comment '数字化招商';

drop table if exists project_online_approval;
create table project_online_approval
(
    id                                       char(20)              not null comment '主键' primary key,
    deleted                                  boolean default false not null comment '逻辑删除',
    create_time                              datetime              not null comment '创建时间',
    update_time                              datetime              not null comment '修改时间',
    approval_type                            varchar(128)          null comment '项目审批类型',
    filing_catalog                           varchar(128)          null comment '备案目录',
    filing_catalog_category                  varchar(128)          null comment '备案目录分类',
    project_code                             varchar(64)           null comment '项目代码',
    project_name                             varchar(128)          null comment '项目名称',
    main_project_name                        varchar(128)          null comment '主项目名称',
    is_supplementary_project                 boolean               null comment '是否补办项目',
    application_time                         datetime              null comment '申报时间',
    approval_time                            datetime              null comment '立项时间',
    review_filing_type                       varchar(128)          null comment '审核备类型',
    project_type                             varchar(128)          null comment '项目类型',
    construction_nature                      varchar(128)          null comment '建设性质',
    project_attributes                       varchar(128)          null comment '项目属性',
    planned_start_year                       smallint              null comment '拟开工时间（年）',
    planned_end_year                         smallint              null comment '拟建成时间（年）',
    construction_location                    text                  null comment '建设地点',
    national_industry_standard               varchar(128)          null comment '国标行业',
    national_industry_code                   varchar(64)           null comment '国标行业代码',
    management_industry                      varchar(128)          null comment '管理行业',
    construction_scale_and_content           text                  null comment '建设规模及内容',
    total_investment                         float                 null comment '总投资（万元）',
    total_investment_desc                    text                  null comment '总投资说明',
    land_area                                float                 null comment '用地面积（公顷）',
    new_land_area                            float                 null comment '新增用地面积（公顷）',
    agricultural_land_area                   float                 null comment '农用地面积（公顷）',
    project_capital                          float                 null comment '项目资本金（万元）',
    funding_source                           text                  null comment '资金来源',
    financial_funding_source                 varchar(16)           null comment '财政资金来源',
    is_technical_reform_project              boolean               null comment '是否技改项目',
    industrial_policy_type                   varchar(16)           null comment '产业政策类型',
    industry_adjustment_guidance_catalog     varchar(16)           null comment '产业结构调整指导目录',
    is_infrastructure_engineering            boolean               null comment '是否属于房屋市政工程',
    agree_to_provide_financing_services      boolean               null comment '是否同意投资平台为项目单位提供融资对接服务',
    legal_company                            varchar(128)          null comment '法人单位',
    legal_company_registration_type          varchar(16)           null comment '法人单位登记注册类型',
    legal_company_document_type              varchar(16)           null comment '法人单位证照类型',
    legal_company_document_number            varchar(64)           null comment '法人单位证照号码',
    legal_company_holding_situation          text                  null comment '法人单位控股情况',
    legal_company_contact_name               varchar(64)           null comment '法人单位联系人',
    legal_company_contact_phone              varchar(16)           null comment '法人单位手机号码',
    legal_company_contact_email              varchar(128)          null comment '法人单位电子邮箱',
    legal_company_legal_representative       varchar(64)           null comment '法人单位法人代表姓名',
    is_legal_company_controlling_for_project boolean               null comment '法人单位是否为该项目的控股单位',
    application_company                      varchar(128)          null comment '申报单位',
    application_company_registration_type    varchar(16)           null comment '申报单位登记注册类型',
    application_company_document_type        varchar(16)           null comment '申报单位证照类型',
    application_company_document_number      varchar(64)           null comment '申报单位证照号码',
    application_company_holding_situation    text                  null comment '申报单位控股情况',
    application_company_contact_name         varchar(64)           null comment '申报单位联系人',
    application_company_contact_phone        varchar(16)           null comment '申报单位手机号码'
) comment '在线审批项目';

drop table if exists project_construction_approval;
create table project_construction_approval
(
    id                                        char(20)              not null comment '主键' primary key,
    deleted                                   boolean default false not null comment '逻辑删除',
    create_time                               datetime              not null comment '创建时间',
    update_time                               datetime              not null comment '修改时间',
    project_code                              varchar(64)           null comment '项目代码',
    project_name                              varchar(128)          null comment '项目名称',
    administrative_division                   varchar(128)          null comment '项目地址-行政区划',
    detailed_address                          text                  null comment '项目详细地址',
    engineering_code                          varchar(64)           null comment '工程代码',
    approval_department                       varchar(64)           null comment '立项部门',
    industry_category                         varchar(64)           null comment '行业类别（国标行业）',
    project_type                              varchar(128)          null comment '项目类型',
    investment_source                         varchar(128)          null comment '项目投资来源',
    approval_type                             varchar(128)          null comment '立项类型',
    fund_attribute                            varchar(128)          null comment '项目资金属性',
    total_investment                          float                 null comment '总投资额（万元）',
    project_capital                           float                 null comment '项目资本金（万元）',
    is_over_one_billion_industrial_project    boolean               null comment '是否是亿元以上产业项目',
    is_concentrated_building_project          boolean               null comment '是否是集中建设项目',
    concentrated_builder_name                 varchar(128)          null comment '集中建设单位名称',
    concentrated_builder_uscc                 varchar(32)           null comment '集中建设单位统一社会信用代码',
    concentrated_builder_legal_representative varchar(16)           null comment '集中建设单位法定代表人姓名',
    company_type                              varchar(16)           null comment '单位类型',
    company_name                              varchar(32)           null comment '企业名称',
    uscc                                      varchar(32)           null comment '统一社会信用代码',
    legal_representative                      varchar(32)           null comment '法定代表人姓名',
    contact_phone                             varchar(20)           null comment '联系电话',
    has_design_plan                           boolean               null comment '土地是否带设计方案',
    regional_assessment_completed             boolean               null comment '是否完成区域评估',
    land_area_sqm                             float                 null comment '用地面积（㎡）',
    new_land_area_sqm                         float                 null comment '新增用地面积（㎡）',
    land_acquisition_method                   varchar(32)           null comment '土地获取方式',
    construction_nature                       varchar(32)           null comment '建设性质',
    construction_type                         varchar(32)           null comment '建设类型',
    total_floor_area_sqm                      float                 null comment '总建筑面积（㎡）',
    planned_start_date                        date                  null comment '拟开工时间',
    planned_completion_date                   date                  null comment '拟建成时间',
    longitude                                 float                 null comment '经度',
    latitude                                  float                 null comment '纬度',
    construction_content                      text                  null comment '建设内容（包括必要性）'
) comment '工程建设审批';
