/* tslint:disable */
/* eslint-disable */
/**
 * 企业全生命周期
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    PageableResultEnterpriseGdpVo,
    PageableResultEnterpriseGdpVoFromJSON,
    PageableResultEnterpriseGdpVoToJSON,
    PageableResultParkGdpVo,
    PageableResultParkGdpVoFromJSON,
    PageableResultParkGdpVoToJSON,
} from '../models';

export interface GetGdpListRequest {
    year: number;
    industrialSystem?: string;
    futureIndustry?: boolean;
    page?: number;
    size?: number;
}

export interface GetGdpListByParkRequest {
    year: number;
    page?: number;
    size?: number;
}

/**
 * 
 */
export class PrimeApiGDPApi extends runtime.BaseAPI {

    /**
     * 查询GDP
     */
    async getGdpListRaw(requestParameters: GetGdpListRequest): Promise<runtime.ApiResponse<PageableResultEnterpriseGdpVo>> {
        if (requestParameters.year === null || requestParameters.year === undefined) {
            throw new runtime.RequiredError('year','Required parameter requestParameters.year was null or undefined when calling getGdpList.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.industrialSystem !== undefined) {
            queryParameters['industrialSystem'] = requestParameters.industrialSystem;
        }

        if (requestParameters.futureIndustry !== undefined) {
            queryParameters['futureIndustry'] = requestParameters.futureIndustry;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/gdp/{year}`.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters.year))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PageableResultEnterpriseGdpVoFromJSON(jsonValue));
    }

    /**
     * 查询GDP
     */
    async getGdpList(requestParameters: GetGdpListRequest): Promise<PageableResultEnterpriseGdpVo> {
        const response = await this.getGdpListRaw(requestParameters);
        return await response.value();
    }

    /**
     * 按板块查询GDP
     */
    async getGdpListByParkRaw(requestParameters: GetGdpListByParkRequest): Promise<runtime.ApiResponse<PageableResultParkGdpVo>> {
        if (requestParameters.year === null || requestParameters.year === undefined) {
            throw new runtime.RequiredError('year','Required parameter requestParameters.year was null or undefined when calling getGdpListByPark.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/gdp/{year}/by-park`.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters.year))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PageableResultParkGdpVoFromJSON(jsonValue));
    }

    /**
     * 按板块查询GDP
     */
    async getGdpListByPark(requestParameters: GetGdpListByParkRequest): Promise<PageableResultParkGdpVo> {
        const response = await this.getGdpListByParkRaw(requestParameters);
        return await response.value();
    }

}
